#+title: Ps 01
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-12-02>
#+lastmod: <2025-12-03 16:58>
#+options: num:t
#+startup: overview

* Problem 1
** Task
Verifying the definition of a field

show that $\mathbb{F}_{2}$ is indeed a field (see example ii.1.5 in the lecture notes).

** Notes
:LOGBOOK:
CLOCK: [2025-12-02 Tue 13:51]--[2025-12-02 Tue 14:16] =>  0:25
:END:
*Definition:* A field $F$ is a set with 2 binary operations +, * defined such that for each pair elements $a,b$ in the set, there are unique elements $a + b$ and $a \cdot b$ in field for which the following axioms hold for all $a,b,c,d$ in $F$:

1. $a + b = b + a$ and $a \cdot b = b \cdot a$ (commutativity)
2. $(a + b) + c = a + (b + c)$ and $(a \cdot b) \cdot c = a \cdot (b \cdot c)$ (associativity)
3. There exists distinct elements 0 and 1 in $F$ such that:
   $0 + a = a$ and $1 \cdot a = a$ (existence of identity)
4. For each $a$ in $F$ and non-zero element $b$ in $F$, there exists $c,d$ in $F$ such that $a + c = 0$ and $b \times d = 1$ (existence of inverses)
5. $a \cdot (b + c) = a \cdot b + a \cdot c$ (distributivity)

** Solution
*Goal:* To show $\mathbb{F}$ is a field by validating the axioms.

*Definition:*

$0 \boxplus 0 = 1 \boxplus 1 = 0$ and $1 \boxplus 0 = 0 \boxplus 1 = 1$
$0 \boxtimes 0 = 1 \boxtimes 0 = 0 \boxtimes 1 = 0$ and $1 \boxtimes 1 = 1$

1. *Commutativity.*

   $1 \boxplus 0 = 0 \boxplus 1$
   $0 \boxtimes 1 = 1 \boxtimes 0$ by definition. Hence, commutativity holds.

2. *Associativity.*

   Proof by exhaustion:
   |---+---+---+-----------------------------+-----------------------------|
   | a | b | c | $(a \boxplus b) \boxplus c$ | $a \boxplus (b \boxplus c)$ |
   |---+---+---+-----------------------------+-----------------------------|
   | 0 | 0 | 0 |                           0 |                           0 |
   |---+---+---+-----------------------------+-----------------------------|
   | 0 | 0 | 1 |                           1 |                           1 |
   |---+---+---+-----------------------------+-----------------------------|
   | 0 | 1 | 0 |                           1 |                           1 |
   |---+---+---+-----------------------------+-----------------------------|
   | 0 | 1 | 1 |                           0 |                           0 |
   |---+---+---+-----------------------------+-----------------------------|
   | . | . | . |                         ... |                         ... |
   |---+---+---+-----------------------------+-----------------------------|

   |---+---+---+-------------------------------+-------------------------------|
   | a | b | c | $(a \boxtimes b) \boxtimes c$ | $a \boxtimes (b \boxtimes c)$ |
   |---+---+---+-------------------------------+-------------------------------|
   | 0 | 0 | 0 |                             0 |                             0 |
   |---+---+---+-------------------------------+-------------------------------|
   | 0 | 0 | 1 |                             0 |                             0 |
   |---+---+---+-------------------------------+-------------------------------|
   | 0 | 1 | 0 |                             0 |                             0 |
   |---+---+---+-------------------------------+-------------------------------|
   | 0 | 1 | 1 |                             0 |                             0 |
   |---+---+---+-------------------------------+-------------------------------|
   | . | . | . |                           ... |                           ... |
   |---+---+---+-------------------------------+-------------------------------|
   (tidious)
   Hence, associativity holds.

3. *Existence Identity.*

   $1 \boxplus 0 = 1$ and $0 \boxplus 0 = 0$,
   $1 \boxtimes 1 = 1$ and $0 \boxtimes 1 = 0$ by definition. Hence, existence identity holds.

4. *Existence Inverse.*

   $0 \boxplus 0 = 1 \boxplus 1 = 0$,
   $1 \boxtimes 1 = 1$ by definition. Hence, existence inverse holds.

5. *Distributivity.*

   - Case 1 (a = 0): $0 \boxtimes (...) = 0$ and $0 \boxplus 0 = 0$

   - Case 2 (a = 1): $1 \boxtimes (b \boxplus c) = b \boxplus c$
                     ($1 \boxtimes b) \boxplus (1 \boxtimes c) = b \boxplus c$

   Distributivity holds.

*Conclusion:* All axioms validated, $(\{0,1\},\boxplus,\boxtimes)$ is a field.

* Problem 2
** Task
Properties of fields

In the remainder of the course, we will use field arithmetic operations rather casually, tacitly relying on the respective axioms and their consequences instead of explicitly citing them to justify every elementary arithmetic transformation. Even for completely new specific or even abstract sets and operations, that will be very similar to how you have been using arithmetic operations over natural, integer, rational and real numbers in your mathematical journey so far.

This problem, however, is different: we will practice the explicit use of the definition of a field, presenting arguments in elementary steps, each relying on and explicitly justified by a single stipulation of the definition (an axiom or another detail of the definition). Examples of such steps are logical implications and arithmetic transformations, and each single one should be elementary in the above sense. Section II.1(ii) of the lecture notes presents examples of arguments structured into such elementary steps. An exception: in each problem part, a step relying on a single statement claimed to be true in a preceding problem part is considered elementary, i.e., statements from preceding problem parts may be used (with a proper reference).

Show the following properties of a field $\mathbb{F}$ with operations and of addition and multiplication and with additive and multiplicative identity elements $0$ and $1$.

(a) Every element has a unique additive inverse.

(b) Every element distinct from $0$ has a unique multiplicative inverse.

(c) For any $\alpha, \beta, \gamma \in \mathbb{F}$, $\alpha \boxplus \gamma = \beta \boxplus \gamma$ implies $\alpha=\beta$

(d) The implication $(\gamma \boxplus \alpha = \gamma \boxplus \beta) \Rightarrow (\alpha = \beta)$ holds for any $\alpha, \beta, \gamma \in \mathbb{F}$.

(e) The statements $a \boxtimes \gamma = \beta \boxtimes \gamma$ and $\alpha=\beta$ are equivalent for any $\alpha,\beta\in\mathbb{F}$ and $\gamma\in\mathbb{F}\backslash\{0\}$.

(f) Consider $\alpha,\beta,\gamma\in\mathbb{F}$ such that $\gamma\ne0$ and $\gamma \boxtimes \alpha = \gamma \boxtimes \beta$. Then $\alpha=\beta$.

(g) Every $\alpha\in\mathbb{F}$ fulfills $0 \times \alpha = 0$.
    Hint: this statement expresses a non-symmetric relation between the two field operations, so the proof clearly has to use one or several of the field axioms that introduce dissimilarities of the operations.

(h) Let $-1$ denote /the/ additive inverse of $1$ in $\mathbb{F}$. Then every $\alpha\in\mathbb{F}$ and /the/ additive inverse $-a$ of $a$ satisfies $-\alpha = (-1) \boxtimes \alpha$.
h.i Does your solution prove the uniqueness of the additive inverses?
h.ii Does your solution rely on the uniqueness of the additive inverses?

(i) Additive inversion is an involution: if is an additive inverse of $\alpha\in\mathbb{F}$ and $y$ is an additive inverse of , then $\alpha=\gamma$.
Hint: consider the expression $\alpha\oplus\beta\oplus\gamma$.

** Notes
In this problem I will practice using field definitions, splitting all field arithmetic operations into elementary and axiom level.

All below problems would imply a field $\mathbb{F}$ with some additive and multiplicative functions $\boxplus$ and $\boxtimes$ and set of $\{0, 1\}$.

Definitions addopted from `II.1.5 of Vladimir Kazeev's paper`.

$0 \boxplus 0 = 1 \boxplus 1 = 0$ and $1 \boxplus 0 = 0 \boxplus 1 = 1$
$0 \boxtimes 0 = 1 \boxtimes 0 = 0 \boxtimes 1 = 0$ and $1 \boxtimes 1 = 1$

No, actually this is wrong. I misread the exercise, it actually says "Show the following properties of a field $\mathbb{F}$ ... with additive and multiplicative identity elements $0$ and $1$.". Hence,

- size of set $\mathbb{F}$ is unknown
- element that behaves as additive identity is labelled as $'0'$
- element that behaves as multiplicative identity is labelled as $'1'$

What about writing definitons on top of this document and use the same citation as it is done in Kazeev's paper? It will be more structred I believe.

Moral of the story: "Moral of the story" looks more funnier than the boring "Conclusion:"

In 2.e, I should show equivalence, which should mean both of them should lead to one another. Lets try.

** Solution
*** Definitons
#+begin_quote
*Definition 1: (field)* Consider a set $\mathbb{F}$ with distinct $0,1 \in \mathbb{F}$ and functions $\boxplus: \mathbb{F} \times \mathbb{F} \to \mathbb{F}$ and $\boxtimes: \mathbb{F} \times \mathbb{F} \to \mathbb{F}$. The set $\mathbb{F}$ is called a /field/ with operations $\boxplus$ and $\boxtimes$ of /addition/ and /multiplication/ and with /additive/ and /multiplicative identity elements/ $0$ and $1$ if the following conditions are satisfied.

  a) *Commutativity:* $\alpha \boxplus \beta = \beta \boxplus \alpha$ and $\alpha \boxtimes \beta = \beta \boxtimes \alpha$ for any $\alpha, \beta \in \mathbb{F}$.

  b) *Associativity:* $(\alpha \boxplus \beta) \boxplus \gamma = \alpha \boxplus (\beta \boxplus \gamma)$ and $(\alpha \boxtimes \beta) \boxtimes \gamma = \alpha \boxtimes (\beta \boxtimes \gamma)$ for any $\alpha, \beta, \gamma \in \mathbb{F}$.

  c) *Neutrality of identity elements:* $0 \boxplus \alpha = \alpha$ and $1 \boxtimes \alpha = \alpha$ for any $\alpha \in \mathbb{F}$.

  d) *Additive inversion:* For every $\alpha \in \mathbb{F}$, there exists $\beta \in \mathbb{F}$ such that $\alpha \boxplus \beta = 0$.

  e) *Multiplicative inversion:* For every $\alpha \in \mathbb{F}$ such that $\alpha \neq 0$, there exists $\beta \in \mathbb{F}$ such that $\alpha \boxtimes \beta = 1$.

  f) *Distributivity:* $\alpha \boxtimes (\beta \boxplus \gamma) = (\alpha \boxtimes \beta) \boxplus (\alpha \boxtimes \gamma)$ for any $\alpha, \beta, \gamma \in \mathbb{F}$.
#+end_quote

#+begin_quote
*Definition 2: (antisymmetric relation)* If $aRb$ with $a \neq b$, then $bRa$ must *not* hold.
#+end_quote

*** a. Every element has a unique additive inverse.
Let $a \in \mathbb{F}$. Assume $\exists b,c : a \boxplus b = 0, \ a \boxplus c = 0$. Hence,

$b = b \boxplus 0$ (Definition 1.c)
$b = b \boxplus (a \boxplus c)$ (Definition 1.d)
$b = (b \boxplus a) \boxplus c$ (Definition 1.b)
$b = (a \boxplus b) \boxplus c$ (Definition 1.a)
$b = 0 \boxplus c$ (Definition 1.d)
$b = c$ (Definition 1.c)

*Moral of the story:* Since $b = c$, additive inverse is unique.

*** b. Every element distinct from $0$ has a unique multiplicative inverse.
Let $a \in \mathbb{F} \backslash \{0\}$. Assume $\exists b,c : a \boxtimes b = 1, \ a \boxtimes c = 1$. Hence,

$a \boxtimes b = 1 = a \boxtimes c$ (by definition)
$a \boxtimes b = a \boxtimes c$ (simplifying)
$a \boxtimes b \boxtimes b = a \boxtimes c \boxtimes b$ (multiply both sides by $b$)
$(a \boxtimes b) \boxtimes b = (a \boxtimes b) \boxtimes c$ (Definitions 1.a, 1.b)
$1 \boxtimes b = 1 \boxtimes c$ (simplifying)
$b = c$ (Definition 1.c)

*Moral of the story:* Since $b = c$, miltiplicative inverse is unique.

*** c. For any $\alpha, \beta, \gamma \in \mathbb{F}$, $\alpha \boxplus \gamma = \beta \boxplus \gamma$ implies $\alpha=\beta$

Let $\delta$ be additive inverse of $\gamma$ (Definition 1.d)
$\alpha \boxplus \gamma = \beta \boxplus \gamma$ (by definition)
$\alpha \boxplus \gamma \boxplus \delta = \beta \boxplus \gamma \boxplus \delta$ (adding $\delta$ to both sides)
$\alpha \boxplus (\gamma \boxplus \delta) = \beta \boxplus (\gamma \boxplus \delta)$ (Definition 1.b)
$\alpha \boxplus 0 = \beta \boxplus 0$ (Definition 1.d)
$\alpha = \beta$ (Definition 1.c)

*Moral of the story:* Implication holds.

*** d. The implication $(\gamma \boxplus \alpha = \gamma \boxplus \beta) \Rightarrow (\alpha = \beta)$ holds for any $\alpha, \beta, \gamma\in\mathbb{F}$.

$\gamma \boxplus \alpha = \gamma \boxplus \beta$ (by definition)
$\alpha \boxplus \gamma = \beta \boxplus \gamma$ (Definition 1.a)

As shown in part c, $\alpha, \beta, \gamma \in \mathbb{F}, \ \alpha \boxplus \gamma = \beta \boxplus \gamma \implies \alpha = \beta$.

Hence, $\alpha = \beta$.

*Moral of the story:* Implication holds.
*** e. The statements $a \boxtimes \gamma = \beta \boxtimes \gamma$ and $\alpha=\beta$ are equivalent for any $\alpha,\beta\in\mathbb{F}$ and $\gamma\in\mathbb{F}\backslash\{0\}$

1. $(\alpha \boxtimes \gamma = \beta \boxtimes \gamma) \implies \alpha = \beta$

   Let $\delta$ be the multiplicative inverse of $\gamma$ (Definition 1.e, since $\gamma \neq 0$).
   $\alpha \boxtimes \gamma = \beta \boxtimes \gamma$ (by definition)
   $\alpha \boxtimes \gamma \boxtimes \delta = \beta \boxtimes \gamma \boxtimes \delta$ (multiply both sides by $\delta$)
   $\alpha \boxtimes (\gamma \boxtimes \delta) = \beta \boxtimes (\gamma \boxtimes \delta)$ (Definition 1.b)
   $\alpha \boxtimes 1 = \beta \boxtimes 1$ (Definition 1.e)
   $\alpha = \beta$ (Definition 1.c)

2. $\alpha = \beta \implies (\alpha \boxtimes \gamma = \beta \boxtimes \gamma)$

   $\alpha = \beta$ (by definition)
   $\alpha \boxtimes \gamma = \beta \boxtimes \gamma$ (operation is well-defined)

*Moral of the story:* Equivalency holds.
*** f. Consider $\alpha,\beta,\gamma\in\mathbb{F}$ such that $\gamma\ne0$ and $\gamma \boxtimes \alpha = \gamma \boxtimes \beta$. Then $\alpha=\beta$.

Let $\delta$ be multiplicative inverse of $\gamma$ (Definition 1.e, since $\gamma \neq 0$).
$\gamma \boxtimes \alpha = \gamma \boxtimes \beta$ (by definition)
$\alpha \boxtimes \gamma = \beta \boxtimes \gamma$ (Definition 1.a)
$\alpha \boxtimes \gamma \boxtimes \delta = \beta \boxtimes \gamma \boxtimes \delta$ (well-defined operation)
$\alpha \boxtimes (\gamma \boxtimes \delta) = \beta \boxtimes (\gamma \boxtimes \delta)$ (Definition 1.b)
$\alpha \boxtimes 1 = \beta \boxtimes 1$ (Defintion 1.e)
$\alpha = \beta$ (Defintion 1.c)

*Moral of the story:* Implication holds.
*** g. Every $\alpha\in\mathbb{F}$ fulfills $0 \times \alpha = 0$.

$0 = 0 \boxplus 0$ (Definition 1.c)
$0 \boxtimes \alpha = (0 \boxplus 0) \boxtimes \alpha$ (well-defined operation)
$0 \boxtimes \alpha = (0 \boxtimes \alpha) \boxplus (0 \boxtimes \alpha)$ (Definition 1.f)
Let $\beta = 0 \boxtimes \alpha$. Hence,
$\beta = \beta \boxplus \beta$ (substitution)
Let $-\beta$ be additive inverse of $\beta$.
$\beta \boxplus -\beta = \beta \boxplus \beta \boxplus -\beta$ (well defined operation)
$0 = \beta \boxplus \beta \boxplus -\beta$ (Definition 1.d)
$0 = \beta \boxplus (\beta \boxplus -\beta)$ (Definition 1.b)
$0 = \beta \boxplus 0$ (Definition 1.d)
$0 = \beta$ (Definition 1.c)
$0 = \alpha \boxtimes 0$ (substitution)

*Moral of the story:* Multiplication by zero results in zero.

*** h. Let $-1$ denote /the/ additive inverse of $1$ in $\mathbb{F}$. Then every $\alpha\in\mathbb{F}$ and /the/ additive inverse $-a$ of $a$ satisfies $-\alpha = (-1) \boxtimes \alpha$.
h.i Does your solution prove the uniqueness of the additive inverses?
h.ii Does your solution rely on the uniqueness of the additive inverses?

Assumption: $\alpha \boxplus ((-1) \boxtimes \alpha) = 0$.
l$\implies (1 \boxtimes \alpha) \boxplus ((-1) \boxtimes \alpha)$ (Definition 1.c)
$\implies (1 \boxplus (-1)) \boxtimes \alpha$ (Definition 1.f)
$\implies 0 \boxtimes \alpha$ (Definition 1.d)
$\implies 0$ (part g)

Since $\alpha \boxplus ((-1) \boxtimes \alpha)$ behaves like additive inverse, and as proved in part a, which states the uniqueness of an additive inverse, above expression is indeed an additive inverse.

*Moral of the story:* $-\alpha = (-1) \boxtimes \alpha$

- h.i
  No, it was proven in part a of the same exercise.

- h.ii
  Yes. The final point heavily relies on the uniqueness of the additive inverse.

* Problem 3
** Task
Discrete cosine and Fourier transforms

Introduction. In several exercise sheets, we will be exploring the discrete cosine and Fourier transforms (DCTs and DFT). Apart from being intimately connected with and serving as approximations to the (real) trigonometric and (complex) Fourier series, which you will study in the Analysis course, such transforms are instrumental for interpolation with trigonometric and algebraic polynomials (we will come to that later in the course). That makes them an important topic in numerical mathematics and numerous applications, including signal and image processing. In fact, you must have been unwittingly using DCT-II daily for a long time now: the transform underlies the JPEG standard for image compression and the MPEG and H.26x standards for video compression.

In this assignment, we start with the DFT and investigate the similarity in how the DFT maps the two halves of the input column vector into the two halves of the output column vector. This will later lead us a fast DFT algorithm, known as the fast Fourier transform (FFT). The somewhat more modern term quantum Fourier transform (QFT) refers to a realization of the same FFT algorithm on a quantum computer. Apart from the challenges associated with quantum hardware and from the unfortunate notations favored by physicists due to historical reasons, the QFT algorithm itself has nothing quantum in it and perfectly falls into the scope of our course.

To the point. For a data dimension $n\in\mathbb{N}$, the DFT involves the matrix $F\in\mathbb{C}^{n\times n}$ defined entrywise as follows:
$$F_{ij}=\exp[i\frac{2\pi}{n}(i-1)(j-1)]$$
for all $i,j\in\{1,...,n\}$, where $i$ is the imaginary unit (see § 1.2 in the lecture notes). (1)

For $m\in\mathbb{N}$ and $n=2m,$ we consider the matrix $F\in\mathbb{C}^{n\times n}$ given by (1). Our goal is to relate this matrix to the smaller matrix $\hat{F}\in\mathbb{C}^{m\times m}$ given by (1) with $m$ in place of $n$. To this end, we select four submatrices of size $m\times m$ in $F$ as follows.
For all $\alpha,\beta\in\{1,2\}$ the submatrices $F_{\alpha\beta}$ are formed by the $m$ odd (for $\alpha=1$) or by the $m$ even (for $\alpha=2$) rows and by the first $m$ (for $\beta=1$) or by the last $m(\beta=2)$ columns of $F$. In each case, the rows and columns are selected in the original order, as they follow in $F$. Formalizing this definition is part of this exercise.

For every $k\in\{1,...,m\}$, we set
$$e_{k}=\exp\frac{i\pi(k-1)}{m}$$
(2)

(a) Verify the following equalities for all $k,j\in\{1,...,m\}$
$$(F_{11})_{kj}=\hat{F_{kj}}$$
(3a)
$$(F_{21})_{kj}=e_{j}\cdot\hat{F_{kj}}$$
(3b)
$$(F_{12})_{kj}=(F_{11})_{kj},$$
(3c)
$$(F_{22})_{kj}=-(F_{21})_{kj}.$$
(3d)

Hint: rewrite (3a)-(3d) for arbitrary $k,j\in\{1,...,m\}$ in an equivalent explicit form not using the matrices introduced above. Prove the resulting equalities for arbitrary $k, j\in\{1,...,m\}$ using properties of the complex exponential function (see § 1.2(vii) in the lecture notes).

(b) Rewrite equalities of (3a)-(3d) with $k,j\in\{1,...,m\}$ as four matrix equalities (involving matrix multiplication and auxiliary matrices where necessary but not involving individual entries) expressing $F_{11}$, $F_{21}$, $F_{12}$ and $F_{22}$ in terms of $\hat{F}$

(c) Implement a Julia function dft matrix that, for any (reasonable) $l\in\mathbb{N}$ produces the DFT matrix $F=$ dft matrix(l) of order $n=2^{l}$ as defined by (1).

(d) For $l=3$, $n=2^{l}$ and $m=2^{l-1}$, use dft matrix to form the DFT matrices $F$ and $\hat{F}$ of orders $n$ and $m$, extract the submatrices $F_{11},$ $F_{21}$, $F_{12}$ and $F_{22}$ of $F$ and verify (3a)-(3d).
Hint: to verify that two matrices are equal, you can evaluate their difference and use the function norm from the package LinearAlgebra.

(e) Repeat part (d) for $l=8$
** Notes
[empty]
** Solution
[empty]
