#+title: Exam V A Solution
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-17>
#+lastmod: <2025-11-17 13:42>
#+options: num:t
#+startup: overview

* 1. Problem 1 [DONE]
** Task
Truth table: `P ‚ą® ¬¨Q -> P ‚ąß Q`

Construct the full truth table.

** Solution
|---+---+----+--------+-------+-----------------|
| P | Q | ¬¨Q | P ‚ą® ¬¨Q | P ‚ąß Q | P ‚ą® ¬¨Q -> P ‚ąß Q |
|---+---+----+--------+-------+-----------------|
| T | T | F  | T      | F     | F               |
|---+---+----+--------+-------+-----------------|
| T | F | T  | T      | T     | T               |
|---+---+----+--------+-------+-----------------|
| F | T | F  | F      | F     | F               |
|---+---+----+--------+-------+-----------------|
| F | F | T  | T      | F     | F               |
|---+---+----+--------+-------+-----------------|

* 2. Problem 2 [DONE]
** Task
Compute: gcd(225, 135)

** Solution
gcd(225, 135)

225 = 135 * 1 + 90
135 = 90 * 1 + 45
90 = 45 * 2 + 0

Hence,
gcd(225, 135) = 45

* 3. Problem 3 [DONE]
** Task
Induction

‚ąĎ(n, l = 1)(1/(l(l+1))) = n/(n+1)

** Solution
#+begin_quote
*Proposition.* ‚ąĎ(n, l = 1)(1/(l(l+1))) = n/(n+1)

*Base case.* n = 1.

‚ąĎ(1, l = 1)(1/(l(l+1))) = 1/(1+1)
1/(1(1+1)) = 1/(1+1)
1/2 = 1/2

*Inductive hypothesis.* Assume ‚ąĎ(n, l = 1)(1/(l(l+1))) = n/(n+1).

*Induction step.*

‚ąĎ(n, l = 1)(1/(l(l+1))) + 1/((n+1)((n+1)+1)) = n/(n+1) + 1/((n+1)((n+1)+1))

‚ąĎ(n+1, l = 1)(1/(l(l+1))) = n/(n+1) + 1/((n+1)(n+2))

‚ąĎ(n+1, l = 1)(1/(l(l+1))) = (n(n+2))/((n+1)(n+2)) + 1/((n+1)(n+2))

‚ąĎ(n+1, l = 1)(1/(l(l+1))) = (n(n+2) + 1)/((n+1)(n+2))

‚ąĎ(n+1, l = 1)(1/(l(l+1))) = (n^2 + 2n + 1)/((n+1)(n+2))

‚ąĎ(n+1, l = 1)(1/(l(l+1))) = ((n + 1)^2)/((n+1)(n+2))

‚ąĎ(n+1, l = 1)(1/(l(l+1))) = (n+1)/((n+1)+1)

*Conclusion.* Hence,
              ‚ąĎ(n, l = 1)(1/(l(l+1))) = n/(n+1)

              implies

              ‚ąĎ(n+1, l = 1)(1/(l(l+1))) = (n+1)/((n+1)+1)
#+end_quote
* 4. Problem 4 [DONE]
** Task
Divisibility exercise

3 !| a
3 !| b

--> 3|(a^2 - b^2)

** Solution
- Case 1: a ‚Č° 1, b ‚Č° 1 (mod 3)

  Hence,
  a^2 ‚Č° 1^2 ‚Č° 1 (mod 3)
  b^2 ‚Č° 1^2 ‚Č° 1 (mod 3)

  Thus,
  a^2 - b^2 ‚Č° 1 - 1 ‚Č° 0 (mod 3)

- Case 2: a ‚Č° 1, b ‚Č° 2 (mod 3)

  Hence,
  a^2 ‚Č° 1^2 ‚Č° 1 (mod 3)
  b^2 ‚Č° 2^2 ‚Č° 4 (mod 3)

  Thus,
  a^2 - b^2 ‚Č° 1 - 4 ‚Č° -3 ‚Č° 0 (mod 3)

- Case 3: a ‚Č° 2, b ‚Č° 1 (mod 3)

  Hence,
  a^2 ‚Č° 2^2 ‚Č° 4 (mod 3)
  b^2 ‚Č° 1^2 ‚Č° 1 (mod 3)

  Thus,
  a^2 - b^2 ‚Č° 4 - 1 ‚Č° 3 ‚Č° 0 (mod 3)

- Case 4: a ‚Č° 2, b ‚Č° 2 (mod 3)

  Hence,
  a^2 ‚Č° 2^2 ‚Č° 4 (mod 3)
  b^2 ‚Č° 2^2 ‚Č° 4 (mod 3)

  Thus,
  a^2 - b^2 ‚Č° 4 - 4 ‚Č° 0 (mod 3)

Hence, 3|(a^2 - b^2).

* 5. Problem 5 [DONE]
** Task
Relation on P(S) where S = {1,2,3,4}
such that for x,y:

x‚Čľy <--> x ‚äÜ y

- Prove that it is a partial order.
- Show whether it is a total order.

** Solution
#+begin_quote
*Proposition.* x‚Čľy <--> x ‚äÜ y, on P(S) where S = {1,2,3,4} is a partial order.

P(S) = {‚ąÖ, {1}, {2}, {3}, {4}, {1,2}, ...}

- *Reflexive:* ‚ąÄa‚ąąA; a‚Čľa.

  Let a ‚ąą P(S).

  Hence, a ‚äÜ a. Since a = a.

  Thus, ‚ąÄa‚ąąP(S); a‚Čľa.

- *Antisymmetric:* ‚ąÄa,b‚ąąA; (a‚Čľb ‚ąß b‚Čľa) --> a=b.

  Let a,b ‚ąą P(S). Assume a‚Čľb and b‚Čľa.

  Hence,
  a ‚äÜ b
  b ‚äÜ a

  Therefore, a = b

  Thus, ‚ąÄa,b‚ąąP(S); (a‚Čľb ‚ąß b‚Čľa) --> a=b.

- *Transitive:* ‚ąÄa,b,c‚ąąA; (a‚Čľb ‚ąß b‚Čľc) --> a‚Čľc.

  Let a,b,c ‚ąą P(S). Assume a‚Čľb and b‚Čľc.

  Hence,
  a ‚äÜ b
  b ‚äÜ c

  Therefore,
  a ‚äÜ b ‚äÜ c
  a ‚äÜ c

  Thus, ‚ąÄa,b,c‚ąąP(S); (a‚Čľb ‚ąß b‚Čľc) --> a‚Čľc.

*Conclusion.* Since ‚Čľ is reflexive, antisymmetric and transitive, it is a partial order.
#+end_quote

#+begin_quote
*Proposition.* x‚Čľy <--> x ‚äÜ y, on P(S) where S = {1,2,3,4} is a total order.

*Proof.*
Since x,y ‚ąą P(S),

{1} = x
{2} = y

Hence, {1} ‚äĄ {2} --> x ‚äĄ y and {2} ‚äĄ {1} --> y ‚äĄ x.

Thus, ‚Čľ is not a total order.
#+end_quote

* 6. Problem 6
** Task
Function properties

- Let `f(x) = (x^2 / 2) - 1`
  a) Prove it is surjective
  b) Check whether it is injective
  c) Determine whether it is bijective

** Solution

* 7. Problem 7
** Task
Countability

- A = {Pi * g : g ‚ąą ‚Ąö}
- ‚ą™(‚ąě, n = 1)[0, 1/n]
- Decide whether the given set(s) are countable or uncountable.

** Solution

* 8. Problem 8
** Task
Set S = {I, J, K, L, M, N, O, P}

How many 8-letter words can be formed such that:
a) Each letter is only used once
b) Letters may be reused as many times as desired
c) M must appear before N in the word

** Solution

* 9. Problem 9
** Task
Modular

- 421 ‚Č° ? (mod 21)
- 21321 ‚Č° ? (mod 21)

** Solution

* 10. Problem 10
** Task
Solve the equation (algebraic or trigonometric form)

z^3 = -8i

** Solution

* 11. Problem 11
** Task
Solve this

(x^4 + x + 1) / (x - 1)

** Solution
