#+title: Exam V A Solution
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-17>
#+lastmod: <2025-11-17 18:07>
#+options: num:t
#+startup: overview

* 1. Problem 1 [DONE]
** Task
Truth table: `P ‚ą® ¬¨Q -> P ‚ąß Q`

Construct the full truth table.

** Solution
|---+---+----+--------+-------+-----------------|
| P | Q | ¬¨Q | P ‚ą® ¬¨Q | P ‚ąß Q | P ‚ą® ¬¨Q -> P ‚ąß Q |
|---+---+----+--------+-------+-----------------|
| T | T | F  | T      | F     | F               |
|---+---+----+--------+-------+-----------------|
| T | F | T  | T      | T     | T               |
|---+---+----+--------+-------+-----------------|
| F | T | F  | F      | F     | F               |
|---+---+----+--------+-------+-----------------|
| F | F | T  | T      | F     | F               |
|---+---+----+--------+-------+-----------------|

* 2. Problem 2 [DONE]
** Task
Compute: gcd(225, 135)

** Solution
gcd(225, 135)

225 = 135 * 1 + 90
135 = 90 * 1 + 45
90 = 45 * 2 + 0

Hence,
gcd(225, 135) = 45

* 3. Problem 3 [DONE]
** Task
Induction

‚ąĎ(n, l = 1)(1/(l(l+1))) = n/(n+1)

** Solution
#+begin_quote
*Proposition.* ‚ąĎ(n, l = 1)(1/(l(l+1))) = n/(n+1)

*Base case.* n = 1.

‚ąĎ(1, l = 1)(1/(l(l+1))) = 1/(1+1)
1/(1(1+1)) = 1/(1+1)
1/2 = 1/2

*Inductive hypothesis.* Assume ‚ąĎ(n, l = 1)(1/(l(l+1))) = n/(n+1).

*Induction step.*

‚ąĎ(n, l = 1)(1/(l(l+1))) + 1/((n+1)((n+1)+1)) = n/(n+1) + 1/((n+1)((n+1)+1))

‚ąĎ(n+1, l = 1)(1/(l(l+1))) = n/(n+1) + 1/((n+1)(n+2))

‚ąĎ(n+1, l = 1)(1/(l(l+1))) = (n(n+2))/((n+1)(n+2)) + 1/((n+1)(n+2))

‚ąĎ(n+1, l = 1)(1/(l(l+1))) = (n(n+2) + 1)/((n+1)(n+2))

‚ąĎ(n+1, l = 1)(1/(l(l+1))) = (n^2 + 2n + 1)/((n+1)(n+2))

‚ąĎ(n+1, l = 1)(1/(l(l+1))) = ((n + 1)^2)/((n+1)(n+2))

‚ąĎ(n+1, l = 1)(1/(l(l+1))) = (n+1)/((n+1)+1)

*Conclusion.* Hence,
              ‚ąĎ(n, l = 1)(1/(l(l+1))) = n/(n+1)

              implies

              ‚ąĎ(n+1, l = 1)(1/(l(l+1))) = (n+1)/((n+1)+1)
#+end_quote
* 4. Problem 4 [DONE]
** Task
Divisibility exercise

3 !| a
3 !| b

--> 3|(a^2 - b^2)

** Solution
- Case 1: a ‚Č° 1, b ‚Č° 1 (mod 3)

  Hence,
  a^2 ‚Č° 1^2 ‚Č° 1 (mod 3)
  b^2 ‚Č° 1^2 ‚Č° 1 (mod 3)

  Thus,
  a^2 - b^2 ‚Č° 1 - 1 ‚Č° 0 (mod 3)

- Case 2: a ‚Č° 1, b ‚Č° 2 (mod 3)

  Hence,
  a^2 ‚Č° 1^2 ‚Č° 1 (mod 3)
  b^2 ‚Č° 2^2 ‚Č° 4 (mod 3)

  Thus,
  a^2 - b^2 ‚Č° 1 - 4 ‚Č° -3 ‚Č° 0 (mod 3)

- Case 3: a ‚Č° 2, b ‚Č° 1 (mod 3)

  Hence,
  a^2 ‚Č° 2^2 ‚Č° 4 (mod 3)
  b^2 ‚Č° 1^2 ‚Č° 1 (mod 3)

  Thus,
  a^2 - b^2 ‚Č° 4 - 1 ‚Č° 3 ‚Č° 0 (mod 3)

- Case 4: a ‚Č° 2, b ‚Č° 2 (mod 3)

  Hence,
  a^2 ‚Č° 2^2 ‚Č° 4 (mod 3)
  b^2 ‚Č° 2^2 ‚Č° 4 (mod 3)

  Thus,
  a^2 - b^2 ‚Č° 4 - 4 ‚Č° 0 (mod 3)

Hence, 3|(a^2 - b^2).

* 5. Problem 5 [DONE]
** Task
Relation on P(S) where S = {1,2,3,4}
such that for x,y:

x‚Čľy <--> x ‚äÜ y

- Prove that it is a partial order.
- Show whether it is a total order.

** Solution
#+begin_quote
*Proposition.* x‚Čľy <--> x ‚äÜ y, on P(S) where S = {1,2,3,4} is a partial order.

P(S) = {‚ąÖ, {1}, {2}, {3}, {4}, {1,2}, ...}

- *Reflexive:* ‚ąÄa‚ąąA; a‚Čľa.

  Let a ‚ąą P(S).

  Hence, a ‚äÜ a. Since a = a.

  Thus, ‚ąÄa‚ąąP(S); a‚Čľa.

- *Antisymmetric:* ‚ąÄa,b‚ąąA; (a‚Čľb ‚ąß b‚Čľa) --> a=b.

  Let a,b ‚ąą P(S). Assume a‚Čľb and b‚Čľa.

  Hence,
  a ‚äÜ b
  b ‚äÜ a

  Therefore, a = b

  Thus, ‚ąÄa,b‚ąąP(S); (a‚Čľb ‚ąß b‚Čľa) --> a=b.

- *Transitive:* ‚ąÄa,b,c‚ąąA; (a‚Čľb ‚ąß b‚Čľc) --> a‚Čľc.

  Let a,b,c ‚ąą P(S). Assume a‚Čľb and b‚Čľc.

  Hence,
  a ‚äÜ b
  b ‚äÜ c

  Therefore,
  a ‚äÜ b ‚äÜ c
  a ‚äÜ c

  Thus, ‚ąÄa,b,c‚ąąP(S); (a‚Čľb ‚ąß b‚Čľc) --> a‚Čľc.

*Conclusion.* Since ‚Čľ is reflexive, antisymmetric and transitive, it is a partial order.
#+end_quote

#+begin_quote
*Proposition.* x‚Čľy <--> x ‚äÜ y, on P(S) where S = {1,2,3,4} is a total order.

*Proof.*
Since x,y ‚ąą P(S),

{1} = x
{2} = y

Hence, {1} ‚äĄ {2} --> x ‚äĄ y and {2} ‚äĄ {1} --> y ‚äĄ x.

Thus, ‚Čľ is not a total order.
#+end_quote

* 6. Problem 6 [DONE]
** Task
Function properties

- Let `f(x) = (x^2 / 2) - 1`
  a) Prove it is surjective
  b) Check whether it is injective
  c) Determine whether it is bijective

** Solution
#+begin_quote
*Proposition.* f(x) = (x^2 / 2) - 1 is injective.
- injective <--> ‚ąÄb‚ąąB, ‚ąÄa1,a2 ‚ąą A : (f(a1) = b ‚ąß f(a2) = b) --> a1 = a2.

*Proof.*
Assume f(a1) = f(a2). Hence,

((a1)^2 / 2) - 1 = ((a2)^2 / 2) - 1     (add 1 to both sides)
      (a1)^2 / 2 = (a2)^2 / 2           (multiply both sides)
          (a1)^2 = (a2)^2               (take root of both sides)
             ¬Īa1 = ¬Īa2

Let a1 = 2, a2 = -2.
((2)^2 / 2) - 1 = ((-2)^2 / 2) - 1
    (4 / 2) - 1 = (4 / 2) - 1
          2 - 1 = 2 - 1
              1 = 1

while 2 != -2.

Hence, f is not injective.
#+end_quote

#+begin_quote
*Proposition.* f(x) = (x^2 / 2) - 1 is surjective.
- injective <--> ‚ąÄb‚ąąB, ‚ąÄa‚ąąA : f(a) = b.

*Proof.*
- If codomain is ‚ĄĚ, then not surjective, since range is [-1, ‚ąě)
- If codomain is [-1, ‚ąě), then surjective.

#+end_quote

* 7. Problem 7 [DONE]
** Task
Countability

- A = {Pi * g : g ‚ąą ‚Ąö}
- ‚ą™(‚ąě, n = 1)[0, 1/n]
- Decide whether the given set(s) are countable or uncountable.

** Solution
- A = {Pi * g : g ‚ąą ‚Ąö}
  #+begin_quote
  A is countable, since:

  f(x) = Pi * x; x ‚ąą ‚Ąö is bijective.

  *Proposition.* f(x) = Pi * x; x ‚ąą ‚Ąö is bijective.
  - *Surjective.* ‚ąÄb‚ąąB, ‚ąÄa‚ąąA : f(a) = b.
    f : ‚Ąö --> A  f(q) = Pi * q.
    Let a ‚ąą A.
    Thus, by definition of A, ‚ąÉq‚ąą‚Ąö : a = Pi * q.
    Hence, f is into A. f is surjective

  - *Injective.* ‚ąÄb‚ąąB, ‚ąÄa1,a2 ‚ąą A : (f(a1) = b ‚ąß f(a2) = b) --> a1 = a2.
    Let q1,q2 ‚ąą ‚Ąö.
    Assume f(q1) = f(q2). Hence,
    Pi * q1 = Pi * q2   (divide both sides by Pi)
         q1 = q2

    Hence, f is injective.

  Since f is bijective, and ‚Ąö is countable (diagonal proof)
  Set A is countable.
  #+end_quote

- ‚ą™(‚ąě, n = 1)[0, 1/n]

  ‚ą™(‚ąě, n = 1)[0, 1/n] = [0,1]

  [0,1] is uncountable, Cantor's diagonal argument.

* 8. Problem 8 [DONE]
** Task
Set S = {I, J, K, L, M, N, O, P}

How many 8-letter words can be formed such that:
a) Each letter is only used once
b) Letters may be reused as many times as desired
c) M must appear before N in the word

** Solution
 a) 8!, trivial
 b) 8^8
 c) 8! / 2

* 9. Problem 9 [DONE]
** Task
Modular

- 421 ‚Č° ? (mod 21)
- 21321 ‚Č° ? (mod 21)

** Solution
- 421 ‚Č° ? (mod 21)

  421 8
  40  52
   21
   16
    5

  Hence, 421 ‚Č° 5 (mod 21)

- 21321 ‚Č° ? (mod 21)

  21321 21
  21    15
    32
    21
    111
    105
      6

  Hence, 21321 ‚Č° 6 (mod 21)

* 10. Problem 10 [SKIP]
** Task
Solve the equation (algebraic or trigonometric form)

z^3 = -8i

** Solution
z = (-8i)^(1/3)
z = -2 * (i)^(1/3)

* 11. Problem 11 [DONE]
** Task
Solve this

(x^4 + x + 1) / (x - 1)

** Solution
3, trivial
