#+title: General
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-19>
#+lastmod: <2025-11-19 14:24>
#+options: num:t
#+startup: overview

* Do I understand right that the monotone sequences and strictly monotone sequences are generalisation of increasing/decreasing sequences and strictly increasing/strictly decreasing sequences?

** Response
Yes, you're correct. A sequence is monotone if it is either entirely non-increasing or entirely non-decreasing, while a sequence is strictly monotone if it is either strictly increasing or strictly decreasing.

So, increasing and decreasing sequences are specific cases of monotone sequences, and strictly increasing and strictly decreasing sequences are specific cases of strictly monotone sequences.


* Can you give some better definition of Sequence Convergence than the following?
Convergence of a sequence: A sequence (a[n]) converges to a real number "a" if for every positive number e, there is a positive integer N such that for all n greater than or equal to N, the absolute value of (a[n] - a) is less than e. This implies, as n grows arbitrarily large, terms of the sequence get as close as we like to the value "a".

** Response
A sequence {a_n} is said to converge to a limit L as n approaches infinity if, for every positive number epsilon, there exists a positive integer N such that for all terms a_n for n > N, the absolute difference between a_n and L is less than epsilon. Essentially, this means the terms of the sequence get arbitrarily close to L as you go further along in the sequence.
