#+title: Problem Set 7
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-16>
#+lastmod: <2026-04-13 17:28>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{mathtools}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t tags:nil
#+property: header-args :eval never-export
#+startup: overview latexpreview inlineimages

* Analysis
* How to prove equivalence relations?
1. *Reflexive*
   Let a ∈ A. Show a~a. (one sentence: reason why the relaton includes (a,a) or why the property holds)

   Therefore, ∀a ∈ A, a~a.

2. *Symmetric*
   Let a,b ∈ A, and assume a~b. Show b~a. (one sentence: use definition of algebraic symmetry)

   Therefore, ∀a,b ∈ A, a~b --> b~a.

3. *Transitive*
   LEt a,b,c ∈ A, and assume a~b and b~c. Show a~c. (one sentence: combine assumptions via definition/transitivity property)

   Therefore, ∀a,b,c ∈ A, (a~b ∧ b~a) --> a~c.

4. *Conclude*
   Since three properties hold, ~ is an equivalence relation.

* Problem 1 [DONE]
** Task
Define R on ℤ a mRn <--> 2|(m^2 + n^2) for all m,n ∈ ℤ. Is R an equivalence relation?

** Solution
#+begin_quote
*Proposition.* mRn <--> 2|(m^2 + n^2) for all m,n ∈ ℤ. Prove R an equivalence relation.
        2|(m^2 + n^2) <--> m^2 + n^2 ≡ 0 (mod 2)

*Proof.*
- *Reflexive* ∀a ∈ A; a~a.
  Let a ∈ ℤ.
  a^2 + a^2 ≡ 0 (mod 2)
  2(a^2) ≡ 0 (mod 2)
  which is obviously true.
  Hence, ∀a ∈ ℤ; a~a.

- *Symmetric* ∀a,b ∈ A; a~b --> a~b.
  Let a,b ∈ ℤ.
  Assume aRb, thus,
  a^2 + b^2 ≡ 0 (mod 2) <--> b^2 + a^2 ≡ 0 (mod 2)
  Thus, a~b --> b~a.
  Hence, ∀a,b ∈ ℤ; a~b --> b~a.

- *Transitive* ∀a,b,c ∈ A; (a~b ∧ b~c) --> a~c.
  Let a,b,c ∈ ℤ.
  Assume aRb and bRc, thus,
  a^2 + b^2 ≡ 0 (mod 2)
  b^2 + c^2 ≡ 0 (mod 2)

  Thus,
  a^2 + b^2 + b^2 + c^2 ≡ 0 (mod 2)
  a^2 + 2(b^2) + c^2 ≡ 0 (mod 2)        (since 2|2(b^2), substract 2(b^2) from LHS)
  a^2 + c^2 ≡ 0 (mod 2)

  Hence, ∀a,b ∈ ℤ; (a~b ∧ b~c) --> a~c.

*Conclusion.* Since mRn is reflexive, symmetric and transitive for all m,n ∈ ℤ, R is an equivalence relation.
#+end_quote

* Problem 2 [DONE]
*Problem topic:* Relations - Equivalence.

** Task
Let R be a relation on the real numbers defined by xRy <--> x^2 = y^2. Is R an equivalence relation?

** Solution
#+begin_quote
*Proposition.* xRy <--> x^2 = y^2, x,y ∈ ℝ. Prove R is an equivalence relation.

*Proof.*
- *Reflexive:* ∀a∈A, a~a.
  Let a ∈ ℝ. Thus,
  a^2 = a^2
  trivial.
  Hence, ∀a∈ℝ, a~a.

- *Symmetric:* ∀a,b∈A; a~b --> b~a.
  Let a,b ∈ ℝ, aRb Thus,
  a^2 = b^2 <--> b^2 = a^2
  Hence, ∀a,b∈ℝ; a~b --> b~a.

- *Transitive:* ∀a,b,c∈A; (a~b ∧ b~c) --> a~c.
  Let a,b,c ∈ ℝ, aRb and bRc Thus,
  a^2 = b^2
  b^2 = c^2
  Thus,
  a^2 = b^2 = b^2 = c^2
  a^2 = c^2
  Hence, ∀a,b,c∈ℝ; (a~b ∧ b~c) --> a~c.

*Conclusion.* Since xRy is reflexive, symmetric and transitive for all x,y ∈ ℝ, R is an equivalence relation.
#+end_quote

* Problem 3 [DONE]
*Problem topic:* Relations - Equivalence.
** Task
Define R on ℤ as xRy <--> 4|(x + 3y) for all x,y ∈ ℤ. Is R an equivalence relation?

** Solution
#+begin_quote
*Proposition.* If xRy <--> 4|(x + 3y) for all x,y ∈ ℤ, R an equivalence relation.
- 4|(x + 3y) <--> x + 3y ≡ 0 (mod 4)

*Proof.*
- *Reflexive:* ∀a∈A; a~a.
  Let a ∈ ℤ. Thus
  a + 3a ≡ 0 (mod 4)
  4a ≡ 0 (mod 4)
  trivial
  Hence, ∀a∈ℤ; a~a.

- *Symmetric:* ∀a,b∈A; a~b --> b~a.
  Let a,b ∈ ℤ.
  Assume a~b, thus,
  a + 3b ≡ 0 (mod 4) <--> 3b + a ≡ 0 (mod 4)
  3b + a ≡ 0 (mod 4) (multiply both sides by 3)
  9b + 3a ≡ 0 (mod 4)
  (b + 3a) + 8b ≡ 0 (mod 4)
  (b + 3a) + 4(2b) ≡ 0 (mod 4) (substract 4(2b), since 4|4(2b))
  b + 3a ≡ 0 (mod 4)
  Hence, ∀a,b∈ℤ; a~b --> b~a.

- *Transitive:* ∀a,b,c∈A; (a~b ∧ b~c) --> a~c.
  Let a,b,c ∈ ℤ.
  Assume a~b and b~c, thus,
  a + 3b ≡ 0 (mod 4)
  b + 3c ≡ 0 (mod 4)
  thus,
  a + 3b + b + 3c ≡ 0 (mod 4)
  a + 4b + 3c ≡ 0 (mod 4) (substract 4b, since 4|4b)
  a + 3c ≡ 0 (mod 4)
  Hence, ∀a,b,c∈ℤ; (a~b ∧ b~c) --> a~c.

*Conclusion.* Since xRy is reflexive, symmetric and transitive, R is equivalence for all x,y ∈ ℤ.
#+end_quote

* Problem 4 [DONE]
** Task
Prove or disprove: If R is an equivalence relation on an infinite set S, then R has infinitely many equivalence classes.

** Solution
- Equivalence class :: is a subset of a set where all elements are related to each other by an equivalence relation.

#+begin_quote
*Proposition.* If xRy <--> 2|(x+y), x,y ∈ ℤ, R is an equivalence relation.

*Proof.*
- *Reflexive:* ∀a∈A; a~a.
  Let a ∈ ℤ. Thus,
  a + a ≡ 0 (mod 2)
  2(a) ≡ 0 (mod 2)
  trivial.
  Hence, ∀a∈ℤ; a~a.

- *Symmetric:* ∀a,b∈A; a~b --> b~a.
  Let a,b ∈ ℤ.
  Assume a~b. Thus,
  a + b ≡ 0 (mod 2) <--> b + a ≡ 0 (mod 2)
  trivial.
  Hence, ∀a,b∈ℤ; a~b --> b~a.

- *Transitive:* ∀a,b,c∈A; (a~b ∧ b~c) --> a~c.
  Let a,b,c ∈ ℤ.
  Assume a~b and b~c. Thus,
  a + b ≡ 0 (mod 2)
  b + c ≡ 0 (mod 2)
  Thus,
  a + b + b + c ≡ 0 (mod 2)
  a + 2b + c ≡ 0 (mod 2)        (substract 2b, since 2|2b)
  a + c ≡ 0 (mod 2)
  Hence, ∀a,b,c∈ℤ; (a~b ∧ b~c) --> a~c.

*Conclusion.* Since R is reflexive, symmetric and transitive, it is an equivalence relation for all x,y ∈ ℤ.
#+end_quote

Thus, since xRy <--> 2|(x+y), x,y ∈ ℤ, R is an equivalence relation, and has only 2 equivalence classes:

{a ∈ ℤ : a ≡ 1 (mod 2)}
{a ∈ ℤ : a ≡ 0 (mod 2)}

This disproves initial statement.

* Problem 5 [SKIP]
** Task
There are five different equivalence relations on the set A = {a,b,c}. Describe them all. (Here you can just draw a picture instead of text if you prefer.)

** Solution
* Problem 6 [SKIP]
** Task
Let S be the set of all triangles in the plane. Define T1 ~ T2 if T1 is similar to T2. Prove that ~ is an equivalence relation.

** Solution
* Problem 7 [SKIP]
** Task
Consider the partition P = {{0}, {-1,1}, {-2,2}, {-3,3}, ...} of Z. Describe the equivalence relation whose equivalence classes are the elements of P.

** Solution
* Problem 8 [SKIP]
** Task
A relation R on ℝ is defined as xRy, <--> |x| <= |y|. Is this a total order?

** Solution
* Problem 9 [SKIP]
** Task
In a basketball tournament, each team plays every other team exactly once. Define a relation ≼ on the set of all teams as: for two teams A and B, we say A ≼ B <--> the final ranking of B is at least as high as that of A. Is ≼ a partial order? Is it a total order?

** Solution
* Problem 10 [DONE] [PROVED ON BOARD]
** Task
A relation ≼ on ℝ^2 is defined as
        (x1, y1) ≼ (x2, y2) <--> |x2 - x1| <= y2 - y1.

Prove that ≼ is a partial order. Is it a total order?

** Solution
* Problem 11 []
** Task
For the problems above, where there is a partial order, decide which elements are:
- greatest/least
- maximal/minimal

** Solution
*Greatest element:* an element g ∈ S, such that for every x ∈ S, x ≼ g.
Unique element

*Least element:* an element l ∈ S, such that for every x ∈ S, l ≼ x.
Unique element

*Maximal element:* an element m ∈ S, is maximal iff there is no x ∈ S, (m ≼ x) ∧ (x != m).
Multiple elements possible

*Minimal element:* an element n ∈ S, is minimal iff there is no x ∈ S, (x ≼ m) ∧ (x != m).
Multiple elements possible

Therefore,

* Problem 12 []
** Task
** Solution
* Problem 13 []
** Task
Let A given by A = {m/n : m, n ∈ N, m < n}  be a subset of R with the standard order ≤. Find sup A, inf A, max A and min A (if they exist).

** Solution
