#+title: Problem Set 2
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-10-06>
#+lastmod: <2026-04-13 17:28>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{mathtools}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t tags:nil
#+property: header-args :eval never-export
#+startup: overview latexpreview inlineimages

* Problem 1 [DONE]
*** Task
Prove
1. (A \ B) \ C = (A \ C) \ (B \ C)
2. вИ©(x вИИ R)[3 - x^2, 5 + x^2] = [3, 5]

*** Solutions
**** (A \ B) \ C = (A \ C) \ (B \ C)
- x вИИ (A \ B) \ C
  <=> (x вИИ A) вИІ (x вИЙ B) вИІ (x вИЙ C)

- x вИИ (A \ B) \ (B \ C)
  <=> (x вИИ A) вИІ (x вИЙ C) вИІ (x вИЙ (B \ C))

  - x вИЙ (B \ C)
    <=> ¬ђ(x вИИ B вИІ x вИЙ C)
    <=> x вИЙ B v x вИИ C

    since x вИЙ C, x вИЙ B

  therefore
  x вИИ (A \ B) \ (B \ C)  <=>  (x вИИ A) вИІ (x вИЙ B) вИІ (x вИЙ C)

**** вИ©(x вИИ R)[3 - x^2, 5 + x^2] = [3, 5]
- вИ©(x вИИ R)[3 - x^2, 5 + x^2] = [3, 5]

  this means that [3, 5] вКЖ вИ©(x вИИ R)[3 - x^2, 5 + x^2]

  take y вИИ [3, 5]

  вИА x вИИ R, x^2 >= 0

  thus

  3 - x^2 <= 3 <= y <= 5 <= 5 + x^2

  thus

  вИА x вИИ R, y вИИ [3 - x^2, 5 + x^2],

* Problem 2 [DONE]
*** Task
Construct the truth table for:
1. (P вИ® ¬ђQ) => (P вИІ Q)
2. (P => Q) => (Q => P)

*** Solution
**** (P вИ® ¬ђQ) => (P вИІ Q)
|-----+-----+------+------------+-----------+-----------------------|
| *P* | *Q* | *¬ђQ* | *(P вИ® ¬ђQ)* | *(P вИІ Q)* | *(P вИ® ¬ђQ) => (P вИІ Q)* |
|-----+-----+------+------------+-----------+-----------------------|
| T   | T   | F    | T          | T         | T                     |
| T   | F   | T    | T          | F         | F                     |
| F   | T   | F    | F          | F         | T                     |
| F   | F   | T    | T          | F         | F                     |
|-----+-----+------+------------+-----------+-----------------------|
**** (P => Q) => (Q => P)
|-----+-----+------------+------------+------------------------|
| *P* | *Q* | *(P => Q)* | *(Q => P)* | *(P => Q) => (Q => P)* |
|-----+-----+------------+------------+------------------------|
| T   | T   | T          | T          | T                      |
| T   | F   | F          | T          | T                      |
| F   | T   | T          | F          | F                      |
| F   | F   | T          | T          | T                      |
|-----+-----+------------+------------+------------------------|

* Problem 3 [DONE]
*** Task
For each of these sentences, determine whether an inclusive вАЬorвАЭ, or an exclusive вАЬorвАЭ, is
intended.
1. Experience with C++ or Java is required.
2. Lunch includes soup or salad.
3. Publish or perish.
4. To enter the country you need a passport or a permanent residence permit.

*** Solution
1. *Inclusive*, since the ability to work with two languages would logically be more prefered.
2. *Exclusive*, since the lunch would most like offer either soup or salad.
3. *Exclusive*, since perish is not prefered after publishing and publishing is impossible after perishing.
4. *Inclusive*, since its just logical.

* Problem 4 [DONE]
*** Task
Let P,Q, and R be the propositions
вАҐ P: You have the flu.
вАҐ Q: You miss the final examination.
вАҐ R: You pass the course.

Express each of these propositions as an English sentence.
1. P => Q
2. ¬ђQ <=> R
3. Q => ¬ђR
4. (P => ¬ђR) вИ® (Q => ¬ђR)

*** Solution
1. "If =you have a flu=, then =you miss the final exam=."
2. "=You not miss the final examination= if and only if =you pass the course=."
   or
   "=You pass the course= if and only if =you not miss the final examination=."
3. "If =you miss the final examination=, then =you not pass the course=."
4. "If =you have a flu= or =you miss the final examination=, then =you not pass the course=."

* Problem 5 [DONE]
*** Task
Five friends have access to a chat room. Is it possible to determine who is chatting if the following information is known?

- Either Kevin or Heather, or both, are chatting.
- Either Randy or Vijay, but not both, are chatting.
- If Abby is chatting, so is Randy.
- Vijay and Kevin are either both chatting or neither is.
- If Heather is chatting, then so are Abby and Kevin.

Explain your reasoning.

*** Solution
- Names: Kevin, Heather, Randy, Vijay, Abbey

#+begin_src julia :session none :results value
# s - statement
s1(K,H) = K || H
s2(R,V) = xor(R,V)
s3(A,R) = !A || R
s4(K,V) = K == V
s5(H,A,K) = !H || (A && K)

function validation(chat_list::Vector{Bool})
    K = chat_list[1]
    H = chat_list[2]
    R = chat_list[3]
    V = chat_list[4]
    A = chat_list[5]

    if s1(K, H) && s2(R, V) && s3(A, R) && s4(K, V) && s5(H, A, K)
        return true
    end

    return false
end

function get_chats()
    n = 5
    result = Vector{Vector{Bool}}()

    for mask in 0:(1 << n) - 1
        combination = Vector{Bool}()

        for j in 1:n
            if ((mask >> (j - 1)) & 1) == 1
                push!(combination, true)
            else
                push!(combination, false)
            end
        end
        if validation(combination)
            push!(result, combination)
        end
    end
    return result
end

get_chats()

#+end_src

#+RESULTS:
: Bool[1, 0, 0, 1, 0]

* Problem 6 [DONE]
*** Task
A proposition that is always true is called a tautology. Prove (without using a truth table) that (P вИІ Q) => (P вИ® Q) is a tautology.

*** Solution
- A => B = ¬ђA v B (Material Implication)

(P вИІ Q) => (P вИ® Q) = ¬ђ(P вИІ Q) v (P v Q)
= ¬ђP v ¬ђQ v P v Q
= (¬ђP v P) v (¬ђQ v Q)
= T v T
= T

* Problem 7 [DONE]
*** Task
Express each of these statements using quantifiers. Then form the negation of the statement
and simplify it. Next, express the negation in simple English.

1. All dogs have fleas.
2. There is a horse that can add.
3. Every koala can climb.
4. No monkey can speak French.
5. There exists a pig that can swim and catch fish.

*** Solution
**** вИАx(Dogs(x) => Fleas(x))
- Negation: ¬ђ(вИА x (Dogs(x) => Fleas(x)))
  ¬ђ(вИА x (Dogs(x) => Fleas(x)))
  <=> вИГx¬ђ(Dogs(x) => Fleas(x)))
  <=> вИГx(Dogs(x) вИІ ¬ђFleas(x)))
- English: There exists a Dog that does not have Fleas.

**** вИГx(Horse(x) вИІ Add(x))
- Negation: ¬ђ(вИГx(Horse(x) вИІ Add(x)))
  ¬ђ(вИГx(Horse(x) вИІ Add(x)))
  <=> вИАx¬ђ(Horse(x) вИІ Add(x)))
  <=> вИАx(Horse(x) => ¬ђAdd(x)))
- English: Every horses can not add.

**** вИАx(Coala(x) => Climb(x))
- Negation: ¬ђ(вИАx(Coala(x) => Climb(x)))
  ¬ђ(вИАx(Coala(x) => Climb(x)))
  <=> вИГx¬ђ(Coala(x) => Climb(x))
  <=> вИГx(Coala(x) вИІ ¬ђClimb(x))
- English: There exists Coala that can not climb.

**** вИАx(Monkey(x) => ¬ђSpeakFrench(x))
- Negation: ¬ђ(вИАx(Monkey(x) => ¬ђSpeakFrench(x)))
  ¬ђ(вИАx(Monkey(x) => ¬ђSpeakFrench(x)))
  <=> вИГx¬ђ(Monkey(x) => ¬ђSpeakFrench(x))
  <=> вИГx(Monkey(x) вИІ SpeakFrench(x))
- English: There exists a Monkey that can speak French.

**** вИГx(Pig(x) вИІ Swim(x) вИІ CatchFish(x))
- Negation: ¬ђ(вИГx(Pig(x) вИІ Swim(x) вИІ CatchFish(x)))
  ¬ђ(вИГx(Pig(x) вИІ Swim(x) вИІ CatchFish(x)))
  <=> вИАx¬ђ(Pig(x) вИІ Swim(x) вИІ CatchFish(x))
  <=> вИАx(Pig(x) => ¬ђ(Swim(x) вИІ CatchFish(x)))
  <=> вИАx(Pig(x) => (¬ђSwim(x) v ¬ђCatchFish(x)))
- English: No Pig both swims and catches fish.

* Problem 8 [DONE]
*** Task
1. Show that вИАx P(x) вИ® вИАx Q(x) and вИАx (P(x) вИ® Q(x)) are not logically equivalent.
2. Show that вИГx P(x) вИ® вИГx Q(x) and вИГx (P(x) вИ® Q(x)) are logically equivalent.

*** Solution
**** 1.
***** Let the domain be D = {a, b}
- P(a) = true, P(b) = false
- Q(a) = false, Q(b) = true

Check:
- For a: P(a) вИ® Q(a) = true
- For b: P(b) вИ® Q(b) = true
Thus, P(x) вИ® Q(x) is true in this model

But, for вИАxP(x) is false because P(b) is false, and вИАxQ(x) is false since P(a) is false.
Hence, вИАx P(x) вИ® вИАx Q(x) is false.

***** вИГx ѕХ(x) вЙ° ¬ђвИАx ¬ђѕХ

- вИАx (P(x) вИ® Q(x)) = ¬ђвИГx ¬ђ(P(x) вИ® Q(x))
                   = ¬ђвИГx (¬ђP(x) вИІ ¬ђQ(x))

- вИАx P(x) вИ® вИАx Q(x) = ¬ђвИГx ¬ђp(x) v ¬ђвИГx ¬ђq(x)
                    = ¬ђ(вИГx ¬ђp(x) вИІ вИГx ¬ђq(x))

- вИАx(P вИ® Q) вЙ° ¬ђвИГx(¬ђP вИІ ¬ђQ),
- вИАxP вИ® вИАxQ вЙ° ¬ђ(вИГx¬ђP вИІ вИГx¬ђQ).

**** 2.
вИГx P(x) вИ® вИГx Q(x) and вИГx (P(x) вИ® Q(x))

вИГx(P(x) вИ® Q(x)) = ¬ђвИАx ¬ђ(P(x) вИ® Q(x))
                = ¬ђвИАx (¬ђP(x) вИІ ¬ђQ(x))
                = ¬ђ(вИАx¬ђP(x) вИІ вИАx¬ђQ(x))
                = ¬ђвИАx¬ђP(x) v ¬ђвИАx¬ђQ(x)
                = вИГxP(x) вИ® вИГxQ(x)

* Problem 9 [DONE]
*** Task
Construct a truth table for the proposition P вИ® Q вИІ (P => R) => (P => ((Q вИІ P) вИ® R)). You donвАЩt need to do it manually and can use Julia library TruthTables1.

*** Solution
#+begin_src julia :session none :results output
using TruthTables
@truthtable P || Q && (P --> R) --> (P --> ((Q && P) || R))
#+end_src

#+RESULTS:
#+begin_example
TruthTable
вФМвФАвФАвФАвФАвФАвФАвФАвФђвФАвФАвФАвФАвФАвФАвФАвФђвФАвФАвФАвФАвФАвФАвФАвФђвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФР
вФВ   P   вФВ   Q   вФВ   R   вФВ P вИ® Q вИІ (P --> R) --> (P --> Q вИІ P вИ® R) вФВ
вФЬвФАвФАвФАвФАвФАвФАвФАвФЉвФАвФАвФАвФАвФАвФАвФАвФЉвФАвФАвФАвФАвФАвФАвФАвФЉвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФ§
вФВ true  вФВ true  вФВ true  вФВ true                                    вФВ
вФВ true  вФВ true  вФВ false вФВ true                                    вФВ
вФВ true  вФВ false вФВ true  вФВ true                                    вФВ
вФВ true  вФВ false вФВ false вФВ false                                   вФВ
вФВ false вФВ true  вФВ true  вФВ true                                    вФВ
вФВ false вФВ true  вФВ false вФВ true                                    вФВ
вФВ false вФВ false вФВ true  вФВ true                                    вФВ
вФВ false вФВ false вФВ false вФВ true                                    вФВ
вФФвФАвФАвФАвФАвФАвФАвФАвФівФАвФАвФАвФАвФАвФАвФАвФівФАвФАвФАвФАвФАвФАвФАвФівФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФАвФШ
#+end_example
