#+title: Problem Set 6
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-15>
#+lastmod: <2025-11-15 15:30>
#+options: num:t
#+startup: overview

* Problem 1 [DONE]
** Task
In a school, every boy knows 32 girls, and every girl knows 29 boys. Who are there more of in the school: boys or girls, and by how many times?

** Solution
Let B be the total number of boys, and G total number of girls.

Hence,
- Each boy knows 32 girls: total aquaintances = 32B
- Each girl knows 29 boys: total aquaintances = 29G

Thus,
32B = 29G
G/B = 32/29

Therefore, there are 10% (32/29 = 1.103...) more girls than boys.

* Problem 2 []
** Task
How many 10-digit numbers are there in which there are at least two identical digits?

** Solution
* Problem 3 []
** Task
How many permutations of the letters ABCDEFGH contain the string 'ABC'?

** Solution
* Problem 4 []
** Task
Are there more seven-digits numbers that contain the digit 1, or more that don't?

** Solution
* Problem 5 []
** Task
Give a proof of the Binomial Theorem by induction on n.

** Solution
* Problem 6 []
** Task
Find the coefficient of x^4 in (2x^3 - 1/x^2)^8

** Solution
* Problem 7 []
** Task
Let p be prime and 1 <= k <= p. Prove that p|(p k).

** Solution
* Problem 8 []
** Task
Prove if n and m are integers with 1 <= m <= n, then m * nCm = n * (n-1)C(m-1). (Try to provide a combinatorial proof as well as an algebraic one.)

** Solution
* Problem 9 []
** Task
How many permutations of the 26 letters of the English alphabet do not contain any of the strings 'math', 'love', 'quiz'?

** Solution
* Problem 10 []
** Task
How many 6 digits numbers have strictly decreasing digits from left to right?
For example 987654.

** Solution
* Problem 11 []
** Task
Let m, n ∈ N. How many solutions does the equation
        x1 + x2 + ... xm = n
have if
1. all xi are nonegative integer numbers.
2. all xi are natural numbers?

/Hint. If you are not confident in your solution, try verifying particular cases for small values of m and n./

** Solution
