#+title: Problem Set 5
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-14>
#+lastmod: <2025-11-14 19:36>
#+options: num:t
#+startup: overview

* Problem 1 [SKIP]
** Task
Find gcd(11...1, 11...1)
            n       m

** Solution
* Problem 2 []
** Task
Find all n ∈ N for which the fraction (n^2 - n + 1)/(n^2 + 1) is irreduciable.

** Solution
* Problem 3 []
** Task
Prove that if n is an odd integer, then n^2 ≡ 1 (mod 8).

** Solution
*CLaim.* If n is odd, n ∈ N, then n^2 ≡ 1 (mod 8).

*Proof.* Let n = 2k + 1, for k ∈ N, k >= 0.
         Then, (2k + 1)^2 = 4k^2 + 4k + 1
         4k^2 + 4k + 1 = 4(k^2 + k) + 1

         But 2|(k^2 + k), as
         (k^2 + k) = k(k + 1) (a product of 2 consequitive integers)
         k(k + 1) = 2m, m ∈ Z.

         Therefore,
         n^2 = 4 * 2m + 1
         n^2 = 8m + 1 ≡ 1 (mod 8).

         Thus every odd n satisfies n^2 ≡ 1 (mod 8).

* Problem 4 []
** Task
Find the remainder from the division of 2^2025 by 11.

** Solution
* Problem 5 []
** Task
Solve the equation x^2 - 16y = 3, where x, y ∈ Z.

** Solution
* Problem 6 []
** Task
Prove that a number whose decimal representation contains three 1 and several 0 can not be a perfect square.

** Solution
* Problem 7 []
** Task
Find all p ∈ N such that p, p + 10, and p + 14 are prime numbers.

** Solution
* Problem 8 []
** Task
It is October today. What are the chances that, in 250 months’ time, people will be swimming in the Danube?

** Solution
* Problem 9 [SKIP]
** Task
Prove that there exists an n ∈ N for which 11 | (2^n − 1).

** Solution
* Problem 10 [SKIP]
** Task
Prove that there exists a power of 3 that ends with the digits 001. (In other words, 3n = ...001 for some n ∈ N.)

** Solution
* Problem 11 [SKIP]
** Task
A natural number is called perfect if it is equal to the sum of all its divisors. For example, 28 is perfect, because 28 = 1 + 2 + 4 + 7 + 14. Find all perfect numbers under 10000.

** Solution
