#+title: Problem Set 7
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-16>
#+lastmod: <2025-11-16 13:18>
#+options: num:t
#+startup: overview

* Analysis
* How to prove equivalence relations?
1. *Reflexive*
   Let a Рѕѕ A. Show a~a. (one sentence: reason why the relaton includes (a,a) or why the property holds)

   Therefore, Рѕђa Рѕѕ A, a~a.

2. *Symmetric*
   Let a,b Рѕѕ A, and assume a~b. Show b~a. (one sentence: use definition of algebraic symmetry)

   Therefore, Рѕђa,b Рѕѕ A, a~b --> b~a.

3. *Transitive*
   LEt a,b,c Рѕѕ A, and assume a~b and b~c. Show a~c. (one sentence: combine assumptions via definition/transitivity property)

   Therefore, Рѕђa,b,c Рѕѕ A, (a~b РѕД b~a) --> a~c.

4. *Conclude*
   Since three properties hold, ~ is an equivalence relation.

* Problem 1 [DONE]
** Task
Define R on Рёц a mRn <--> 2|(m^2 + n^2) for all m,n Рѕѕ Рёц. Is R an equivalence relation?

** Solution
#+begin_quote
*Proposition.* mRn <--> 2|(m^2 + n^2) for all m,n Рѕѕ Рёц. Prove R an equivalence relation.
        2|(m^2 + n^2) <--> m^2 + n^2 РЅА 0 (mod 2)

*Proof.*
- *Reflexive* Рѕђa Рѕѕ A; a~a.
  Let a Рѕѕ Рёц.
  a^2 + a^2 РЅА 0 (mod 2)
  2(a^2) РЅА 0 (mod 2)
  which is obviously true.
  Hence, Рѕђa Рѕѕ Рёц; a~a.

- *Symmetric* Рѕђa,b Рѕѕ A; a~b --> a~b.
  Let a,b Рѕѕ Рёц.
  Assume aRb, thus,
  a^2 + b^2 РЅА 0 (mod 2) <--> b^2 + a^2 РЅА 0 (mod 2)
  Thus, a~b --> b~a.
  Hence, Рѕђa,b Рѕѕ Рёц; a~b --> b~a.

- *Transitive* Рѕђa,b,c Рѕѕ A; (a~b РѕД b~c) --> a~c.
  Let a,b,c Рѕѕ Рёц.
  Assume aRb and bRc, thus,
  a^2 + b^2 РЅА 0 (mod 2)
  b^2 + c^2 РЅА 0 (mod 2)

  Thus,
  a^2 + b^2 + b^2 + c^2 РЅА 0 (mod 2)
  a^2 + 2(b^2) + c^2 РЅА 0 (mod 2)        (since 2|2(b^2), substract 2(b^2) from LHS)
  a^2 + c^2 РЅА 0 (mod 2)

  Hence, Рѕђa,b Рѕѕ Рёц; (a~b РѕД b~c) --> a~c.

*Conclusion.* Since mRn is reflexive, symmetric and transitive for all m,n Рѕѕ Рёц, R is an equivalence relation.
#+end_quote

* Problem 2 [DONE]
*Problem topic:* Relations - Equivalence.

** Task
Let R be a relation on the real numbers defined by xRy <--> x^2 = y^2. Is R an equivalence relation?

** Solution
#+begin_quote
*Proposition.* xRy <--> x^2 = y^2, x,y Рѕѕ РёЮ. Prove R is an equivalence relation.

*Proof.*
- *Reflexive:* РѕђaРѕѕA, a~a.
  Let a Рѕѕ РёЮ. Thus,
  a^2 = a^2
  trivial.
  Hence, РѕђaРѕѕРёЮ, a~a.

- *Symmetric:* Рѕђa,bРѕѕA; a~b --> b~a.
  Let a,b Рѕѕ РёЮ, aRb Thus,
  a^2 = b^2 <--> b^2 = a^2
  Hence, Рѕђa,bРѕѕРёЮ; a~b --> b~a.

- *Transitive:* Рѕђa,b,cРѕѕA; (a~b РѕД b~c) --> a~c.
  Let a,b,c Рѕѕ РёЮ, aRb and bRc Thus,
  a^2 = b^2
  b^2 = c^2
  Thus,
  a^2 = b^2 = b^2 = c^2
  a^2 = c^2
  Hence, Рѕђa,b,cРѕѕРёЮ; (a~b РѕД b~c) --> a~c.

*Conclusion.* Since xRy is reflexive, symmetric and transitive for all x,y Рѕѕ РёЮ, R is an equivalence relation.
#+end_quote

* Problem 3 [DONE]
*Problem topic:* Relations - Equivalence.
** Task
Define R on Рёц as xRy <--> 4|(x + 3y) for all x,y Рѕѕ Рёц. Is R an equivalence relation?

** Solution
#+begin_quote
*Proposition.* If xRy <--> 4|(x + 3y) for all x,y Рѕѕ Рёц, R an equivalence relation.
- 4|(x + 3y) <--> x + 3y РЅА 0 (mod 4)

*Proof.*
- *Reflexive:* РѕђaРѕѕA; a~a.
  Let a Рѕѕ Рёц. Thus
  a + 3a РЅА 0 (mod 4)
  4a РЅА 0 (mod 4)
  trivial
  Hence, РѕђaРѕѕРёц; a~a.

- *Symmetric:* Рѕђa,bРѕѕA; a~b --> b~a.
  Let a,b Рѕѕ Рёц.
  Assume a~b, thus,
  a + 3b РЅА 0 (mod 4) <--> 3b + a РЅА 0 (mod 4)
  3b + a РЅА 0 (mod 4) (multiply both sides by 3)
  9b + 3a РЅА 0 (mod 4)
  (b + 3a) + 8b РЅА 0 (mod 4)
  (b + 3a) + 4(2b) РЅА 0 (mod 4) (substract 4(2b), since 4|4(2b))
  b + 3a РЅА 0 (mod 4)
  Hence, Рѕђa,bРѕѕРёц; a~b --> b~a.

- *Transitive:* Рѕђa,b,cРѕѕA; (a~b РѕД b~c) --> a~c.
  Let a,b,c Рѕѕ Рёц.
  Assume a~b and b~c, thus,
  a + 3b РЅА 0 (mod 4)
  b + 3c РЅА 0 (mod 4)
  thus,
  a + 3b + b + 3c РЅА 0 (mod 4)
  a + 4b + 3c РЅА 0 (mod 4) (substract 4b, since 4|4b)
  a + 3c РЅА 0 (mod 4)
  Hence, Рѕђa,b,cРѕѕРёц; (a~b РѕД b~c) --> a~c.

*Conclusion.* Since xRy is reflexive, symmetric and transitive, R is equivalence for all x,y Рѕѕ Рёц.
#+end_quote

* Problem 4 []
** Task
Prove or disprove: If R is an equivalence relation on an infinite set S, then R has infinitely many equivalence classes.

** Solution
* Problem 5 []
** Task
There are five different equivalence relations on the set A = {a,b,c}. Describe them all. (Here you can just draw a picture instead of text if you prefer.)

** Solution
* Problem 6 []
** Task
Let S be the set of all triangles in the plane. Define T1 ~ T2 if T1 is similar to T2. Prove that ~ is an equivalence relation.

** Solution
* Problem 7 []
** Task
Consider the partition P = {{0}, {-1,1}, {-2,2}, {-3,3}, ...} of Z. Describe the equivalence relation whose equivalence classes are the elements of P.

** Solution
* Problem 8 []
** Task
A relation R on РёЮ is defined as xRy, <--> |x| <= |y|. Is this a total order?

** Solution
* Problem 9 []
** Task
In a basketball tournament, each team plays every other team exactly once. Define a relation РЅ╝ on the set of all teams as: for two teams A and B, we say A РЅ╝ B <--> the final ranking of B is at least as high as that of A. Is РЅ╝ a partial order? Is it a total order?

** Solution
* Problem 10 []
** Task
A relation РЅ╝ on R^2 is defined as
        (x1, y1) РЅ╝ (x2, y2) <--> |x2 - x1| <= y2 - y1.

Prove that РЅ╝ is a partial order. Is it a total order?

** Solution
* Problem 11 []
** Task
For the problems above, where there is a partial order, decide which elements are:
- greatest/least
- maximal/minimal

** Solution
*Greatest element:* an element g Рѕѕ S, such that for every x Рѕѕ S, x РЅ╝ g.
Unique element

*Least element:* an element l Рѕѕ S, such that for every x Рѕѕ S, l РЅ╝ x.
Unique element

*Maximal element:* an element m Рѕѕ S, is maximal iff there is no x Рѕѕ S, (m РЅ╝ x) РѕД (x != m).
Multiple elements possible

*Minimal element:* an element n Рѕѕ S, is minimal iff there is no x Рѕѕ S, (x РЅ╝ m) РѕД (x != m).
Multiple elements possible

Therefore,

* Problem 12 []
** Task
** Solution
* Problem 13 []
** Task
Let A given by A = {m/n : m, n Рѕѕ N, m < n}  be a subset of R with the standard order РЅц. Find sup A, inf A, max A and min A (if they exist).

** Solution
