#+title: Problem Set 3
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-13>
#+lastmod: <2025-11-14 13:08>
#+options: num:t
#+startup: overview

* Analysis

- I need revisit problem 3, feels a bit strange, specifically the part of "Sn implies Sn+1".
- The weak induction is done very very smoothly.
- Revisit Problem 6,7,8

* Weak Induction Structure
#+begin_quote
*Proposition.* S1, S2, S3 .., are all true.

*Base case.* Demonstrate that S1 is true.

*Inductive hypothesis.* Assume that Sk is true.

*Inductive step.* Prove that Sk implies Sk+1.

*Conclusion.* Therefore, by induction, all the Sn are true.
#+end_quote

#+begin_quote
*Proposition.*

*Base case.*

*Inductive hypothesis.*

*Inductive step.*

*Conclusion.*
#+end_quote

* Strong Induction Structure
#+begin_quote
*Proposition.* S1, S2, S3 .., are all true.

*Base case.* Demonstrate that S1 (or more S) is true.

*Inductive hypothesis.* Assume that S1, S2, S3, ..., Sk are true.

*Inductive step.* Prove that (S1, S2, S3, ..., Sk) implies Sk+1.

*Conclusion.* Therefore, by induction, all the Sn are true.
#+end_quote

#+begin_quote
*Proposition.*

*Base case.*

*Inductive hypothesis.*

*Inductive step.*

*Conclusion.*
#+end_quote

* Problem 1 [DONE]
** Task
Prove that 3|(n^3 - n) for all n ∈ ℕ

** Solution
#+begin_quote proof by induction
*Proposition.* 3|(n^3 - n) for all n ∈ ℕ.

*Base case.* Let n = 1. 1^3 - 1 = 0, hence 3|0. Base holds.

*Inductive hypothesis.* Assume 3|(a^3 - a) <--> (a^3 - a) ≡ 0 (mod 3) is true for some a ∈ ℕ.

*Induction step.* Let a ∈ ℕ.

(a^3 - a) ≡ 0 (mod 3)   (add 3(a^2 + a) to the left side, since multiple of 3)
 a^3 - a + 3(a^2 + a) ≡ 0 (mod 3)
 a^3 - a + (3a^2 + 3a) ≡ 0 (mod 3)
 a^3 + 3a^2 + 3a + 1 - a - 1 ≡ 0 (mod 3)
(a+1)^3 - (a+1) ≡ 0 (mod 3)

Therefore, 3|(a^3 - a) implies 3|((a+1)^3 - (a+1)) for some a ∈ ℕ.

*Conclusion.* Therefore, by induction, 3|(n^3 - n) for all n ∈ ℕ.
#+end_quote

* Problem 2 [DONE]
** Task
Prove that 2^n < n! for all n >= 4.

** Solution
#+begin_quote
*Proposition.* 2^n < n! for all n >= 4.

*Base case.* Let n = 4. 2^4 = 16, 4! = 24; 16 < 24. Base holds.

*Inductive hypothesis.* Assume 2^k < k! for all k >= 4.

*Inductive step.* Let k >= 4.

2^k < k!                (multiply both sides by 2)
2^(k+1) < 2 * k!

Since k >= 4 --> (k + 1) >= 5 > 2. Hence, replace 2 on RHS with (k+1).
2^(k+1) < (k+1) * k!
2^(k+1) < (k+1)!

Hence, 2^n < k! implies 2^(k+1) < (k+1)! for k >= 4.

*Conclusion.* Therefore, 2^n < n! for all n >= 4.
#+end_quote

* Problem 3 [DONE]
** Task
Prove that sin(nx) <= n * sin(x) for all x ∈ [0, Pi/2] and n ∈ ℕ.

** Solution
#+begin_quote
*Proposition.* sin(nx) <= n * sin(x) for all for all x ∈ [0, Pi/2]  and k ∈ ℕ.

*Base case.* Let n = 1. sin(1*x) <= 1 * sin(x) <--> sin(x) <= sin(x). Base holds.

*Inductive hypothesis.* Assume sin(kx) <= k * sin(x) for all x ∈ ℝ and k ∈ ℕ.

*Inductive step.* Let k ∈ ℕ.

- Trigonometric identities: sin(2x) = 2sin(x)cos(x)
                            sin(A+B) = sin(A)cos(B) + cos(A)sin(B)

sin((k+1)x) <= (k+1) * sin(x)
sin(kx + x) <= (k+1) * sin(x)
sin(kx)cos(x) + cos(kx)sin(x) <= (k+1) * sin(x)

Since x ∈ [0, Pi/2]; cos(x) ∈ [0,1], sin(x) >= 0, cos(kx) <= 1:

sin(kx)cos(x) <= ksin(x)cos(x) <= ksin(x)

and since cos(x) <= 1,

cos(kx)sin(x) <= 1 * sin(x) = sin(x)

Thus,
sin(kx)cos(x) + cos(kx)sin(x) <= sin(x) + ksin(x)
sin(kx)cos(x) + cos(kx)sin(x) <= (k+1) * sin(x)

*Conclusion.* Therefore, sin(nx) <= n * sin(x) for all for all x ∈ [0, Pi/2]  and k ∈ ℕ.
#+end_quote

* Problem 4 [DONE]
** Task
(Bernoulli inequality.) Prove that (1 + x)^n >= 1 + nx for all real x >= -1 and all n ∈ ℕ.

** Solution
#+begin_quote
*Proposition.* (1 + x)^n >= 1 + nx for all real x >= -1 and all n ∈ ℕ.

*Base case.* Let n = 1. (1 + x) >= 1 + x. Base holds.

*Inductive hypothesis.* Assume (1 + x)^k >= 1 + kx for all real x >= -1 and all k ∈ ℕ.

*Inductive step.*

(1 + x)^k >= 1 + kx                     (multiply both sides by (1+x))
(1 + x)^(k+1) >= (1 + kx)(1 + x)
(1 + x)^(k+1) >= 1 + x + kx + kx^2
(1 + x)^(k+1) >= 1 + (k+1)x + kx^2      (since k >= 1 and x^2 >= 0, remove kx^2 from RHS)
(1 + x)^(k+1) >= 1 + (k+1)x

Hence, (1 + x)^k >= 1 + kx implies (1 + x)^(k+1) >= 1 + (k+1)x.

*Conclusion.* Therefore, (1 + x)^n >= 1 + nx for all real x >= -1 and all n ∈ ℕ.
#+end_quote

* Problem 5 [DONE]
** Solution
1/1(1+1) + 1/2(2+1) + 1/3(3+1) + 1/4(4+1) + ... + 1/n(n+1)
1/1 + 1/6 + 1/12 + 1/20 + ... + 1/n(n+1)

n = 1, e = 1
n = 2, e = 1 + 1/6 = 7/6
n = 3, e = 1 + 1/6 + 1/12 = 5/4
n = 4, e = 1 + 1/6 + 1/12 + 1/20 = 13/10

1/k(k+1) = 1/k - 1/k+1

Thus,
1/1 - 1/2 + 1/2 - 1/3 + 1/3 - 1/4 + ... + 1/k - 1/k+1

Hence,
equation = 1 - 1/k+1

* Problem 6 [DONE]
** Task
Let S be a set containing n elements. Use induction to prove that |P(S)| = 2^n.

** Solution
#+begin_quote
*Proposition.* If S is set, and |S| = n. Then |P(S)| = 2^n.

*Base case.* Let |S| = 0. |P(S)| = 1. Base holds.

*Inductive hypothesis.* Assume If |S| = k, then |P(S)| = 2^k.

*Inductive step.* Let S be the set of k+1 elements. Let a ∈ S. Define T := S \ {a}. Thus |T| = k. Now define:

A = {X ⊆ S : a ∉ X}
B = {X ⊆ S : a ∈ X}

f : P(T) --> B  f(X) = X ∪ {a}.

Since f is a bijective function, with assumption, |A| = 2^k, |B| = 2^k.

And since P(S) = A ∪ B --> |P(S)| = |A| + |B|, |P(S)| = 2^k + 2^k = 2^(k+1)

*Conclusion.* Therefore, if |S| = n. Then |P(S)| = 2^n.
#+end_quote

* Problem 7 [DONE]
** Task
The bank has an unlimited supply of 3 and 5 euros bills. Prove that it can dispense any number of euros greater than 8 (without change).

** Solution
*** Solution 1 [mine and wrong]
#+begin_quote
*Proposition.* For any x ∈ ℕ : x > 8, x = 3n + 5m, for n,m ∈ ℕ0.

*Base case.* Let x = 9. x = 3*3 + 5*0; n = 3, m = 0.
             Let x = 10. x = 3*0 + 5*2; n = 3, m = 0.
             Let x = 11. x = 3*2 + 5*1; n = 3, m = 0.
             Bases hold.

*Inductive hypothesis.* For any k ∈ ℕ : k > 8, k = 3n + 5m, for n,m ∈ ℕ0.

*Inductive step.*

Let k be arbitrary, k ∈ ℕ.

Hence, k ≡ 0 (mod 3)
       k ≡ 1 (mod 3)
       k ≡ 2 (mod 3)

- If k ≡ 0 (mod 3)
  k = 3*a + 9, a ∈ ℕ0.
  k = 3*a + 3*3 + 5*0,
  k = 3*(a+3) + 5*0,
  Since a ∈ ℕ0, (a+3) ∈ ℕ. Thus, k = 3n + 5m, for n,m ∈ ℕ0.

- If k ≡ 1 (mod 3)
  k = 3*a + 3*3 + 1, a ∈ ℕ0.
  k = 3*a + 10,
  k = 3*a + 3*0 + 5*2,
  k = 3*(a) + 5*2,
  Since a ∈ ℕ0. Thus, k = 3n + 5m, for n,m ∈ ℕ0.

- If k ≡ 2 (mod 3)
  k = 3*a + 3*3 + 2, a ∈ ℕ0.
  k = 3*a + 11,
  k = 3*a + 3*2 + 5*1,
  k = 3*(a+2) + 5*1,
  Since a ∈ ℕ0, (a+2) ∈ ℕ. Thus, k = 3n + 5m, for n,m ∈ ℕ0.

*Conclusion.* For any x ∈ ℕ : x > 8, x = 3n + 5m, for n,m ∈ ℕ0.
#+end_quote

*** Solution 2
#+begin_quote
*Proposition.* For any x ∈ ℕ : x >= 8, x = 3n + 5m, for n,m ∈ ℕ0.

*Base case.* Let x = 8. x = 3*1 + 5*1; n = 1, m = 1.
             Let x = 9. x = 3*3 + 5*0; n = 3, m = 0.
             Let x = 10. x = 3*0 + 5*2; n = 0, m = 2.
             These represent all congruence classes of modulo 3.
             Bases hold.

*Inductive hypothesis.* Assume for any k ∈ ℕ : k >= 8, k = 3n + 5m, for n,m ∈ ℕ0.

*Inductive step.* Then, k + 3 = 3(n+1) + 5m, which is also a valid representation.

Thus,
- Numbers congruent to 2 mod 3 are generated from 8.
- Numbers congruent to 0 mod 3 are generated from 9.
- Numbers congruent to 1 mod 3 are generated from 10.

*Conclusion.* Therefore, for any x ∈ ℕ : x >= 8, x = 3n + 5m, for n,m ∈ ℕ0.
#+end_quote

* Problem 8 [DONE]
** Task
There is a 16 × 16 chess board with one square removed. Prove that it can be tiled using triminoes (you can rotate them). We have already proved it in class, and now your goal is to express the proof in words.

** Solution
*** Solution 1 [mine and right]
#+begin_quote
*Proposition.* There is a 16 × 16 chess board with one square removed. Prove that it can be tiled using triminoes (you can rotate them).

*Base case.* Consider 2x2 chess board. Choose any of the four squares, the left 3 would perfectly fit a triminos.

*Inductive hypothesis.* Assume any of the chess boards of size 2^n x 2^n, with n ∈ ℕ, can be filled with triminoes, leaving one square unoccupied.

*Inductive step.*

Consider 2^(n+1) x 2^(n+1) chessboard with one square removed at its center (center is 2x2 squares). Now, by splitting this chessboard into 5 parts, vertically and horizontally making 4 parts, and 5th being the center's triminos. This would result in 4 2^n chessboards, with 1 empty square in each, and 1 triminoes.

Each of these 4 parts could be perfectly covered with triminoes by the inductive hypothesis, and hence 2^(n+1) x 2^(n+1) chessboard can be perfeclty covered.

*Conclusion.* By induction, for every n ∈ ℕ, if one square is removed from a 2^n x 2^n chessboard, the result can be perfectly covered with triminoes.
#+end_quote

*** Solution 2 [revised]
#+begin_quote
*Proposition.* There is a 16 × 16 chess board with one square removed. Prove that it can be tiled using triminoes (you can rotate them).

Chessboard follows a resolution of 2^n x 2^n, n ∈ ℕ.

*Base case.* When n = 1, the board is 2 x 2. Removing any square leaves an L-shape, which can be covered by a single L-tromino. Base holds.

*Inductive hypothesis.* Assume that for some k >= 1, any table 2^k x 2^k with one square removed can be covered by L-trominoes.

*Inductive step.* Consider 2^(k+1) x 2^(k+1) board with one square removed.

Cut it vertically and horizontally through the center, forming 2^k x 2^k quadrants. Exactly one quadrant contains the removed square, and by the inductive hypothesis can be filled with L-trominoes.

Now place one L-tromino at the center, so that is covers one central square of other 3 quadrants. This creates exactly one missing square in each quadrant.

By the inductive hypothesis, each 2^k x 2^k quadrants, with exaclty one missing square can be tiled. Togethere with the center tromino, this tiles the whole 2^(k+1) x 2^(k+1) board.

*Conclusion.* By induction, any 2^n x 2^n board with one square removed can be tiled with L-trominoes.
#+end_quote

* Problem 9 [DONE]
** Task
Prove that there exists an n ∈ ℕ for which 11|(2^n − 1).

** Solution
#+begin_quote
*Proposition.* There exists an n ∈ ℕ for which 11|(2^n − 1).
               Or equivalently, 2^n - 1 ≡ 0 (mod 11)

*Proof.* Since 11 is prime, and gcd(2, 11) = 1, the sequence:

        2^1, 2^2, 2^3, ... (mod 11)

must eventually repeat. Because, there are only 10 nonzero remainders modulo 11, the numbers 2^1, 2^2, 2^3, ... must contain a repetition.

        2^1 ≡ 1 (mod 11)
        2^2 ≡ 4 (mod 11)
        2^3 ≡ 8 (mod 11)
        2^4 ≡ 5 (mod 11)
        2^5 ≡ 10 (mod 11)
        2^6 ≡ 9 (mod 11)
        2^7 ≡ 7 (mod 11)
        2^8 ≡ 3 (mod 11)
        2^9 ≡ 6 (mod 11)
        2^10 ≡ 1 (mod 11)

We have found:

        2^10 ≡ 1 (mod 11)

Thus, 2^10 - 1 ≡ 0 (mod 11)

*Conclusion.* For n = 10, 11|(2^n − 1).
#+end_quote
