#+title: Problem Set 6
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-15>
#+lastmod: <2025-11-15 17:16>
#+options: num:t
#+startup: overview

* Problem 1 [DONE]
** Task
In a school, every boy knows 32 girls, and every girl knows 29 boys. Who are there more of in the school: boys or girls, and by how many times?

** Solution
Let B be the total number of boys, and G total number of girls.

Hence,
- Each boy knows 32 girls: total aquaintances = 32B
- Each girl knows 29 boys: total aquaintances = 29G

Thus,
32B = 29G
G/B = 32/29

Therefore, there are 10% (32/29 = 1.103...) more girls than boys.

* Problem 2 [DONE]
** Task
How many 10-digit numbers are there in which there are at least two identical digits?

** Solution
*** Solution 1
10 digit numbers start with:

1000000000

and end with

9999999999

There are total of 10! numbers with no identical digits.
But they also include the numbers that start with 0, which we should ignore.

The total amount of numbers that start with 0 are: 9!.

Hence, the total 10-digit numbers with no identical digits are: 10! - 9!.

But we need to find numbers with at *least two* identical digits. Therefore, we need to count all possible numbers.

All possible numbers are:

9999999999 - 1000000000 + 1 = 9000000000

9000000000 - 10! + 9!

*** Solution revised
There are a total of:

9999999999 - 1000000000 + 1 = 9000000000 = 9 * 10^9

10 digit numbers.

And there are:

9 * 9|

numbers with no digit repetitions.

Therefore, there are a total of:

9 * 10^9 - 9 * 9!

10-digit numbers with at least two digit repetitions.

* Problem 3 [DONE]
** Task
How many permutations of the letters ABCDEFGH contain the string 'ABC'?

** Solution
Consider 'ABC' being one element in the list of strings, like this:

['ABC', 'D', 'E', 'F', 'G', 'H']

Hence, there are a total of 6 elements in a list. Meaning that there are a total of 6! permutations.

* Problem 4 [DONE]
** Task
Are there more seven-digits numbers that contain the digit 1, or more that don't?

** Solution
Number of 7-digit number is:

9999999 - 1000000 + 1 = 9000000 = 9 * 10^6

We shall count the total number of 7-digit numbers, with no digit 1. Therefore, each slot of 7 digit number would have a choice of 9 digits.

Take into account that the first digit can not be 0. Therefore, split it.

Hence,
9^6 - is the number of 6-digit numbers with no 1 digit.

8 * 9! / 3! = 4251528 is the total number of 7-digit numbers with no digit 1. As 1st slot can not be 1 xor 0.

9 * 10^6 - 4251528 = 4748472 number of 7-digits numbers that do contain digit 1.

4748472 > 4251528, therefore, there are more 7-digit numbers that do contain digit 1.

* Problem 5 [SKIP]
** Task
Give a proof of the Binomial Theorem by induction on n.

** Solution
* Problem 6 [DONE]
** Task
Find the coefficient of x^4 in (2x^3 - 1/x^2)^8

** Solution
To find coefficient of x^4:
3n - 2n = 4
n = 4

#+begin_quote
C(n,k) = n! / ((n - k)! * k!)
n - is the number of choices
k - is the length of desired combination
#+end_quote

(2x^3 - 1/x^2)^8 = (2x^3 - x^-2)^8

Hence,
(2x^3 - x^-2)^8 = ... + 8C4 * (2x^3)^4 * (-x^-2)^8 + ...
                = ... + 70 * 16x^12 * x^-8 + ...
                = ... + 1120 * x^4 + ...

* Problem 7 [DONE]
** Task
Let p be prime and 1 <= k <= p. Prove that p|(p k).

** Solution
*** Solution 1
(p k) is basically:

p! / ((p - k)! * k!)

it can be also represented as:

((p) * (p-1) * (p-2) * (p-3) * ... * 2 * 1) / ((p - k)! * k!)
p * ((p-1) * (p-2) * (p-3) * ... * 2 * 1) / ((p - k)! * k!)

Since p is the prime, and (p k) = pCk is an integer, means that we can "extract" p from the fraction:

p * (p-1)!/((p - k)! * k!)

The fraction is still an integer, since we extracted the prime number which is only divisible by itself.

Therefore, p|(p k).
*** Solution revised
pCk is basically

pCk = p! / ((p-k)! * k!)

pCk * ((p-k)! * k!) = p!

pCk * (p-k)! * k! = p * (p-1)!

Therefore, p|(pCk * (p-k)! * k!)

- k! = 1 * 2 * ... * k where k < p
- (p-k)! = 1 * 2 * ... * (p-k), where (p-k) < p
  (remember that p is prime, meaning that it can not be represented as any product)

Therefore, as neither k! and (k-p)! contribute the factor p to the (pCk * (p-k)! * k!), pCk must be a multiple of p.

* Problem 8 [DONE]
** Task
Prove if n and m are integers with 1 <= m <= n, then m * nCm = n * (n-1)C(m-1). (Try to provide a combinatorial proof as well as an algebraic one.)

** Solution
- Algebraic proof

  m * nCm = n * (n-1)C(m-1)

  m * (n!/((n-m)! * m!)) = n * ((n-1)!/(((n-1)-(m-1))! * (m-1)!)
  (n!/((n-m)! * (m-1)!)) = (n!/((n-m)! * (m-1)!)

- Combinatorical proof

  m * nCm is a way to select a group leader from a combination of m people.

  While n * (n-1)C(m-1) is selecting a leader from group of n, and then selecting a combination of group.

  Both count the same thing.

* Problem 9 [MAYBE LATER]
** Task
How many permutations of the 26 letters of the English alphabet do not contain any of the strings 'math', 'love', 'quiz'?

** Solution
* Problem 10 [DONE]
** Task
How many 6 digits numbers have strictly decreasing digits from left to right?
For example 987654.

** Solution
Imagine a list of numbers like this:

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

Hence we need to find the total number of ways to choose 4 numbers from the list. This would give us total amount of "remaining" numbers, forming a number with decreasing digits.

Thus,

10C4 = 10! / ((10-4)! * 4!)
     = 210

* Problem 11 []
** Task
Let m, n ∈ N. How many solutions does the equation
        x1 + x2 + ... xm = n
have if
1. all xi are nonegative integer numbers.
2. all xi are natural numbers?

/Hint. If you are not confident in your solution, try verifying particular cases for small values of m and n./

** Solution
