#+title: Problem Set 7
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-16>
#+lastmod: <2025-11-16 10:47>
#+options: num:t
#+startup: overview

* Problem 1 []
** Task
Define R on Z a mRn <--> 2|(m^2 + n^2) for all m,n ∈ Z. Is R an equivalence relation?

** Solution
* Problem 2 []
*Problem topic:* Relations - Equivalence.

** Task
Let R be a relation on the real numbers defined by xRy <--> x^2 = y^2. Is R an equivalence relation?

** Solution
* Problem 3 []
*Problem topic:* Relations - Equivalence.
** Task
Define R on Z as xRy <--> 4|(x + 3y) for all x,y ∈ Z. Is R an equivalence relation?

** Solution
* Problem 4 []
** Task
Prove or disprove: If R is an equivalence relation on an infinite set S, then R has infinitely many equivalence classes.

** Solution
* Problem 5 []
** Task
There are five different equivalence relations on the set A = {a,b,c}. Describe them all. (Here you can just draw a picture instead of text if you prefer.)

** Solution
* Problem 6 []
** Task
Let S be the set of all triangles in the plane. Define T1 ~ T2 if T1 is similar to T2. Prove that ~ is an equivalence relation.

** Solution
* Problem 7 []
** Task
Consider the partition P = {{0}, {-1,1}, {-2,2}, {-3,3}, ...} of Z. Describe the equivalence relation whose equivalence classes are the elements of P.

** Solution
* Problem 8 []
** Task
A relation R on ℝ is defined as xRy, <--> |x| <= |y|. Is this a total order?

** Solution
* Problem 9 []
** Task
In a basketball tournament, each team plays every other team exactly once. Define a relation ≼ on the set of all teams as: for two teams A and B, we say A ≼ B <--> the final ranking of B is at least as high as that of A. Is ≼ a partial order? Is it a total order?

** Solution
* Problem 10 []
** Task
A relation ≼ on R^2 is defined as
        (x1, y1) ≼ (x2, y2) <--> |x2 - x1| <= y2 - y1.

Prove that ≼ is a partial order. Is it a total order?

** Solution
* Problem 11 []
** Task
For the problems above, where there is a partial order, decide which elements are:
- greatest/least
- maximal/minimal

** Solution
*Greatest element:* an element g ∈ S, such that for every x ∈ S, x ≼ g.
Unique element

*Least element:* an element l ∈ S, such that for every x ∈ S, l ≼ x.
Unique element

*Maximal element:* an element m ∈ S, is maximal iff there is no x ∈ S, (m ≼ x) ∧ (x != m).
Multiple elements possible

*Minimal element:* an element n ∈ S, is minimal iff there is no x ∈ S, (x ≼ m) ∧ (x != m).
Multiple elements possible

Therefore,

* Problem 12 []
** Task
** Solution
* Problem 13 []
** Task
Let A given by A = {m/n : m, n ∈ N, m < n}  be a subset of R with the standard order ≤. Find sup A, inf A, max A and min A (if they exist).

** Solution
