#+title: Problem Set 4
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-14>
#+lastmod: <2025-11-14 15:14>
#+options: num:t
#+startup: overview

* Problem 1 [DONE]
** Task
Let x and y be nonnegative numbers. Prove that if x <= y, then sqrt{x} <= sqrt{y}.

** Solution
#+begin_quote
*Proposition.* x,y >= 0, if x <= y, then sqrt{x} <= sqrt{y}.

*Proof.* Assume x <= y with x,y >= 0.

Square both sides of sqrt{x} <= sqrt{y}:

sqrt{x}^2 = x
sqrt{y}^2 = y

Squaring is allowed since both sides are non-negative.

Thus, from x <= y, we get:

sqrt{x}^2 <= sqrt{y}^2

Since the square function is increasing on [0, ∞), this is equivalent to:

sqrt{x} <= sqrt{y}
#+end_quote

* Problem 2 [DONE]
** Task
For n ∊ ℕ prove that 4|(1 + (-1)^n * (2n - 1)).

** Solution
#+begin_quote
*Proposition.* For n ∈ ℕ, 4|(1 + (-1)^n * (2n - 1)) <--> (1 + (-1)^n * (2n - 1)) ≡ 0 (mod 4).

*Proof.*

(1 + (-1)^n * (2n - 1))

n = 1 : (1 + (-1)^1 * (2*1 - 1)) = (1 - 1(2 - 1)) = 0
n = 2 : (1 + (-1)^2 * (2*2 - 1)) = (1 + 1(4 - 1)) = 4
n = 3 : (1 + (-1)^3 * (2*3 - 1)) = (1 - 1(6 - 1)) = -4
n = 4 : (1 + (-1)^4 * (2*4 - 1)) = (1 + 1(8 - 1)) = 8
n = 5 : (1 + (-1)^5 * (2*5 - 1)) = (1 - 1(10 - 1)) = -8

Let n = 2k for k ∈ ℕ.
        (1 + (-1)^(2k) * (2*2k - 1)) = (1 + 1 * (4k - 1))
                                     = 1 + 4k - 1
                                     = 4k

Let n = 2k + 1 for k ∈ ℕ.
        (1 + (-1)^(2k+1) * (2*(2k+1) - 1)) = (1 - 1 * (4k + 2 - 1))
                                           = 1 - 4k - 1
                                           = -4k

*Conclusion.* In both cases, expression is a multiple of 4 for every n ∈ ℕ.
#+end_quote

* Problem 3 [DONE]
** Task
Prove that log2(3) is irrational.

** Solution
#+begin_quote
*Proposition.* log2(3) != a/b, a ∈ ℤ, b ∈ ℕ. log2(3) is irrational.

*Proof.*
Assume log2(3) is rational.

log2(3) = a/b, a ∈ ℤ, b ∈ ℕ.

Thus,
2^(a/b) = 3
2^a = 3^b

LHS has only one prime number factor 2
RHS has only one prime number factor 3

By the Fundamental Theorem of Arithmetics (unique prime factorisation), the two sides can not be equal unless both are 1.

But 2^p = 1 would force a = 0, which gives 3^b = 1, and then b = 0, which is impossible because of b being natural.
#+end_quote

* Problem 4 [DONE]
** Task
Five children found nine mushrooms. Prove that at least two of them found an equal number of mushrooms.

** Solution
#+begin_quote
*Proposition.* 9 items can not be splitted into 5 groups of different count number.

Let 1st brat have 0 mushrooms, this would force 2nd brat to have 0+1 mushrooms, so it would not be equal to the first brat's mushrooms. Same logic goes for the rest brats.

        1st = 0 mushrooms
        2nd = 1 mushrooms
        3rd = 2 mushrooms
        4th = 3 mushrooms
        5th = 4 mushrooms

Thus, the total amount of mushrooms in this case would be:

        0 + 1 + 2 + 3 + 4 = 10

Thus, it would force us to decrement on of the brat's mushrooms by 1. Which would lead to 2 brats with the same amount of mushrooms.
#+end_quote

* Problem 5 [DONE]
** Task
Calculate
a. 0.1212.. + 0.122122..
b. 0.33.. + 0.44..

** Solution
a. 0.1212.. + 0.122122..

   0.1212.. = 12/99
   0.122122.. = 122/999

   Thus, 0.1212.. + 0.122122.. = 12/99 + 122/999

   12/99 + 122/999 = 111 * 12/99 + 11 * 122/999 = 132/10989 + 1342/10989 = 2674/10989 = 0.24334..

   99 = 3 * 3 * 11
   999 = 3 * 3 * 3 * 37
   Thus, lcm(99, 999) = 10989

b. 0.33.. * 0.44..

   0.33.. = 3/9
   0.44.. = 4/9

   Thus,
   3/9 * 4/9 = 12/81 = 0.148..

* Problem 6 []
** Task
Find digits a and b such that (o.aa..)^(1/2) = 0.bb..

** Solution
* Problem 7 []
** Task

** Solution
* Problem 8 []
** Task
a. gcd(10223; 33341)
b. gcd(2n + 1; 3n + 2)

** Solution
* Problem 9 []
** Task
Convert (110 1001 0101 1011)2 to decimal representation. Without converting, can you know for sure whether this number is greater than 2^15?

** Solution
