#+title: Problem Set 2
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-13>
#+lastmod: <2025-11-13 09:42>
#+options: num:t
#+startup: overview

* Problem 1 []
*** Task
Prove
1. (A \ B) \ C = (A \ C) \ (B \ C)
2. ∩(x ∈ R)[3 - x^2, 5 + x^2] = [3, 5]

* Problem 2 []
*** Task
Construct the truth table for:
1. (P ∨ ¬Q) => (P ∧ Q)
2. (P => Q) => (Q => P)

* Problem 3 []
*** Task
For each of these sentences, determine whether an inclusive “or”, or an exclusive “or”, is
intended.
1. Experience with C++ or Java is required.
2. Lunch includes soup or salad.
3. Publish or perish.
4. To enter the country you need a passport or a permanent residence permit.

* Problem 4 []
*** Task
Let P,Q, and R be the propositions
• P: You have the flu.
• Q: You miss the final examination.
• R: You pass the course.

Express each of these propositions as an English sentence.
1. P => Q
2. ¬Q <=> R
3. Q => ¬R
4. (P => ¬R) ∨ (Q => ¬R)

* Problem 5 []
*** Task
Five friends have access to a chat room. Is it possible to determine who is chatting if the following information is known?

- Either Kevin or Heather, or both, are chatting.
- Either Randy or Vijay, but not both, are chatting.
- If Abby is chatting, so is Randy.
- Vijay and Kevin are either both chatting or neither is.
- If Heather is chatting, then so are Abby and Kevin.

Explain your reasoning.

* Problem 6 []
*** Task
A proposition that is always true is called a tautology. Prove (without using a truth table) that (P ∧ Q) => (P ∨ Q) is a tautology.

* Problem 7 []
*** Task
Express each of these statements using quantifiers. Then form the negation of the statement
and simplify it. Next, express the negation in simple English.

1. All dogs have fleas.
2. There is a horse that can add.
3. Every koala can climb.
4. No monkey can speak French.
5. There exists a pig that can swim and catch fish.

* Problem 8 []
*** Task
1. Show that ∀x P(x) ∨ ∀x Q(x) and ∀x (P(x) ∨ Q(x)) are not logically equivalent.
2. Show that ∃x P(x) ∨ ∃x Q(x) and ∃x (P(x) ∨ Q(x)) are logically equivalent.

* Problem 9 []
*** Task
Construct a truth table for the proposition P ∨ Q ∧ (P => R) => (P => ((Q ∧ P) ∨ R)). You don’t need to do it manually and can use Julia library TruthTables1.

