#+title: Ideas
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-27>
#+lastmod: <2025-12-07 20:57>
#+options: num:t
#+startup: overview

* List of ideas to implement in this repository:
- A massive file with a list of topics and links to the best explanatory resources.

  Example: my favourite resource to learn proof of binomual theorem by induction is the [[https://www.youtube.com/watch?v=l_VgvueBwuA][video of some professor in medival clothes in church explaining it]].

- Another silly idea is to add list of nice places to eat around the main buildings.

  Examples:
  - Ikea store has a free hot drinks for 1 hour everyday, on weekdays its pretty chill study place.
  - [[https://fam.tuwien.ac.at/contact/restaurants.pdf][List of places to eat near TU Wien]]

- List of study places

- WHat would be an absolute banger is to add a directory with all julia tutorials. This will include:
  - Installation of Julia
  - Instructions on how to download packages
  - List of the most important packages (e.g. Plots, Combinatorics and etc)
  - Simple instructions on those packages (important ones)

    What will make this idea outstanding is to inspire this section of my university repo from MIT's little github repo, but make it super applicable to ours bachelor.
