#+title: Ps 02
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-03-16>
#+lastmod: <2026-03-16 12:28>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t
#+startup: overview latexpreview inlineimages

* Problem 1.24 :DONE:
** Task
#+begin_quote
(Reverse Triangle Inequality). From the triangle inequality, derive the /reverse triangle inequality/, namely

$| \|x\| - \|y\| | \leq \|x - y\|$, $\forall (x, y) \in \mathbb{K}$

where $\mathbb{K} = \mathbb{R}^n$ or $\mathbb{C}^n$ and $\|\cdot\|$ is any norm in $\mathbb{R}^n$.
#+end_quote

** Solution
First, rewrite $x = (x - y) + y$ and apply the triangle inequality:

\begin{align*}
\|x\| &= \|(x-y) + y\| \\
       &\le \|x-y\| + \|y\|
\end{align*}

which gives:

$$\|x\| - \|y\| \le \|x-y\| \tag{1}$$

Similarly, rewrite $y = (y - x) + x$ and apply the triangle inequality:

\begin{align*}
\|y\| &= \|(y-x) + x\| \\
       &\le \|y-x\| + \|x\|
\end{align*}

By homogeneity, $\|y - x\| = \|{-(x-y)}\| = |{-1}| \cdot \|x-y\| = \|x-y\|$, so:

$$\|y\| - \|x\| \le \|x-y\| \tag{2}$$

Combining (1) and (2): since both $\|x\|-\|y\| \le \|x-y\|$ and $-(\|x\|-\|y\|) \le \|x-y\|$, we have:

$$\bigl|\|x\| - \|y\|\bigr| \le \|x-y\|$$

* Problem 1.29 :DONE:
** Task
#+begin_quote
(Vector space) On $\mathbb{R}^2$ we define the following operations

$(x_1, x_2) \oplus (y_1, y_2) = (x_1 + y_1, x_2 + y_2)$, $\lambda \odot (x_1, x_2) = (\lambda x_1, 0)$.

Which vector space axioms does $(\mathbb{R}^2, \oplus, \odot)$ satisfy? Is it a vector space?
#+end_quote

** Solution
1. *Associativity of addition*
   $(x \oplus y) \oplus z = (x_1+y_1+z_1,\, x_2+y_2+z_2) = x \oplus (y \oplus z)$.

2. *Commutativity of addition*
   $x \oplus y = (x_1+y_1,\, x_2+y_2) = y \oplus x$.

3. *Additive identity*
   $(x_1, x_2) \oplus (0, 0) = (x_1, x_2)$.

4. *Additive inverse*
   $(x_1, x_2) \oplus (-x_1, -x_2) = (0, 0)$.

5. *Distributivity over scalar addition*
   Both sides yield $((\lambda+\mu)x_1,\, 0)$.

6. *Distributivity over vector addition*
   Both sides yield $(\lambda(x_1+y_1),\, 0)$.

7. *Compatibility of scalar multiplication*
   Both sides yield $(\lambda\mu\, x_1,\, 0)$.

8. *Scalar multiplicative identity*
   $1 \odot (x_1, x_2) = (x_1, 0) \neq (x_1, x_2)$ when $x_2 \neq 0$.

*Conclusion:* $(\mathbb{R}^2, \oplus, \odot)$ is not a vector space.

Axioms 1-7 hold, but axiom 8 fails: scalar multiplication by $1$ zeroes out the second component.

* Problem 1.33
** Task
#+begin_quote
(Bases and regular matrices) Let $\mathcal{U} = \{u_1, \ldots, u_n\}$ be a basis of a vector space $\mathbb{E}$. Let $A \in \mathbb{K}^{n \times n}$ and vectors $v_j = \sum_{i=1}^{n} A_{ij} u_j$. Prove that $\mathcal{V} = \{v_1, \ldots, v_n\}$ is also a basis if and only if $A$ is invertible.
#+end_quote

** Notes

** Solution

* Problem 1.37
** Task
#+begin_quote
(Direct sum of triangular matrices) Let $\mathbb{E} = \mathbb{K}^{n \times n}$, we define $\mathbb{F}_1, \mathbb{F}_2 \subset \mathbb{E}$ as the subspaces of upper and lower triangular matrices, respectively. Determine whether $\mathbb{E} = \mathbb{F}_1 \oplus \mathbb{F}_2$. Does the result vary if we replace $\mathbb{F}_1$ by $\mathbb{F}_1'$ the subspace of 1-stricly triangular matrices (as defined in ex. 1.28)?
#+end_quote

** Notes

** Solution
