#+title: Ps 02
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-03-16>
#+lastmod: <2026-03-16 08:28>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t
#+startup: overview latexpreview inlineimages

* Problem 1.24
** Task
#+begin_quote
(Reverse Triangle Inequality). From the triangle inequality, derive the /reverse triangle inequality/, namely

$| \|x\| - \|y\| | \leq \|x - y\|$, $\forall (x, y) \in \mathbb{K}$

where $\mathbb{K} = \mathbb{R}^n$ or $\mathbb{C}^n$ and $\|\cdot\|$ is any norm in $\mathbb{R}^n$.
#+end_quote

** Notes

** Solution

* Problem 1.29
** Task
#+begin_quote
(Vector space) On $\mathbb{R}^2$ we define the following operations

$(x_1, x_2) \oplus (y_1, y_2) = (x_1 + y_1, x_2 + y_2)$, $\lambda \odot (x_1, x_2) = (\lambda x_1, 0)$.

Which vector space axioms does $(\mathbb{R}^2, \oplus, \odot)$ satisfy? Is it a vector space?
#+end_quote

** Notes

** Solution

* Problem 1.33
** Task
#+begin_quote
(Bases and regular matrices) Let $\mathcal{U} = \{u_1, \ldots, u_n\}$ be a basis of a vector space $\mathbb{E}$. Let $A \in \mathbb{K}^{n \times n}$ and vectors $v_j = \sum_{i=1}^{n} A_{ij} u_j$. Prove that $\mathcal{V} = \{v_1, \ldots, v_n\}$ is also a basis if and only if $A$ is invertible.
#+end_quote

** Notes

** Solution

* Problem 1.37
** Task
#+begin_quote
(Direct sum of triangular matrices) Let $\mathbb{E} = \mathbb{K}^{n \times n}$, we define $\mathbb{F}_1, \mathbb{F}_2 \subset \mathbb{E}$ as the subspaces of upper and lower triangular matrices, respectively. Determine whether $\mathbb{E} = \mathbb{F}_1 \oplus \mathbb{F}_2$. Does the result vary if we replace $\mathbb{F}_1$ by $\mathbb{F}_1'$ the subspace of 1-stricly triangular matrices (as defined in ex. 1.28)?
#+end_quote

** Notes

** Solution
