#+title: Exam
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-01-14>
#+lastmod: <2026-04-13 17:28>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{mathtools}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t tags:nil
#+property: header-args :eval never-export
#+startup: overview latexpreview inlineimages

* Problem A1
#+begin_quote
What is the cardinality of the set of all real numbers from $(0, 1)$, whose decimal representation does not contain odd digits?


(a) This set has cardinality of $\mathbb{N}$ (that is $\aleph_0$).

(b) This set has cardinality of $\mathbb{R}$ (that is continuum $\mathfrak{c}$).

(c) This set is finite.

(d) This set has cardinality that is in between $\aleph_0$ and $\mathfrak{c}$.
#+end_quote

* Problem A2
#+begin_quote
Find $\lim_{n\to\infty} \frac{2^{n+1}}{3^n - 2^n}$.

(a) $\frac{2}{3}$ \qquad (b) $1$ \qquad (c) $0$ \qquad (d) $+\infty$
#+end_quote

* Problem A3
#+begin_quote
Find $\text{gcd}(2^{100}, 20^{10})$.

(a) $2^{10}$ \qquad (b) $2^{20}$ \qquad (c) $2^{40}$ \qquad (d) $20^{10}$
#+end_quote

* Problem A4
#+begin_quote
Find the sum of the roots of $z^2 - z + 2i = 0$.

(a) $1$ \qquad (b) $\sqrt{5}$ \qquad (c) $0$ \qquad (d) $1 + 2i$
#+end_quote

* Problem A5
#+begin_quote
What is the set $M = \bigcup_{\alpha \in [0,1]} A_\alpha$, if $A_\alpha = \{x : \alpha^2 \leqslant x \leqslant \alpha\}$?

(a) $M = \{0, 1\}$ \qquad (b) $M = [0, 1]$ \qquad (c) $M = (0, 1)$ \qquad (d) $M = [\frac{1}{4}, \frac{1}{2}]$
#+end_quote

* Problem A6
#+begin_quote
What will the following code output?
#+begin_src julia
a = [2]
for i in 1:8
    if mod(2^i, 9) == 1
        push!(a, i)
    end
end
println(sum(a))
#+end_src
(a) $6$ \qquad (b) $8$ \qquad (c) $10$ \qquad (d) this code will return an error.
#+end_quote

* Problem A7
#+begin_quote
The set $A$ has 2 elements, the set $B$ has 4 elements. How many surjective functions $f: \mathscr{P}(A) \times B \to \mathscr{P}(A) \times B$ are there?

(a) $6!$ \qquad (b) $8!$ \qquad (c) $12!$ \qquad (d) $16!$
#+end_quote

* Problem A8
#+begin_quote
Choose the statement to which the statement $(P \implies Q) \land (P \implies R)$ is equivalent

(a) $(P \land Q) \implies R$ (b) $P \implies (Q \lor R)$ (c) $(P \lor Q) \implies R$ (d) $P \implies (Q \land R)$
#+end_quote

* Problem A9
#+begin_quote
Find the coefficient of $x^{20}$ in the expression of $(x^2 - \frac{1}{x})^{100}$.

(a) $\binom{100}{20}$ \qquad (b) $\binom{100}{40}$ \qquad (c) $-\binom{100}{60}$ \qquad (d) $\binom{100}{80}$
#+end_quote

* Problem A10
#+begin_quote
Consider the set
$$S = \left\{ \frac{m}{n} : m, n \in \mathbb{N}, \ m^2 < 2n^2 \right\}.$$
Find $\sup S$ in $\mathbb{R}$ (with the usual order).

(a) $\sqrt{2}$ \qquad (b) $\frac{1}{\sqrt{2}}$ \qquad (c) $\frac{1}{2}$ \qquad (d) It doesn't exist.
#+end_quote

* Problem B1
#+begin_quote
Propositions $P, Q$, and $R$ have the same truth value. Prove that the proposition $(P \lor \neg Q) \land (Q \lor \neg R) \land (R \lor \neg P)$ is always true.
#+end_quote

* Problem B2
#+begin_quote
Let $R$ be a relation on $\mathbb{R}$ such that $xRy$ if and only if $x - y \in \mathbb{Q}$. Prove that $R$ is an equivalence relation.
#+end_quote

* Problem B3
#+begin_quote
Find the number of natural numbers not exceeding 200 that are not divisible by 5 or by 11.
#+end_quote

* Problem B4
#+begin_quote
The following code aims to find all elements in the array ~a_array~ that are greater than 13 and are not present in array ~b_array~. Fill in the missing bits. (The syntax for and in Julia is &&, for or is ||, and for not is !).
#+begin_src julia
a_array = [2, 71, 14, 11, 11, 2, 12, 14, 120]
b_array = [14, 2, 121, 11, 2025]
result_array = []
for a in a_array
    if ...
        push!(..................., ........................)
    end
end
#+end_src
#+end_quote

* Problem B5
#+begin_quote
Depict on a complex plane the set $\{z \in \mathbb{C} : |iz - 1| = 1\}$.
#+end_quote

* Problem B6
#+begin_quote
Provide an example of strictly decreasing divergent sequence. (No explanations required).
#+end_quote

* Problem B7
#+begin_quote
For sets $A$ and $B$ prove that $A \setminus B = A \setminus (A \cap B)$.
#+end_quote

* Problem B8
#+begin_quote
Let $f: \mathbb{R} \to \mathbb{R}$ be defined as $f(x) = \sqrt{|x|}$. Find $f(A)$ if $A = (-\infty, -1) \cup (0, 1)$.
#+end_quote

* Problem B9
#+begin_quote
Prove that two hyperplanes in $\mathbb{R}^4$ given by
$$2x_1 - 2x_2 + x_3 + 3x_4 = 5 \quad \text{and} \quad x_1 - 3x_2 + x_3 - 3x_4 = 5$$
are orthogonal.
#+end_quote

* Problem B10
#+begin_quote
Integers $a, b$ are such that $3 \nmid ab$. Prove that $a^2 + b^2$ cannot be a perfect square.
#+end_quote

* Problem C1
#+begin_quote
Let $A = \{1, 2, \dots, n+1\}$. How many strictly increasing sequences of length $n$ can be constructed from the elements of $A$?
#+end_quote

* Problem C2
#+begin_quote
Prove the inequality for all nonnegative $x_1, \dots, x_n$
$$\prod_{k=1}^n (1 + x_k) \geqslant 1 + \sum_{k=1}^n x_k.$$
#+end_quote

* Problem C3
#+begin_quote
Find the limit $\lim_{n \to \infty} (\sqrt[4]{n^4 - n^2} - n)$.
#+end_quote

* Problem C4
#+begin_quote
There are 5 points on the plane with integer coordinates. Prove that the midpoint of one of the segments joining these points also has integer coordinates.
#+end_quote

* Problem C5
#+begin_quote
Let $f(x) = x^2 + px + q$. Prove that at least one of the numbers $|f(0)|, |f(1)|, |f(-1)|$ is greater or equal $\frac{1}{2}$.
#+end_quote

* Problem C6
#+begin_quote
Prove that if two sets $A$ and $B$ satisfy $|A| = |B|$, then $|\mathscr{P}(A)| = |\mathscr{P}(B)|$.
#+end_quote

* Problem C7
#+begin_quote
Find a polynomial with real coefficients among whose roots are 2 and $1 - i$.
#+end_quote

* Problem C8
#+begin_quote
How many strings of six lowercase letters from the English alphabet contain the letters a and b? (The formula suffices, no need to calculate the concrete number).
#+end_quote
