#+title: Ps 03
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-03-19>
#+lastmod: <2026-03-19 19:46>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t
#+startup: overview latexpreview inlineimages

* Problem 1.23
** Task
#+begin_quote
(Norm Equivalences in $\mathbb{R}^n$). Show that $\|\cdot\|_1$, $\|\cdot\|_2$ and $\|\cdot\|_\infty$ are equivalent norms in $\mathbb{R}^n$ (of course, without using Theorem 1.56!).
#+end_quote

** Notes

** Solution

* Problem 1.38
** Task
#+begin_quote
(Distances are not always induced by norms)

From Proposition 1.53 we have seen that for any normed vector space $(\mathbb{E}, \|\cdot\|_{\mathbb{E}})$, we can define a distance on $\mathbb{E}$ $d_{\|\cdot\|_{\mathbb{E}}}(x,y) = \|x - y\|_{\mathbb{E}}$ such that $(\mathbb{E}, d_{\|\cdot\|_{\mathbb{E}}})$ is a metric space. We shall see with this exercise that not every distance can be expressed in terms of a norm $\|x - y\|$.

(i) Let $X$ be an arbitrary non-empty set, we define the /discrete distance/ $\rho : X \times X \to \mathbb{R}$, given by

\[
\rho(x, y) = \begin{cases} 0, & \text{if } x = y \\ 1, & \text{if } x \neq y \end{cases}.
\]

Prove that $(X, \rho)$ is a metric space.

(ii) We now set $X = \mathbb{R}$ with the distance $\rho : \mathbb{R} \times \mathbb{R} \to \mathbb{R}$ as defined above, prove by contradiction that $\rho$ cannot be written as $\rho(x,y) = \|x - y\|$, for any $\|\cdot\| : \mathbb{R} \to \mathbb{R}$ defined on $\mathbb{R}$. (*Indication:* Suppose that $\rho(x,y) = \|x - y\|$ for some $\|\cdot\|$, then $\|1\| = \rho(0, 1) = 1$, and $\|2\| = |2| \cdot \|1\| = 2$. What does this contradict?)

(iii) Similarly to the previous point, prove this generalized result:

Given $\mathbb{E} \neq \{0\}$ a $\mathbb{R}$-vector space and $d(\cdot, \cdot) : \mathbb{E} \times \mathbb{E} \to \mathbb{R}$ a /bounded/ metric (i.e. there exists $K > 0$ such that $d(x, y) \leq K$, $\forall x, y \in \mathbb{E}$). Then $d(\cdot, \cdot)$ cannot be written as $d(x, y) = \|x - y\|$, for any $\|\cdot\| : \mathbb{E} \to \mathbb{R}$.

(iv) Prove that for any norm $\|\cdot\| : \mathbb{E} \to \mathbb{R}$ defined on a $\mathbb{R}$-vector space $\mathbb{E} \neq \{0\}$, the function $d(\cdot, \cdot) : \mathbb{E} \times \mathbb{E} \to \mathbb{R}$ given by

\[
d(x, y) := \frac{\|x - y\|}{1 + \|x - y\|}
\]

defines a distance on $\mathbb{E}$ but is not induced by a norm. (*Indication:* to see that $d(x,y)$ as defined above satisfies the triangular inequality, it might be useful to first prove that the function $\phi(t) = t/(1+t)$ is monotone increasing on the positive real numbers and subadditive, i.e. $\phi(a + b) \leq \phi(a) + \phi(b)$, for all $a, b \geq 0$)
#+end_quote

** Notes

** Solution

* Problem 1.44
** Task
#+begin_quote
(Dual space). The following is a similar but perhaps more laborious exercise to the previous one (ex. 1.43).

Let $\mathbb{E} = \mathbb{C}_2[X]$ be the space of *complex* polynomials $p(X)$ with $\deg p \leq 2$ (suppose that $\{1, X, X^2\}$ is proven to be a basis on $\mathbb{E}$), and let $f, g \in \mathbb{E}^*$ be as defined below:

\[
f(p(X)) = p(1), \qquad \text{and} \qquad g(p(X)) = p(i),
\]

where $i \in \mathbb{C}$ is the imaginary unit element.

(i) Are $f$ and $g$ linearly independent?

(ii) If the previous point is affirmative, give a third element $h \in \mathbb{E}^*$ such that $\{f, g, h\}$ forms a basis on $\mathbb{E}^*$.

(iii) Does the system of equations

\[
\begin{cases} f(p(X)) = i, & \text{and} \\ g(p(X)) = 1 \end{cases}
\]

have any solution for $p \in \mathbb{E}$? if there is, give all the polynomials that are solution of the system. Is the solution unique?
#+end_quote

** Notes

** Solution

* Problem 2.4
** Task
#+begin_quote
(Inner product of functions)

We define the following set of functions:

\[
\mathbb{E} = \{f : [0, \pi] \to \mathbb{R} \;:\; f(x) = \alpha \cos x + \beta \sin x, \; \alpha, \beta \in \mathbb{R}\}.
\]

(i) Prove that $\mathbb{E}$, when equipped with the usual addition $((f+g)(x) = f(x)+g(x))$ and scalar multiplication of functions $((\lambda \cdot f)(x) = \lambda \cdot f(x))$, is a vector space.

(ii) In the vector space $\mathbb{E}$ we define the following inner product:

\[
\omega(f, g) = \int_0^{\pi} f(x) g(x) \, \mathrm{d}x.
\]

Is the basis $\mathcal{B} := \{\cos(x), \sin(x)\}$ an orthogonal basis w.r.t. $\omega$? Is it orthonormal? Give an orthogonal/orthonormal basis if $\mathcal{B}$ is not.
#+end_quote

** Notes

** Solution
