#+title: Rings And Fields
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-11>
#+lastmod: <2025-11-11 19:05>
#+options: num:t
#+startup: overview

* Definitions
Most important definitions:
- Ring :: is a set of elements, that satisfy following requirements:
  - Is an commutative group.
  - Multiplication is associative.
  - Multiplication distributes over addition.
- Unity :: (in the context of rings) is a property of ring to have multiplicative identity 1 != 0 such that 1*a = a for all a ∈ R.
- Commutative ring :: property of ring of ab = ba for all a,b ∈ R.
- Unit :: is an element u ∈ R with multiplicative inverse u^-1, such that u*u^-1 = 1.

* 1. What is a ring? (informal)
Think of a *ring* as a set where you can add and multiply, with addition behaving like the integers and multiplication behaving reasonably well (associative and distributive over addition). Rings generalise ℤ, polynomial arithmetic, matrix arithmetic, and lots of algebraic structures.

- *Formal definition*
  A *ring* R is equipped with two binary operations + and *, such that:
  1. (R, +) is an abelian (commutative) group
     - There is additive identity 0. Every element a has additive inverse -a.
  2. Multiplication is associative: (a*b)*c = a*(b*c) for all a,b,c ∈ R.
  3. Multiplication distributes over addition:
     - a*(b+c) = a*b + a*c and (a+b)*c = a*c + b*c.

  Extra condtitions in statement:
  - A *ring with unity (or with identity)* has a multiplicative identity 1 != 0 such that 1*a=a for all a.
  - A *commutative ring* means ab = ba for all a,b.

* 2. Special elements in a ring
- A *unit* is an element u ∈ R with a multiplicative inverse u^-1, so u*u^-1 = 1.

  Examples:
  - In ℤ the only units are 1 and -1.
  - In ℚ that could be any number.
- A *zero divisor* is a nonzero a such that there exists nonzero b with ab = 0

* 3. Integral domains
A commutative ring with unity R is an integral domain if it has no zero divisors: whenever ab = 0, either a = 0 or b = 0.

(This section relies too much on fields, so I will write it later.)

* 4. Fields - definition and intuition
A field F is a commutative ring with unity in which every nonzero element has a multiplicative inverse.
