#+title: Vectors
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-22>
#+lastmod: <2025-11-23 11:58>
#+options: num:t
#+startup: overview

- [[https://www.youtube.com/watch?v=k7RM-ot2NWY][Very helpful video on introduction to vectors]]

* Terminology
- Vector :: is a quantity defined by both magnitude and direction.
- Basis Vector :: is a set of vectors that are linearly independent and that span the vector space.
- Span :: of the set of vectors is the set of all possible linear combinations o fhte vectors.
- Collinear Vectors :: are vectors that lie along the same line, or there must exist a scalar multiple relationship between teh vectors.
- Coplanar Vectors :: are vectors that lie in the same plane in three-dimensional space.
- Non-Coplanar Vectors :: vectors that do not lie on the same plane in three dimensional space.
- Equal Vectors :: are vectors that have the same magnitude and direction, irrespective of their original points.
- Linear Combination :: is a set of vectors {v1, v2, ..., vn} if v can be exressed as a1*v1 + a2*v2, ..., an*vn, where a1, a2, ..., an are scalars.
