#+title: Problem Set 7
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-16>
#+lastmod: <2025-11-16 16:25>
#+options: num:t
#+startup: overview

* Analysis
* How to prove equivalence relations?
1. *Reflexive*
   Let a ‚ąą A. Show a~a. (one sentence: reason why the relaton includes (a,a) or why the property holds)

   Therefore, ‚ąÄa ‚ąą A, a~a.

2. *Symmetric*
   Let a,b ‚ąą A, and assume a~b. Show b~a. (one sentence: use definition of algebraic symmetry)

   Therefore, ‚ąÄa,b ‚ąą A, a~b --> b~a.

3. *Transitive*
   LEt a,b,c ‚ąą A, and assume a~b and b~c. Show a~c. (one sentence: combine assumptions via definition/transitivity property)

   Therefore, ‚ąÄa,b,c ‚ąą A, (a~b ‚ąß b~a) --> a~c.

4. *Conclude*
   Since three properties hold, ~ is an equivalence relation.

* Problem 1 [DONE]
** Task
Define R on ‚Ą§ a mRn <--> 2|(m^2 + n^2) for all m,n ‚ąą ‚Ą§. Is R an equivalence relation?

** Solution
#+begin_quote
*Proposition.* mRn <--> 2|(m^2 + n^2) for all m,n ‚ąą ‚Ą§. Prove R an equivalence relation.
        2|(m^2 + n^2) <--> m^2 + n^2 ‚Č° 0 (mod 2)

*Proof.*
- *Reflexive* ‚ąÄa ‚ąą A; a~a.
  Let a ‚ąą ‚Ą§.
  a^2 + a^2 ‚Č° 0 (mod 2)
  2(a^2) ‚Č° 0 (mod 2)
  which is obviously true.
  Hence, ‚ąÄa ‚ąą ‚Ą§; a~a.

- *Symmetric* ‚ąÄa,b ‚ąą A; a~b --> a~b.
  Let a,b ‚ąą ‚Ą§.
  Assume aRb, thus,
  a^2 + b^2 ‚Č° 0 (mod 2) <--> b^2 + a^2 ‚Č° 0 (mod 2)
  Thus, a~b --> b~a.
  Hence, ‚ąÄa,b ‚ąą ‚Ą§; a~b --> b~a.

- *Transitive* ‚ąÄa,b,c ‚ąą A; (a~b ‚ąß b~c) --> a~c.
  Let a,b,c ‚ąą ‚Ą§.
  Assume aRb and bRc, thus,
  a^2 + b^2 ‚Č° 0 (mod 2)
  b^2 + c^2 ‚Č° 0 (mod 2)

  Thus,
  a^2 + b^2 + b^2 + c^2 ‚Č° 0 (mod 2)
  a^2 + 2(b^2) + c^2 ‚Č° 0 (mod 2)        (since 2|2(b^2), substract 2(b^2) from LHS)
  a^2 + c^2 ‚Č° 0 (mod 2)

  Hence, ‚ąÄa,b ‚ąą ‚Ą§; (a~b ‚ąß b~c) --> a~c.

*Conclusion.* Since mRn is reflexive, symmetric and transitive for all m,n ‚ąą ‚Ą§, R is an equivalence relation.
#+end_quote

* Problem 2 [DONE]
*Problem topic:* Relations - Equivalence.

** Task
Let R be a relation on the real numbers defined by xRy <--> x^2 = y^2. Is R an equivalence relation?

** Solution
#+begin_quote
*Proposition.* xRy <--> x^2 = y^2, x,y ‚ąą ‚ĄĚ. Prove R is an equivalence relation.

*Proof.*
- *Reflexive:* ‚ąÄa‚ąąA, a~a.
  Let a ‚ąą ‚ĄĚ. Thus,
  a^2 = a^2
  trivial.
  Hence, ‚ąÄa‚ąą‚ĄĚ, a~a.

- *Symmetric:* ‚ąÄa,b‚ąąA; a~b --> b~a.
  Let a,b ‚ąą ‚ĄĚ, aRb Thus,
  a^2 = b^2 <--> b^2 = a^2
  Hence, ‚ąÄa,b‚ąą‚ĄĚ; a~b --> b~a.

- *Transitive:* ‚ąÄa,b,c‚ąąA; (a~b ‚ąß b~c) --> a~c.
  Let a,b,c ‚ąą ‚ĄĚ, aRb and bRc Thus,
  a^2 = b^2
  b^2 = c^2
  Thus,
  a^2 = b^2 = b^2 = c^2
  a^2 = c^2
  Hence, ‚ąÄa,b,c‚ąą‚ĄĚ; (a~b ‚ąß b~c) --> a~c.

*Conclusion.* Since xRy is reflexive, symmetric and transitive for all x,y ‚ąą ‚ĄĚ, R is an equivalence relation.
#+end_quote

* Problem 3 [DONE]
*Problem topic:* Relations - Equivalence.
** Task
Define R on ‚Ą§ as xRy <--> 4|(x + 3y) for all x,y ‚ąą ‚Ą§. Is R an equivalence relation?

** Solution
#+begin_quote
*Proposition.* If xRy <--> 4|(x + 3y) for all x,y ‚ąą ‚Ą§, R an equivalence relation.
- 4|(x + 3y) <--> x + 3y ‚Č° 0 (mod 4)

*Proof.*
- *Reflexive:* ‚ąÄa‚ąąA; a~a.
  Let a ‚ąą ‚Ą§. Thus
  a + 3a ‚Č° 0 (mod 4)
  4a ‚Č° 0 (mod 4)
  trivial
  Hence, ‚ąÄa‚ąą‚Ą§; a~a.

- *Symmetric:* ‚ąÄa,b‚ąąA; a~b --> b~a.
  Let a,b ‚ąą ‚Ą§.
  Assume a~b, thus,
  a + 3b ‚Č° 0 (mod 4) <--> 3b + a ‚Č° 0 (mod 4)
  3b + a ‚Č° 0 (mod 4) (multiply both sides by 3)
  9b + 3a ‚Č° 0 (mod 4)
  (b + 3a) + 8b ‚Č° 0 (mod 4)
  (b + 3a) + 4(2b) ‚Č° 0 (mod 4) (substract 4(2b), since 4|4(2b))
  b + 3a ‚Č° 0 (mod 4)
  Hence, ‚ąÄa,b‚ąą‚Ą§; a~b --> b~a.

- *Transitive:* ‚ąÄa,b,c‚ąąA; (a~b ‚ąß b~c) --> a~c.
  Let a,b,c ‚ąą ‚Ą§.
  Assume a~b and b~c, thus,
  a + 3b ‚Č° 0 (mod 4)
  b + 3c ‚Č° 0 (mod 4)
  thus,
  a + 3b + b + 3c ‚Č° 0 (mod 4)
  a + 4b + 3c ‚Č° 0 (mod 4) (substract 4b, since 4|4b)
  a + 3c ‚Č° 0 (mod 4)
  Hence, ‚ąÄa,b,c‚ąą‚Ą§; (a~b ‚ąß b~c) --> a~c.

*Conclusion.* Since xRy is reflexive, symmetric and transitive, R is equivalence for all x,y ‚ąą ‚Ą§.
#+end_quote

* Problem 4 [DONE]
** Task
Prove or disprove: If R is an equivalence relation on an infinite set S, then R has infinitely many equivalence classes.

** Solution
- Equivalence class :: is a subset of a set where all elements are related to each other by an equivalence relation.

#+begin_quote
*Proposition.* If xRy <--> 2|(x+y), x,y ‚ąą ‚Ą§, R is an equivalence relation.

*Proof.*
- *Reflexive:* ‚ąÄa‚ąąA; a~a.
  Let a ‚ąą ‚Ą§. Thus,
  a + a ‚Č° 0 (mod 2)
  2(a) ‚Č° 0 (mod 2)
  trivial.
  Hence, ‚ąÄa‚ąą‚Ą§; a~a.

- *Symmetric:* ‚ąÄa,b‚ąąA; a~b --> b~a.
  Let a,b ‚ąą ‚Ą§.
  Assume a~b. Thus,
  a + b ‚Č° 0 (mod 2) <--> b + a ‚Č° 0 (mod 2)
  trivial.
  Hence, ‚ąÄa,b‚ąą‚Ą§; a~b --> b~a.

- *Transitive:* ‚ąÄa,b,c‚ąąA; (a~b ‚ąß b~c) --> a~c.
  Let a,b,c ‚ąą ‚Ą§.
  Assume a~b and b~c. Thus,
  a + b ‚Č° 0 (mod 2)
  b + c ‚Č° 0 (mod 2)
  Thus,
  a + b + b + c ‚Č° 0 (mod 2)
  a + 2b + c ‚Č° 0 (mod 2)        (substract 2b, since 2|2b)
  a + c ‚Č° 0 (mod 2)
  Hence, ‚ąÄa,b,c‚ąą‚Ą§; (a~b ‚ąß b~c) --> a~c.

*Conclusion.* Since R is reflexive, symmetric and transitive, it is an equivalence relation for all x,y ‚ąą ‚Ą§.
#+end_quote

Thus, since xRy <--> 2|(x+y), x,y ‚ąą ‚Ą§, R is an equivalence relation, and has only 2 equivalence classes:

{a ‚ąą ‚Ą§ : a ‚Č° 1 (mod 2)}
{a ‚ąą ‚Ą§ : a ‚Č° 0 (mod 2)}

This disproves initial statement.

* Problem 5 [SKIP]
** Task
There are five different equivalence relations on the set A = {a,b,c}. Describe them all. (Here you can just draw a picture instead of text if you prefer.)

** Solution
* Problem 6 [SKIP]
** Task
Let S be the set of all triangles in the plane. Define T1 ~ T2 if T1 is similar to T2. Prove that ~ is an equivalence relation.

** Solution
* Problem 7 [SKIP]
** Task
Consider the partition P = {{0}, {-1,1}, {-2,2}, {-3,3}, ...} of Z. Describe the equivalence relation whose equivalence classes are the elements of P.

** Solution
* Problem 8 [SKIP]
** Task
A relation R on ‚ĄĚ is defined as xRy, <--> |x| <= |y|. Is this a total order?

** Solution
* Problem 9 [SKIP]
** Task
In a basketball tournament, each team plays every other team exactly once. Define a relation ‚Čľ on the set of all teams as: for two teams A and B, we say A ‚Čľ B <--> the final ranking of B is at least as high as that of A. Is ‚Čľ a partial order? Is it a total order?

** Solution
* Problem 10 [DONE] [PROVED ON BOARD]
** Task
A relation ‚Čľ on ‚ĄĚ^2 is defined as
        (x1, y1) ‚Čľ (x2, y2) <--> |x2 - x1| <= y2 - y1.

Prove that ‚Čľ is a partial order. Is it a total order?

** Solution
* Problem 11 []
** Task
For the problems above, where there is a partial order, decide which elements are:
- greatest/least
- maximal/minimal

** Solution
*Greatest element:* an element g ‚ąą S, such that for every x ‚ąą S, x ‚Čľ g.
Unique element

*Least element:* an element l ‚ąą S, such that for every x ‚ąą S, l ‚Čľ x.
Unique element

*Maximal element:* an element m ‚ąą S, is maximal iff there is no x ‚ąą S, (m ‚Čľ x) ‚ąß (x != m).
Multiple elements possible

*Minimal element:* an element n ‚ąą S, is minimal iff there is no x ‚ąą S, (x ‚Čľ m) ‚ąß (x != m).
Multiple elements possible

Therefore,

* Problem 12 []
** Task
** Solution
* Problem 13 []
** Task
Let A given by A = {m/n : m, n ‚ąą N, m < n}  be a subset of R with the standard order ‚Č§. Find sup A, inf A, max A and min A (if they exist).

** Solution
