#+title: Ps 03
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-01-26>
#+lastmod: <2026-01-26 13:21>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t
#+startup: overview latexpreview inlineimages

* Problem 1
** Task
#+begin_quote
The ReLU function is a standard activation function in neural networks. It is simply given by $f:\mathbb{R}\rightarrow\mathbb{R}$
$f(x)=\begin{cases}0,&x\le0,\\ x,&x>0.\end{cases}$
Use the ( , $\delta$)-definition of continuity to determine, where $f$ is continuous and where not. Plot $f$ in Julia.
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_1.jl
#+end_src

* Problem 2
** Task
#+begin_quote
Define another activation function $g:\mathbb{R}\rightarrow\mathbb{R}$,
$g(x)=\log(1+e^{x})$.
(a) Why is $g$ continuous on $\mathbb{R}$?
(b) Plot $f$ and $g$ in Julia. Which activation function looks "smoother", $f$ or $g$?
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_2.jl
#+end_src

* Problem 3
** Task
#+begin_quote
A data set contains the locations $X=(1,2,3,4,5,6,7,8,9)^{\top}$ with corresponding observations $Y=(3,5,7,7,11,15,19,?,27)^{\top}$ The observation at $x=8$ is missing.
(a) Provide an educated guess for the observation at $x=8$.
(b) Write new or modify existing Julia code to fill in missing observations.
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_3.jl
#+end_src

* Problem 4
** Task
#+begin_quote
We want to estimate the value of $\exp(1.3)$ by the following procedure:
1. Use Julia to implement a finite sum to determine $e=\exp(1)$ up to an error smaller than $10^{-6}$ according to Proposition 1.3.12.
2. Express $\exp(1.3)$ by using $\exp(1)$ and $\exp(0.3)$.
3. Replace the "unknown" value of $\exp(0.3)$ by a linear approximation from $\exp(0)$ to $\exp(1)$.
4. How big is the error?
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_4.jl
#+end_src

* Problem 5
** Task
#+begin_quote
Consider the two functions $f,g:(0,\infty)\rightarrow\mathbb{R}$ given by

$$f(x)=\log(x), \quad g(x)=2x^{2}-2$$

Plot both functions in Julia and provide mathematical reasons for the number of intersection points that you may observe.
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_5.jl
#+end_src

* Problem 6
** Task
#+begin_quote
Write Julia functions approxSin and approxCos that approximate $\sin$ and $\cos$ by using their truncated series expansions. Plot both functions using your approximations.
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_6.jl
#+end_src
