#+title: Ps 04
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-04-12>
#+lastmod: <2026-04-12 20:09>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t
#+startup: overview latexpreview inlineimages

* Problem 1 :DONE:
** Task
#+begin_quote
Let $f : \mathbb{R}^2 \to \mathbb{R}$ be defined by $f(x, y) = x^2 + y^2$.

(a) Compute $\nabla f(x, y)$.

(b) Evaluate it at $(1, 2)$ and determine the local (affine) linear approximation of $f$ in $(1, 2)$.

(c) Plot $f$ and $\nabla f$ in Julia.
#+end_quote

** Solution

*** (a)

Let $f : \mathbb{R}^2 \to \mathbb{R}, \quad f(x, y) = x^2 + y^2$.

By definition, the partial derivatives are:

\begin{align*}
\partial_1 f(x, y) &= \lim_{h \to 0} \frac{f(x + h, y) - f(x, y)}{h}, \\
\partial_2 f(x, y) &= \lim_{h \to 0} \frac{f(x, y + h) - f(x, y)}{h}.
\end{align*}

Computing $\partial_1 f$:

\begin{align*}
\partial_1 f(x, y)
&= \lim_{h \to 0} \frac{(x + h)^2 + y^2 - x^2 - y^2}{h} \\
&= \lim_{h \to 0} \frac{2xh + h^2}{h} \\
&= \lim_{h \to 0} (2x + h) = 2x.
\end{align*}

By analogous computation, $\partial_2 f(x, y) = 2y$.

Therefore:

$$\nabla f(x, y) = \begin{pmatrix} 2x \\ 2y \end{pmatrix}$$

*** (b)

Evaluating the gradient at $p = (1, 2)$:

\[
\nabla f(1, 2) = \begin{pmatrix} 2 \cdot 1 \\ 2 \cdot 2 \end{pmatrix} = \begin{pmatrix} 2 \\ 4 \end{pmatrix}.
\]

The Fréchet derivative $Df(p) : \mathbb{R}^n \to \mathbb{R}^m$ is the unique linear map satisfying:

\[
\lim_{h \to 0} \frac{\|f(p + h) - f(p) - Df(p)(h)\|}{\|h\|} = 0.
\]

For $f : \mathbb{R}^n \to \mathbb{R}$, this linear functional has the representation $Df(p)(h) = \nabla f(p)^\top h$, yielding the affine approximation:

$$L(x) = f(p) + \nabla f(p)^{\top} (x - p)$$

With $p = (1, 2)$ and $f(1, 2) = 1^2 + 2^2 = 5$:

\begin{align*}
L(x, y) &= 5 + \begin{pmatrix} 2 & 4 \end{pmatrix} \begin{pmatrix} x - 1 \\ y - 2 \end{pmatrix} \\
         &= 5 + 2(x - 1) + 4(y - 2) \\
         &= 2x + 4y - 5.
\end{align*}

*** (c)

#+begin_src julia :results value :exports both :tangle julia/p_01.jl
using Plots

f(x, y) = x^2 + y^2
L(x, y) = 2x + 4y - 5

xs = -6:0.05:6
ys = -6:0.05:6

anim = Animation()

for azimuth in 0:2:360
    surface(xs, ys, (x, y) -> f(x, y),
            alpha=0.8,
            colorbar=false,
            label="f(x,y)")
    surface!(xs, ys, (x, y) -> L(x, y),
             alpha=0.6,
             color=:reds,
             label="L(x,y)")
    scatter!([1], [2], [5],
             color=:black,
             markersize=4,
             label="(1,2,5)")
    plot!(xlabel="x", ylabel="y", zlabel="z",
          camera=(azimuth, 20),
          size=(800, 800))
    frame(anim)
end

gif(anim, "./assets/p_01_c.gif", fps=30)
#+end_src

#+RESULTS:
: Plots.AnimatedGif("/Users/ziro2173/personal/university/01_bachelor/02_semester/01_analysis/02_exercises/set_04/assets/p_01_c.gif")

* Problem 2 :DONE:
** Task
#+begin_quote
Let $f : \mathbb{R}^3 \to \mathbb{R}$ be defined by $f(x, y, z) = xyz$.

(a) Compute $\nabla f(x, y, z)$.

(b) Evaluate it at $(1, 1, 1)$ and determine the local (affine) linear approximation of $f$ in $(1, 1, 1)$.

(c) Plot $(x, y) \mapsto f(x, y, 1)$ in Julia.
#+end_quote

** Solution

*** (a)

Let $f : \mathbb{R}^3  \rightarrow \mathbb{R}, \quad f(x, y, z) = xyz$.

By definition, the partial derivatives are:

\begin{align*}
\partial_1 f(x, y, z) &= \lim_{h \rightarrow 0} \frac{f((x + h), y, z) - f(x, y, z)}{h} \\
\partial_2 f(x, y, z) &= \lim_{h \rightarrow 0} \frac{f(x, (y + h), z) - f(x, y, z)}{h} \\
\partial_3 f(x, y, z) &= \lim_{h \rightarrow 0} \frac{f(x, y, (z + h)) - f(x, y, z)}{h} \\
\end{align*}

Computing $\partial_1 f(x, y, z)$:

\begin{align*}
\partial_1 f(x, y, z) &= \lim_{h \rightarrow 0} \frac{f((x + h), y, z) - f(x, y, z)}{h} \\
                      &= \lim_{h \rightarrow 0} \frac{(x + h)yz - xyz}{h} \\
                      &= \lim_{h \rightarrow 0} \frac{hyz}{h} \\
                      &= yz \\
\end{align*}

By analogous computation, $\partial_2 f(x, y, z) = xz$, $\partial_3 f(x, y, z) = xy$.

Therefore:

$$\nabla f(x, y, z) = \begin{pmatrix} yz \\ xz \\ xy \end{pmatrix}$$

*** (b)

Evaluating the gradient at $p = (1, 1, 1)$:

$$\nabla f(1, 1, 1) = \begin{pmatrix} 1 \\ 1 \\ 1 \end{pmatrix}$$

The Fréchet derivative $Df(p) : \mathbb{R}^3 \rightarrow \mathbb{R}$ is the unique linear map satisfying:

$$\lim_{h \rightarrow 0} \frac{\| f(p + h) - f(p) - Df(p)(h) \|}{\| h \|} = 0$$

For $f : \mathbb{R}^3 \rightarrow \mathbb{R}$, this linear functional has the representation $Df(p)(h) = \nabla f(p)^{\top}h$, yielding the affine approximation:

$$L(x) = f(p) + \nabla f(p)^{\top} (x - p)$$

With $p = (1, 1, 1)$, and $f(1, 1, 1) = 1$:

\begin{align*}
L(x, y, z) &= 1 + \begin{pmatrix} 1 & 1 & 1 \end{pmatrix} \begin{pmatrix} x - 1 \\ y - 1 \\ z - 1 \end{pmatrix} \\
&= 1 + (x - 1) + (y - 1) + (z - 1) \\
&= x + y + z - 2 \\
\end{align*}

*** (c)

#+begin_src julia :results value :exports both :tangle julia/p_02.jl
using Plots

f(x, y) = x * y
L(x, y) = x + y - 1

xs = -6:0.05:6
ys = -6:0.05:6

anim = Animation()

for azimuth in 0:2:360
    surface(xs, ys, (x, y) -> f(x, y),
            alpha=0.8,
            colorbar=false,
            label="f(x,y)")
    surface!(xs, ys, (x, y) -> L(x, y),
             alpha=0.6,
             color=:reds,
             label="L(x,y)")
    scatter!([1], [1], [1],
             color=:black,
             markersize=4,
             label="(1,1,1)")
    plot!(xlabel="x", ylabel="y", zlabel="z",
          camera=(azimuth, 20),
          size=(800, 800))
    frame(anim)
end

gif(anim, "./assets/p_02_c.gif", fps=30)
#+end_src

#+RESULTS:
: Plots.AnimatedGif("/Users/ziro2173/personal/university/01_bachelor/02_semester/01_analysis/02_exercises/set_04/assets/p_02_c.gif")

* Problem 3 :DONE:
** Task
#+begin_quote
Let $f : \mathbb{R}^2 \to \mathbb{R}$ be defined by $f(x, y) = x^2 y + y^2$.

(a) Compute $\operatorname{grad} f(x, y)$.

(b) Determine the local (affine) linear approximation of $f$ at $(1, 1)$.
#+end_quote

** Solution

*** (a)

Let $f : \mathbb{R}^2 \rightarrow \mathbb{R}, \quad f(x, y) = x^2y + y^2$.

By definition, the partial derivatives are:


\begin{align*}
\partial_1 f(x, y) &= \lim_{h \rightarrow 0} \frac{f((x + h), y) - f(x, y)}{h} \\
\partial_2 f(x, y) &= \lim_{h \rightarrow 0} \frac{f(x, (y + h)) - f(x, y)}{h} \\
\end{align*}

Computing $\partial_1 f(x, y)$:

\begin{align*}
\partial_1 f(x, y) &= \lim_{h \rightarrow 0} \frac{((x + h)^2 y + y^2) - (x^2 y + y^2)}{h} \\
&= \lim_{h \rightarrow 0} \frac{2xyh + yh^2}{h} \\
&= \lim_{h \rightarrow 0} 2xy + yh \\
&= 2xy \\
\end{align*}

Computing $\partial_2 f(x, y)$:

\begin{align*}
\partial_2 f(x, y) &= \lim_{h \rightarrow 0} \frac{(x^2(y + h) + (y + h)^2) - (x^2 y + y^2)}{h} \\
&= \lim_{h \rightarrow 0} \frac{x^2 h + 2yh + h^2}{h} \\
&= \lim_{h \rightarrow 0} (x^2 + 2y + h) \\
&= x^2 + 2y \\
\end{align*}

Therefore:

$$\nabla f(x, y) = \begin{pmatrix} 2xy \\ x^2 + 2y \end{pmatrix}$$

*** (b)

Evaluating the gradient at $p = (1, 1)$:

$$\nabla f(1, 1) = \begin{pmatrix} 2 \\ 3 \end{pmatrix}$$

With $f(1, 1) = 1 + 1 = 2$:

\begin{align*}
L(x, y) &= 2 + \begin{pmatrix} 2 & 3 \end{pmatrix} \begin{pmatrix} x - 1 \\ y - 1 \end{pmatrix} \\
&= 2 + 2(x - 1) + 3(y - 1) \\
&= 2x + 3y - 3 \\
\end{align*}

* Problem 4
** Task
#+begin_quote
Let $f : \mathbb{R}^2 \to \mathbb{R}$ be defined by $f(x, y) = \frac{x}{x^2 + y^2 + 1}$.

(a) Plot $f$ in Julia.

(b) Guess its local extrema from your plot.
#+end_quote

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_04.jl
#+end_src

* Problem 5
** Task
#+begin_quote
Let $f : \mathbb{R}^2 \to \mathbb{R}$ and $g : \mathbb{R} \to \mathbb{R}$ be twice continuously differentiable such that $f(x, y) = g(x + y)$.

(a) Show that the Taylor polynomial of $g$ of order 1 centered at 0 and evaluated at $t = x + y$ coincides with the local (affine) linear approximation of $f$ in $(0, 0)$.

(b) The Hessian matrix of $f$ is
\[
Hf(x, y) = \begin{pmatrix} \partial_x \partial_x f(x, y) & \partial_x \partial_y f(x, y) \\ \partial_y \partial_x f(x, y) & \partial_y \partial_y f(x, y) \end{pmatrix}.
\]
Consider $g(t) = e^t$ and show that the Taylor polynomial of $g$ of order 2 centered at 0 and evaluated at $t = x + y$ coincides with
\[
F(x, y) = f(0, 0) + \operatorname{grad} f(0, 0) \begin{pmatrix} x \\ y \end{pmatrix} + \frac{1}{2} (x, y) \, Hf(0, 0) \begin{pmatrix} x \\ y \end{pmatrix}.
\]
#+end_quote

** Solution
