#+title: Ps 00
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-01-26>
#+lastmod: <2026-01-26 18:19>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t
#+startup: overview latexpreview inlineimages

* Problem 1
** Task
#+begin_quote
The p-q-formula of quadratic equations leads to
$x^{2}-2px+q=0$, $x_{1/2}=p\pm\sqrt{p^{2}-q}$.
Write a function $(p,q)\mapsto myPQnaive(p,q)$ that returns the zeros $x_{1}$ and $x_{2}$.
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_1.jl
#+end_src

* Problem 2
** Task
#+begin_quote
Visualize the following sequences
(a) $a_{n}:=(1+\frac{1}{n})^{n}$ for $n=1,2,\ldots$
(b) Plot in the same graph: $\frac{1}{2^{n}}$ and $\frac{1}{n^{2}}$ , for $n=1,2,\ldots$
(c) For $n\in\mathbb{N}$ put

$$b_n = \begin{cases}
1 \qquad \text{if n is a square} \\
\dfrac{1}{n+1} \qquad \text{otherwise}
\end{cases}$$

(d) Find and illustrate the largest element in the sequence $(x_{n})_{n\in\mathbb{N}}$, given by
$x_{n}=\frac{n^{2}}{2^{n}}, \qquad n\in\mathbb{N}$
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_2.jl
#+end_src

* Problem 3
** Task
#+begin_quote
Show that
(a) $lim_{n\rightarrow\infty}\frac{(-1)^{n}}{n}=0$ ,
(b) $lim_{n\rightarrow\infty}\frac{4n^{2}-2n+1}{n^{2}-n+6}=4$
In addition, visualize this behavior in Julia.
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_3.jl
#+end_src

* Problem 4
** Task
#+begin_quote
Show that the sequence $(a_{n})_{n\in\mathbb{N}}$, given by
$$a_{n}=n+n(-1)^{n}, \qquad n\in\mathbb{N}$$
is divergent. Check also in Julia.
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_4.jl
#+end_src

* Problem 5
** Task
#+begin_quote
Does the sequence $(x_{n})_{n\in\mathbb{N}}$ given by
$$x_{n}=\sqrt{n+4}-\sqrt{n}, \qquad n\in\mathbb{N}$$
converge? Prove your answer and illustrate in Julia.
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_5.jl
#+end_src
