#+title: Ps 01
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-01-26>
#+lastmod: <2026-01-26 13:12>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t
#+startup: overview latexpreview inlineimages

* Problem 1
** Task
#+begin_quote
Let $\Omega$ be any nonempty set. Define the function $d_{\Omega}:\Omega\times\Omega\rightarrow\mathbb{R}$ by
$$d_{\Omega}(x,y)=\begin{cases}0,& \text{if } x=y,\\ 1,& \text{if } x\ne y.\end{cases}$$
(1) Show that $d_{\Omega}$ is a metric on $\Omega$.
(2) Let $(x_{n})_{n\in\mathbb{N}}$ be a sequence in $\Omega$. Show that $(x_{n})_{n\in\mathbb{N}}$ converges in $(\Omega,d_{\Omega})$ if and only if it is eventually constant.
(... properly define what we mean by "eventually constant"...)
#+end_quote

** Notes

** Solution

* Problem 2
** Task
#+begin_quote
Consider $\mathbb{R}^{2}$ with the metric
$$d(x,y)=|x_{1}-y_{1}|+|x_{2}-y_{2}|, \quad x=(x_{1},x_{2})^{T}, y=(y_{1},y_{2})^{T}\in\mathbb{R}^{2}.$$
Consider the sequences $(a_{n})_{n\in\mathbb{N}},(b_{n})_{n\in\mathbb{N}}\subseteq\mathbb{R}^{2}$
$$a_{n}=\begin{pmatrix}\frac{1}{n+1}\\ 2+\frac{n}{n^{2}+1}\end{pmatrix}$$
$$b_{n}=\begin{pmatrix}\sqrt{4+n}-\sqrt{n}\\ (-1)^{n}\end{pmatrix}$$
and determine their behavior in regards to convergence in $(\mathbb{R}^{2},d)?$ In addition, investigate/illustrate also in Julia.
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_2.jl
#+end_src

* Problem 3
** Task
#+begin_quote
Consider the series
$$\sum_{n=1}^{\infty}\frac{(-1)^{n+1}}{n}.$$
(1) Show that it converges towards a limit $a\in\mathbb{R}$ Does it converge absolutely?
(2) Use Julia to guess the limit of $\sum_{k=0}^{\infty}\frac{a^{k}}{k!}$
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_3.jl
#+end_src

* Problem 4
** Task
#+begin_quote
We want to show that the sequence $(a_{n})_{n\in\mathbb{N}}=((1+\frac{1}{n+1})^{n+1})_{n\in\mathbb{N}}$ contains a convergent subsequence by verifying the following steps:
(1) Show that $(a_{n})_{n\in\mathbb{N}}$ is bounded. Hint for the upper bound: use the binomial theorem to verify
$$(1+\frac{1}{n})^{n}\le\sum_{k=0}^{n}\frac{1}{k!}, \quad n=1,2,....$$
(2) Argue now that $(a_{n})_{n\in\mathbb{N}}$ has a convergent subsequence. Make additionally numerical checks in Julia to collect some evidence that $(a_{n})_{n\in\mathbb{N}}$ is monoton and hence convergent.
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_4.jl
#+end_src
