#+title: Steup Vo Exam Prep
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-19>
#+lastmod: <2025-11-21 14:34>
#+options: num:t
#+startup: overview

* Weak Points
- [ ] Extremal elements in a poset
- [ ] Pigeonhole principle
- [ ] Infinite sets
- [ ] Cantor-Schröder-Bernstein theorem
- [ ] Complex numbers
- [ ] Rings and fields
- [ ] Polynomial Rings, Polar coordinates
- [ ] Sequences: Convergence, More sequences
- [ ] Vectors, Scalar product, Equation of lines and planes
- [ ] Exponential function

* Covered Topics
- [X] Logistics: Introduction to the course, Julia tutorials
- [X] Sets: Basic definitions, operations with sets
- [X] Propositional logic, Quantifiers
- [X] Induction
- [ ] Proofs
- [ ] Numbers: integer, rational, real, decimal representation
- [ ] Integers
- [ ] Congruences
- [ ] Counting: Binomial theorem, Inclusion-exclusion formula
- [ ] Relations
- [ ] Pigeonhole principle
- [ ] Functions
- [ ] Infinite sets
- [ ] Cantor-Schröder-Bernstein theorem
- [ ] Polynomials
- [ ] Complex numbers
- [ ] Rings and fields
- [ ] Polynomial Rings, Polar coordinates
- [ ] Sequences: Convergence, More sequences
- [ ] Vectors, Scalar product, Equation of lines and planes
- [ ] Exponential function

* Lectures Topics
Lecture 0.      Introduction to the course. Logistics. Julia.
Lecture 1.      Sets. Basic definitions and operations with sets.
Lectures 2-3.   Propositional logic. Quantifiers.
Lecture 4-5.    Induction.
Lecture 6.      Proofs.
Lecture 7.      Numbers: integer, rational, real. Decimal representation.
Lectures 8-9.   Numbers. Decimal representation. Integers.
Lecture 10.     Integers.
Lecture 11.     Integers. Congruences.
Lecture 12.     Julia tutorial.
Lecture 13.     Problem solving.
Lectures 14-15. Counting. Binomial theorem. Inclusion-exclusion formula.
Lectures 16-17. Relations.
Lecture 18.     Extremal elements in a poset.
Lecture 19.     Pigeonhole principle.
Lecture 20.     Functions. Lecture 21. Julia tutorial.
Lecture 22.     Functions (continuation).
Lectures 23-24. Even more functions.
Lecture 25.     Infinite sets.
Lectures 26-27. Infinite sets. Cantor-Schröder-Bernstein theorem.
Lecture 28.     Polynomials.
Lecture 29.     Polynomials-2.
Lecture 30.     Complex numbers.
Lecture 31.     Complex numbers-2.
Lecture 32.     Rings and fields.
Lecture 34.     Polynomial Rings. Polar coordinates.
Lecture 35.     Sequences. Convergence.
Lecture 36.     Sequences-2.
Lecture 37.     More sequences.
Lecture 38.     Vectors. Lecture 39. Sequences and the exponential function.
Lecture 40.     Vectors, scalar product, equation of lines and planes.
