#+title: Problem Set 10
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-04>
#+lastmod: <2025-11-10 18:39>
#+options: num:t
#+startup: overview

* NB?
Below, asnwering "finite" or "infinite" to "How many?" is not enough. We care whether it is ℵ0 or c, or somethinsg else.

- ℵ is an aleph number, that represents the cardinality of infinite sets.
- ℵ0 in our case stands for the cardinality of natural numbers set, which is the smallest along all aleph numbers sequence.

* Problem 1 [DONE] [CHECKED]
** Task
Prove that the set of finite bit strings is countable. (A bit string is a sequence of 0 and 1. like 0001101.)

** Notes
So I understand the set of finite of bit strings as:

{"0000", "0001", "0010", "0011", ...}

With each next element being a natural binary number (including 0).

Though, we should notice that problem states "sequence of 0 and 1", meaning that set lacks "0000" and "1111".


How to prove?

We can link each element of the bit strings set to a natural number, in our case it would look like:

We imagine each of the bits being the 2^n, where n is the index of the bit (it doesn't really matter if we count it from right or from left).

Thus, it would look like this:

|---+-----+-----+-----+-----|
|   | 2^3 | 2^2 | 2^1 | 2^0 |
|---+-----+-----+-----+-----|
| 1 |   0 |   0 |   0 |   1 |
|---+-----+-----+-----+-----|
| 2 |   0 |   0 |   1 |   0 |
|---+-----+-----+-----+-----|
| 3 |   0 |   0 |   1 |   1 |
|---+-----+-----+-----+-----|
0001 <-> 1
0010 <-> 2
0011 <-> 3
0100 <-> 4
...

And since a *countable set* is the set all of whose elements can be put into one-to-one relation with the natural numbers, means its elements can be listed in a sequence.

And since all binary strigns are repesentation of natural numbers in binary number system, meaning that each element of binary strings set is into one-to-one relation with a natural numbers.

** Solution
#+begin_quote Solution 1
*Proposition.* The set of finite bit strings is countable.

*Proof.* Let S be the set of all finite bit strings. For a string s ∈ S, |s| would be its length. For each n ∈ ℕ define:

        Sn = {s ∈ S : |s| = n},

the set of all bit strings:

        S = U(n=0)(Sn),

because every finite string has some finite length n.

Each Sn is finite: |Sn| = 2^n, since every bit position is binary.

So we can imagine S looking like:

        S = {"", "0", "1", "00", "01", "10", "11", "000", ...},

with

        S0 = {""}
        S1 = {"0", "1"}
        S2 = {"00", "01", "10", "11"}
        S3 = {...}

Thus, every level of Sn is finite, and we list them in order: 0,1,2,3,...
#+end_quote

#+begin_quote Solution 2
*Proposition.* The set of finite bit strings is countable.

*Proof.*

For n ∈ ℕ let Sn = {s ∈ S : |s| = n} be the set of all bit-strings of finite length n.

Clearly, S = U(n=0)(Sn)

For each n the set Sn is finite, in fact: |Sn| = 2^n.

Now:

        S0 = {""}
        S1 = {"0", "1"}
        S2 = {"00", "01", "10", "11"}
        S3 = {...}

Because each Sn is finite, concatenating these lists produces a single sequence that contains every element of S exaclty once; therefore, S is countable.
#+end_quote

* Problem 2 [SKIP]
** Task
Prove that the set of infinite bit strings has the same cardinality as ℝ.

** Notes
From what I can notice from the start is that in each level of the S, Sn repeats the binary numbers of the predecessor except of S0.

        S0 = {""}
        S1 = {"0", "1"}
        S2 = {"00", "01", "10", "11"}
        S3 = {...}

So in here we can see that S2's "00" equal to S1's "0" as a binary number (and "01" = "1" as well).

So we kind of repeat the previous numbers in each level.


** Solution
* Problem 3 [DONE] [CHECKED]
** Task
How many disjoints intervals (a,b) are in ℝ?

** Notes
- The rational numbers ℚ are countable and dense in ℝ.
- [[https://www.youtube.com/watch?v=z9UkzT2a3w8&t=119s][Video on rational dense in reals]]

** Solution
#+begin_quote
*Lemma.* ∃ x ∈ ℚ : a < x < b; a,b ∈ ℝ.

Let x = m/n : m ∈ ℤ, n ∈ ℕ. Hence, a < m/n < b; a,b ∈ ℝ.

Thus, an < m < bn (an, bn ∈ ℝ).

By Archimedean property, we pick n ∈ ℕ, where 1/n < b - a (or a < b - 1/n).
- This simply means to find n that would make the distance between a and b being greater than 1.

Next, take the smallest

m ∈ ℤ :   m - 1 <= na < m
                    a < m/n

        m - 1 <= na (substitute (b - 1/n) )
        m - 1 < n(b - 1/n)
        m - 1 < nb - 1
            m < nb
          m/n < b


Thus, a < m/n < b.

*Statement.* Number of disjoint open intervals in ℝ is either finite, or countably infinite, but not uncountable.

For each open interval of ℝ, there exists at least one x ∈ ℚ, such that x ∈ (a,b); a,b ∈ ℝ.

Because intervals are disjoint, different intervals can not contain the same rational number. Hence, the map

        F = {(a,b) : a,b ∈ ℝ; (a,b)∩Fn = ∅: n ∈ ℕ}

        I |-> q1 is injective from F to ℚ

An injective map into a countable set shows F is at most countable. Hence |F| <= ℵ0.
#+end_quote

* Problem 4 [NOT DONE] [CHECKED]
** Task
** Notes
** Solution
* Problem 5 [NOT DONE] [CHECKED]
** Task
How many non-intersecting circles can be drawn on a plane (circles may have an arbitrary radius)?

** Notes
** Solution
For two circles with the same center to intersect, its needed:

(x - a)^2 + (y - b)^2 + r^2 = (x - )^2 + (y - d)^2 + r'^2

* Problem 6 [NOT DONE] [CHECKED]
** Task
** Notes
** Solution
* Problem 7 [DONE]
** Task
Prove that the set of all functions f : ℕ -> {0,1} is uncountable.

** Notes
** Solution
#+begin_quote
*Proposition.* The set of all functions f : ℕ -> {0,1} is uncountable.

*Proof.*

Proof will be using Cantor's diagonal argument.

Each function f : ℕ -> {0,1} can be represented as infinite sequence of 0s and 1s. So the set of all such sequences is equivalent to the power set of natural numbers 2^ℕ.

1. By contradiction lets assume set of all functions, F is countable and thus can be represented as following:

   f1 = 0, 1, 0, 1, 0, 1, ...

   f2 = 1, 1, 1, 1, 1, 1, ...

   f3 = 0, 0, 0, 0, 0, 0, ...

   ...

2. Now we construct new function g : ℕ -> {0,1} that is not in that list. Rule: is the ith function in the list assigns the value 1 to the input i then the new function g assigns 0, and vice versa.

3. Therefore, this new function g does not match any function in the list, since it differs in ith place from the function fi. Contradiction. Thus set of all functions is uncountable.
#+end_quote
