#+title: Ch 02 Inner Product Spaces
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-04-27>
#+lastmod: <2026-05-04 12:45>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{mathtools}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t tags:nil
#+property: header-args :eval never-export
#+startup: overview latexpreview inlineimages

* Definition  2.01:  Inner product (aka. scalar product)

Let $E$ be an $\mathbb{K}$ vector space with $\mathbb{K} = \mathbb{R}$ or $\mathbb{C}$. An inner product on $E$ is a map $\langle \cdot, \cdot \rangle_E : E \times E \rightarrow \mathbb{K}$ satisfying for all $x, y, z \in E$ and $\lambda \in \mathbb{K}$:

1. linearity with respect to the first variable:

   $$\langle \lambda x + \mu y, z \rangle_E = \lambda \langle x, z \rangle_E + \mu \langle y, z \rangle_E, \quad \forall x, y, z \in E \text{ and } \lambda, \mu \in \mathbb{K}$$

2. conjugate symmetry:

   $$\langle x, y \rangle_E = \overline{\langle y, x \rangle}_E, \quad \forall x, y \in E$$

3. positive-definiteness:

   $$\langle x, x \rangle_E \ge 0, \quad \forall x \in E \quad \text{and} \quad \langle x, x \rangle_E = 0 \iff x = 0_E$$

* Lemma       2.02:  Norm induced by an inner product

Let $E$ be an $\mathbb{K}$ vector space with $\mathbb{K} = \mathbb{R}$ or $\mathbb{C}$ and $\langle \cdot, \cdot \rangle_E$ be an inner product over $E$. The map

$$\|\cdot\|_E : E \rightarrow \mathbb{R}, \quad x \mapsto \|x\|_E := \langle x, x \rangle_E^{1/2} \tag{2.1}$$

is a norm on $E$ which is called the norm induced by the inner product.

*Proof.*

We have to prove that the mapping defined in Eq. (2.1) satisfies all the properties of a norm. The only nontrivial point is the triangle inequality. For this, we let $x, y \in E$ and write

\begin{align*}
\|x + y\|^2 &= \langle x + y, x + y \rangle \\
&= \|x\|^2 + \langle x, y \rangle + \langle y, x \rangle + \|y\|^2 \\
&= \|x\|^2 + \langle x, y \rangle + \overline{\langle x, y \rangle} + \|y\|^2 \\
&= \|x\|^2 + 2\Re(\langle x, y \rangle) + \|y\|^2 \\
&\le \|x\|^2 + 2|\langle x, y \rangle| + \|y\|^2 \\
\end{align*}

By the Cauchy-Schwarz inequality,

$$\|x + y\|^2 \le \|x\|^2 + 2\|x\| \|y\| + \|y\|^2 = (\|x\| + \|y\|)^2$$

* Lemma       2.03:  Cauchy-Schwarz inequality

Let $E$ be an $\mathbb{K}$ vector space with $\mathbb{K} = \mathbb{R}$ or $\mathbb{C}$ and let $\langle \cdot, \cdot \rangle_E$ be defined as in Eq. (2.1). Then

$$|\langle x, y \rangle_E| \le \|x\|_E \|y\|_E,$$

and equality holds if and only if $x$ and $y$ are linearly dependent.

*Proof.*

We first start with the real case $\mathbb{K} = \mathbb{R}$. Let us define the map $p : \lambda \in \mathbb{R} \mapsto \|x + \lambda y\|^2$, which is nonnegative for every $\lambda \in \mathbb{R}$. Then

$$p(\lambda) = \|x + \lambda y\|^2 = \langle x + \lambda y, x + \lambda y \rangle = \|x\|^2 + 2\lambda \langle x, y \rangle + \lambda^2 \|y\|^2$$

Thus $p$ is a polynomial of degree two in $\lambda$. Since $p(\lambda) \ge 0$ for all $\lambda \in \mathbb{R}$, then its discriminant must be nonpositive, which translates into,

$$4|\langle x, y \rangle|^2 \le 4 \|x\|^2 \|y\|^2,$$

and yields the desired inequality. In addition, in case of an equality, this means that $|\langle x, y \rangle| = \|x\| \|y\|$. The discriminant is equal to zero, and $p$ has a unique root $\mu$. From the fact that $p(\mu) = 0$, it follows that $\|x + \mu y\| = 0$ which is equivalent to $x + \mu y$ (linear dependence).

We now consider the case $\mathbb{K} = \mathbb{C}$, and let $x, y \in E$. Since $\langle x, y \rangle \in \mathbb{C}$, it admits a polar decomposition of the form $\langle x, y \rangle = \rho e^{i\theta}$ with $\rho = |\langle x, y \rangle| \ge 0$ and $\theta \in \mathbb{R}$. We now let $x' = e^{i\theta} x$, and define for all $\lambda \in \mathbb{R}$

\begin{align*}
p(\lambda) &:= \|x' + \lambda y\|^2 \\
&= \langle x' + \lambda y, x' + \lambda y \rangle \tag{2.2} \\
&= \|x'\|^2 + \|\lambda y\|^2 + \langle x', \lambda y \rangle + \langle \lambda y, x' \rangle \\
&= \|x'\|^2 + \|\lambda y\|^2 + 2\Re(\langle x', \lambda y \rangle) \\
&= \|x\|^2 + \lambda^2 \|y\|^2 + 2\rho \lambda \tag{2.3} \\
\end{align*}

From Eq. (2.3), it follows that $p$ is a real-valued polynomial in $\lambda$. In addition, from Eq. (2.2) we have that $p(\lambda) \ge 0$ due to the nonnegativity of the inner product (see point 3 in /Definition 2.1/). Therefore, the discriminant of $p$ is nonpositive, and we conclude following the same lines as for the real case.

* Definition  2.04:  Inner-Product, Hilbert and Euclidean Spaces

1. inner-product space: An inner-product space is a normed space $(E, \|\cdot\|_E)$ where the norm is induced by an inner product $\langle \cdot, \cdot \rangle_E$. We usually denote it as $(E, \langle \cdot, \cdot \rangle_E)$.

2. Hilbert space: A Hilbert space is an inner-product space which is also complete (i.e. any Cauchy sequence of elements of $E$ converges in this norm to a limiting element which is also in $E$).

3. Euclidean space: A Euclidean space is a finite-dimensional, real inner-product space.

You will learn about completeness in your analysis, topology and functional analysis courses.

* Proposition 2.06:  Parallelogram Identity

Let $(E, \langle \cdot, \cdot \rangle_E)$ be a $\mathbb{K}$ inner-product vector space, and let $\|\cdot\|$ be its induced norm. Then

$$\|x + y\|^2 + \|x - y\|^2 = 2(\|x\|^2 + \|y\|^2), \quad \forall x, y \in E$$

* Lemma       2.07:  Polarization identity

Let $(E, \|\cdot\|)$ be a $\mathbb{K}$ vector space that satisfies the parallelogram identity. For a real vector space, define

$$\langle x, y \rangle := \frac{1}{4} ( \|x + y\|^2 - \|x - y\|^2 ) \tag{2.5}$$

and for a complex vector space define

$$\langle x, y \rangle := \frac{1}{4} \sum_{k=0}^{3} i^k \|x + i^k y\|^2$$

Then:

1. $\langle \cdot, \cdot \rangle$ is an inner product,

2. $\langle \cdot, \cdot \rangle$ is the only inner-product that induces the norm $\|\cdot\|_E$.

*Proof.*

We give the proof for the real case:

(i) It is easy to see that $\langle \cdot, \cdot \rangle$ is symmetric and positive, we proceed by checking the additivity and homogeneity.

*Additivity:* We first give a few identities that can be directly derived from the parallelogram identity (simply applying eq. (2.6) on the pairs $\{u, v\}$, $\{w, t\}$, ... etc.), let $x, y, z \in E$:

\begin{align*}
\begin{cases} u = x + z \\ v = y + z \end{cases} &\Rightarrow \|x + z\|^2 + \|y + z\|^2 = \frac{1}{2} ( \|x + y + 2z\|^2 + \|x - y\|^2 ) \tag{2.6} \\
\begin{cases} w = x - z \\ t = y - z \end{cases} &\Rightarrow \|x - z\|^2 + \|y - z\|^2 = \frac{1}{2} ( \|x + y - 2z\|^2 + \|x - y\|^2 ) \tag{2.7} \\
\begin{cases} r = x + y + z \\ s = z \end{cases} &\Rightarrow \|x + y + z\|^2 + \|z\|^2 = \frac{1}{2} ( \|x + y + 2z\|^2 + \|x + y\|^2 ) \tag{2.8} \\
\begin{cases} p = x + y - z \\ q = -z \end{cases} &\Rightarrow \|x + y - z\|^2 + \|z\|^2 = \frac{1}{2} ( \|x + y - 2z\|^2 + \|x + y\|^2 ) \tag{2.9} \\
\end{align*}

We then have

\begin{align*}
\langle x, z \rangle + \langle y, z \rangle &\stackrel{(2.5)}{=} \frac{1}{4} ( \|x + z\|^2 + \|y + z\|^2 - \|x - z\|^2 - \|y - z\|^2 ) \\
&\stackrel{(2.6),(2.7)}{=} \frac{1}{4} \left[ \frac{1}{2} ( \|x + y + 2z\|^2 + \|x - y\|^2 ) - \frac{1}{2} ( \|x + y - 2z\|^2 + \|x - y\|^2 ) \right] \\
&= \frac{1}{4} \left[ \frac{1}{2} \|x + y + 2z\|^2 - \frac{1}{2} \|x + y - 2z\|^2 \right] \\
&\stackrel{(2.8),(2.9)}{=} \frac{1}{4} \left[ ( \|x + y + z\|^2 + \|z\|^2 - \tfrac{1}{2} \|x + y\|^2 ) - ( \|x + y - z\|^2 + \|z\|^2 - \tfrac{1}{2} \|x + y\|^2 ) \right] \\
&= \frac{1}{4} ( \|x + y + z\|^2 - \|x + y - z\|^2 ) \\
&\stackrel{(2.5)}{=} \langle x + y, z \rangle \\
\end{align*}

which is the additivity we wish to prove.

*Homogeneity:* We wish to prove that

$$\langle \lambda x, y \rangle = \lambda \langle x, y \rangle, \quad \forall \lambda \in \mathbb{R}$$

Firstly, using the additivity of $\langle \cdot, \cdot \rangle$ that we have just proved, it is easy to see that for natural numbers:

$$\langle nx, y \rangle = n \langle x, y \rangle, \quad \forall n \in \mathbb{N} \tag{2.10}$$

For negative natural numbers $-n$, we have that

$$\langle -nx, y \rangle + n \langle x, y \rangle \stackrel{(2.10)}{=} \langle -nx, y \rangle + \langle nx, y \rangle \stackrel{(\text{Add.})}{=} \langle -nx + nx, y \rangle = \langle 0, y \rangle = 0$$

Or equivalently:

$$\langle -nx, y \rangle = -n \langle x, y \rangle, \quad \forall n \in \mathbb{N} \tag{2.11}$$

Equations (2.10) and (2.11) can be summarised as

$$\langle zx, y \rangle = z \langle x, y \rangle, \quad \forall z \in \mathbb{Z} \tag{2.12}$$

Now we turn to rational numbers. Let $q \in \mathbb{Q}$, then there exists $n, m \in \mathbb{Z}$ with $m \ne 0$ such that $q = n/m$. Therefore for $x, y \in E$ we get

$$m \langle qx, y \rangle \stackrel{(2.12)}{=} \langle m \cdot (qx), y \rangle \stackrel{(mq=n)}{=} \langle nx, y \rangle \stackrel{(2.12)}{=} n \langle x, y \rangle$$

Dividing both sides by $m$ we get

$$\langle qx, y \rangle = q \langle x, y \rangle, \quad \forall q \in \mathbb{Q} \tag{2.13}$$

Lastly, let $\lambda \in \mathbb{R}$, from analysis we know that there exists a sequence of rational numbers $(q_n)_{n=1}^{\infty} \subseteq \mathbb{Q}$ that converges to $\lambda$. For each $n \in \mathbb{N}$, thanks to (2.13) we have

$$\langle q_n x, y \rangle = q_n \langle x, y \rangle \tag{2.14}$$

On the right hand side we have

$$\lim_{n \rightarrow \infty} q_n \langle x, y \rangle = \lambda \langle x, y \rangle$$

The left hand side is trickier: we first expand the expression:

$$\langle q_n x, y \rangle = \frac{1}{4} \left[ \|q_n x + y\|^2 - \|q_n x - y\|^2 \right] \tag{2.15}$$

Using the reverse triangle inequality we see that

$$\left| \|q_n x + y\| - \|\lambda x + y\| \right| \le \|(q_n - \lambda) \cdot x\| = \underbrace{|q_n - \lambda|}_{\xrightarrow{n \rightarrow \infty} 0} \cdot \|x\| \xrightarrow{n \rightarrow \infty} 0 \quad \Rightarrow \quad \lim_{n \rightarrow \infty} \|q_n x + y\| = \|\lambda x + y\|,$$

similarly $\lim_{n \rightarrow \infty} \|q_n x - y\| = \|\lambda x - y\|$, putting this back to (2.15) we get

\begin{align*}
\lim_{n \rightarrow \infty} \langle q_n x, y \rangle &= \lim_{n \rightarrow \infty} \frac{1}{4} \left[ \|q_n x + y\|^2 - \|q_n x - y\|^2 \right] = \frac{1}{4} \left[ \lim_{n \rightarrow \infty} \|q_n x + y\|^2 - \lim_{n \rightarrow \infty} \|q_n x - y\|^2 \right] \\
&= \frac{1}{4} \left[ \|\lambda x + y\|^2 - \|\lambda x - y\|^2 \right] = \langle \lambda x, y \rangle \\
\end{align*}

Going back to (2.14) we have that

$$\langle \lambda x, y \rangle \xleftarrow{n \rightarrow \infty} \langle q_n x, y \rangle = q_n \langle x, y \rangle \xrightarrow{n \rightarrow \infty} \lambda \langle x, y \rangle \stackrel{(\text{Uniqueness of limit})}{\Longrightarrow} \langle \lambda x, y \rangle = \lambda \langle x, y \rangle$$

Which is the homogeneity condition that we wanted to prove.

(ii) We first prove that the inner-produc[?] (2.5) induces the norm. This is true since we have

$$\langle x, x \rangle \stackrel{(2.5)}{=} \frac{1}{4} ( \|x + x\|^2 + \|x - x\|^2 ) = \frac{1}{4} ( \|2x\|^2 + \|0\|^2 ) = \frac{1}{4} ( 4 \|x\|^2 ) = \|x\|^2$$

We now show that (2.5) is the unique product that induces the norm. Let $\omega(\cdot, \cdot) : E \times E$ be an arbitrary inner product on $E$ that satisfies

$$\|x\|^2 = \omega(x, x), \forall x \in E \tag{2.16}$$

For simplicity, we assume that $\mathbb{K} = \mathbb{R}$ so that $\omega$ is symmetric (for $\mathbb{K} = \mathbb{C}$ we need to minimally adapt the proof for $\omega$ being conjugate symmetric). Then for $x, y \in E$, from (2.16) we see that

\begin{align*}
\|x + y\|^2 &= \omega(x + y, x + y) = \omega(x, x) + \omega(y, y) + 2\omega(x, y) = \|x\|^2 + \|y\|^2 + 2\omega(x, y), \quad \text{and} \\
\|x - y\|^2 &= \omega(x - y, x - y) = \omega(x, x) + \omega(y, y) - 2\omega(x, y) = \|x\|^2 + \|y\|^2 - 2\omega(x, y) \\
\end{align*}

Combining both lines we see that

$$\|x + y\|^2 - \|x - y\|^2 = 4\omega(x, y) \quad \iff \quad \omega(x, y) = \frac{1}{4} ( \|x + y\|^2 - \|x - y\|^2 ) \stackrel{(2.5)}{=} \langle x, y \rangle$$

We have thus proven that any inner product on $E$ that satisfies the property (2.16) is necessarily equal to $\langle \cdot, \cdot \rangle$. Or in other words, $\langle \cdot, \cdot \rangle$ is the unique inner product that has said property.

For the case where $\mathbb{K} = \mathbb{C}$, the lemma can be proved in analogous manner, although with more complex (no pun intended) calculations.

* Theorem     2.08:  Jordan von-Neumann

Let $\|\cdot\|$ be a norm on a $\mathbb{K}$ vector space $E$. Then we have the equivalence:

$$\|\cdot\| \text{ is induced by an inner product} \iff \|\cdot\| \text{ satisfies the parallelogram identity}$$

*Proof.*

The direction $\Leftarrow$ holds thanks to the parallelogram identity. The direction $\Rightarrow$ holds by the polarization identity, which gives us an explicit construction of the inner-product inducing the given norm.

* Definition  2.09:  Angle between 2 vectors

The angle $\alpha \in \left[ 0, \pi \right]$ between two vectors $x, y \in E$ is defined through its cosine as

$$\cos(\alpha) := \frac{\langle x, y \rangle}{\|x\| \|y\|}$$

This definition makes sense since, by the Cauchy-Schwarz inequality, $\left| \frac{\langle x, y \rangle}{\|x\| \|y\|} \right| \le 1$, therefore we can interpret this quantity as the cosine of an angle. We may note that we recover the classical definition of angle between vectors in $\mathbb{R}^n$.

Interesting things happen when the vectors 'become perpendicular' in the sense that $\alpha = \pi / 2$. This happens when $\langle x, y \rangle = 0$ (assuming that $x, y \ne 0$). This is gives raise to the general notion of orthonogonality and orthonormality, which are key concepts in inner-product spaces.

* Definition  2.10:  Orthogonality and Orthonormality

Let $(E, \langle \cdot, \cdot \rangle_E)$ be a $\mathbb{K}$ inner-product vector space with $\mathbb{K} = \mathbb{R}$ or $\mathbb{C}$, and let $W$ and $T$ be two subspaces of $E$.

1. orthogonal vectors: We say that two vectors $x, y \in E$ are orthogonal if $\langle x, y \rangle = 0$, and we often denote this as $x \perp y$.

2. vector orthogonal to subspace: We say that $x$ is orthogonal to $W$ ($x \perp W$) if $\langle x, w \rangle = 0$ for all $w \in W$.

3. orthogonal subspaces: We say that $W$ and $T$ are orthogonal ($W \perp T$) if $\langle w, t \rangle = 0$ for all $w \in W$ and $t \in T$.

4. orthonormal set: We say that a set of vectors $\{v_1, \ldots, v_n\} \subseteq E$ is orthonormal if $\langle v_i, v_j \rangle = \delta_{ij}$.

* Definition  2.11:  Orthogonal and orthonormal basis

Let $E$ be an $n$-dimensional Euclidean space and $X = \{e_1, \ldots, e_n\}$ be a basis of $E$. We say that $X$ is an orthogonal basis if

$$\langle e_i, e_j \rangle = 0, \quad \forall i \ne j.$$

The basis is said to be orthonormal if

$$\langle e_i, e_j \rangle = \delta_{ij}, \quad \forall 1 \le i, j \le n.$$

* Proposition 2.12:  Coordinates in an orthonormal basis

Let $E$ be a Euclidean space and $\mathcal{E}_n = \{e_1, \ldots, e_n\}$ an orthonormal basis of $E$. Then

$$x = \sum_{i=1}^{n} \langle x, e_i \rangle e_i, \quad \text{and} \quad \|x\|^2 = \sum_{i=1}^{n} |\langle x, e_i \rangle|^2.$$

*Proof.*

Since $\mathcal{E}_n$ is a basis, there exist $(c_1, \ldots, c_n) \in \mathbb{R}^n$ such that $x = \sum_{i=1}^{n} c_i e_i$. Taking the inner product with $e_j$ yields $c_j = \langle x, e_j \rangle$ for all $1 \le j \le n$. To prove the formula with the norm, we simply write $\|x\|^2 = \langle x, x \rangle$ and develop the sum using that $x = \sum_{i=1}^{n} \langle x, e_i \rangle e_i$.

* Theorem     2.13:  Gram-Schmidt orthonormalization

Any euclidean space $E$ has an orthonormal basis.

*Proof.*

Let $\mathcal{X} = \{x_1, \ldots, x_n\}$ be a basis of $E$. We define by induction the following vectors,

\begin{align*}
e_1 &:= \frac{x_1}{\|x_1\|} \\
e_i &:= \frac{x_i - \sum_{j=1}^{i-1} \langle x_i, e_j \rangle e_j}{\|x_i - \sum_{j=1}^{i-1} \langle x_i, e_j \rangle e_j\|}, \quad 2 \le i \le n.
\end{align*}

Our goal is to prove that $\mathcal{E}_n = \{e_1, \ldots, e_n\}$ is an orthonormal basis of $E$. For this, we start by noticing that each $e_i \in \text{span}\{x_1, \ldots, x_i\}$. This implies that for every $1 < i \le n$, $\|x_i - \sum_{j=1}^{i-1} \langle x_i, e_j \rangle e_j\| \ne 0$ given that $\sum_{j=1}^{i-1} \langle x_i, e_j \rangle e_j \in \text{span}\{x_1, \ldots, x_{i-1}\}$. This shows that definition (2.17) of the $e_i$ is well-posed in the sense that the denominator does not vanish.

We are now going to show by induction that $\mathcal{E}_i$ is an orthonormal set for $1 \le i \le n$. We start with the case $i = 1$, for which it directly follows by the definition of $e_1$ that $\langle e_1, e_1 \rangle = \langle x_1, x_1 \rangle / \|x_1\|^2 = 1$. For the inductive step, let $1 < i \le n$, and assume that $\mathcal{E}_{i-1}$ is an orthonormal set. By the definition of $e_i$, we have that

$$\langle e_i, e_i \rangle = \frac{\langle x_i - \sum_{j=1}^{i-1} \langle x_i, e_j \rangle e_j, x_i - \sum_{j=1}^{i-1} \langle x_i, e_j \rangle e_j \rangle}{\|x_i - \sum_{j=1}^{i-1} \langle x_i, e_j \rangle e_j\|^2} = 1.$$

For any $1 \le k < i$,

\begin{align*}
\langle e_i, e_k \rangle &= \frac{\langle x_i, e_k \rangle - \sum_{j=1}^{i-1} \langle x_i, e_j \rangle \langle e_j, e_k \rangle}{\|x_i - \sum_{j=1}^{i-1} \langle x_i, e_j \rangle e_j\|} \\
&= \frac{\langle x_i, e_k \rangle - \sum_{j=1}^{i-1} \langle x_i, e_j \rangle \delta_{j,k}}{\|x_i - \sum_{j=1}^{i-1} \langle x_i, e_j \rangle e_j\|} \quad \text{(induction hypothesis: } \mathcal{E}_{i-1} \text{ is an orthonormal set)} \\
&= \frac{\langle x_i, e_k \rangle - \langle x_i, e_k \rangle}{\|x_i - \sum_{j=1}^{i-1} \langle x_i, e_j \rangle e_j\|} \\
&= 0.
\end{align*}

This allows us to conclude that $\mathcal{E}_n$ is an orthonormal set. To show that $\mathcal{E}_n$ is a basis of $E$, it suffices to show that it is a linearly independent family. Let $\lambda_1, \ldots, \lambda_n \in \mathbb{K}$ be such that $\lambda_1 e_1 + \lambda_n e_n = 0$. Multiplying scalarly by $e_i$ and using that $\mathcal{E}_n$ is an orthonormal set, we deduce that $\lambda_i = 0$ for $1 \le i \le n$. Thus $\mathcal{E}_n$ is linearly independent, and therefore a basis of $E$.

* Definition  2.14:  Orthogonal complement

Let $E$ be an inner-product space and $F \subseteq E$ a subspace of $E$. We denote

$$F^\perp := \{x \in E : \langle x, f \rangle = 0, \forall f \in F\}$$

the orthogonal complement of $F$.

* Proposition 2.15:  Properties of the orthogonal complement

Let $F$ be a subspace of a euclidean space $E$. Then:

1. $E = \{0\}^\perp$ and $E^\perp = \{0\}$.

2. $F^\perp$ is a nonempty subspace of $E$.

3. $E = F \oplus F^\perp$.

4. $(F^\perp)^\perp = F$.

*Proof.*

1. To prove that $E^\perp = \{0\}$, we remark that if $x \in E^\perp$, then $\|x\| = 0$, thus $x = 0$.

2. $F^\perp$ is non empty since $0 \in F^\perp$. The fact that $F^\perp$ is a subspace can easily be verified and is left as an exercise.

3. Suppose that the dimension of $F$ is $p$ with $0 \le p \le n$. If $p = 0$ or $p = n$, the statement is proven thanks to point (i). Let us now deal with the case $1 \le p < n$. To prove the first statement, we consider a basis of $F$, to which we add linearly independent vectors to obtain a basis of $E$. We next orthonormalize the basis by Gram-Schmidt orthonormalization. This gives us an orthonormal basis $\mathcal{E} = \{e_1, \ldots, e_n\}$ where the first $p$ vectors form a basis of $F$. By using Eq. (2.18), we can then show that

   $$F^\perp = \text{span}\{e_{p+1}, \ldots, e_n\}.$$

   We thus conclude that $F = F \oplus F^\perp$ and $\dim(E) = \dim(F) + \dim(F^\perp)$.

4. We start by observing that $\dim((F^\perp)^\perp) = \dim(E) - \dim(F^\perp)$. Then, we easily verify that $F \subseteq (F^\perp)^\perp$, which leads to the conclusion that $(F^\perp)^\perp = F$.

* Definition  2.16:  Orthogonal projection

Let $E = F \oplus F^\perp$ for a subspace $F \subseteq E$. The mapping

\begin{align*}
P_F = P_{F \oplus F^\perp} &: E \rightarrow F \subseteq E \\
x = x_F + x_{F^\perp} &\mapsto x_F
\end{align*}

is called the orthogonal projector onto $F$, and $x_F$ is called the orthogonal projection of $x \in E$ onto $F$.

* Proposition 2.18:  Properties of the orthogonal projection

Let $F$ be a subspace of a euclidean vector space $E$. Then:

1. $P_F$ is the projection onto $F$ in the sense that $\text{im}\, P_F = F$ and $P_F \circ P_F = P_F$.

2. Orthogonality: For all $x \in E$ it holds that

   $$x - P_F(x) \perp F$$

   $$x = P_F(x) + P_{F^\perp}(x)$$

3. Contraction: For all $x \in E$, $\|P_f(x)\| \le \|x\|$.

4. If $f \in \mathcal{L}(E)$ is a linear map such that $f = f \circ f$ and $\text{im}(f) \perp \text{ker}(f)$, then $f$ is the orthogonal projection onto $\text{im}(f)$.

5. Minimizing property: For all $x \in E$,

   $$\|x - P_F(x)\| = \min_{f \in F} \|x - f\|.$$

*Proof.*

1. This property simply follows from the definition of the orthogonal projector $P_F$ as the subspace projection $P_{F \oplus F^\perp}$.

2. Every $x \in E = F \oplus F^\perp$ can be uniquely decomposed into $x = x_F + x_{F^\perp}$, and by the definition of $P_F$ and $P_{F^\perp}$, $x_F = P_F(x)$ and $x_{F^\perp} = P_{F^\perp}(x)$. Thus $x = P_F(x) + P_{F^\perp}(x)$. Therefore $x - P_F(x) \in F^\perp$, which is equivalent to $x - P_F(x) \perp F$.

3. For every $x \in E$,

   $$\|x\|^2 = \langle x, x \rangle = \langle P_F(x) + P_{F^\perp}(x), P_F(x) + P_{F^\perp}(x) \rangle = \|P_F(x)\|^2 + \|P_{F^\perp}(x)\|^2 \ge \|P_F(x)\|^2.$$

4. We start by proving that $E = \text{im}(p) + \text{ker}(p)$. Every $x \in E$ can be written as $x = p(x) + x - p(x)$. Since $p(x - p(x)) = 0$, it follows that $x - p(x) \in \text{ker}(p)$. In addition, the decomposition of $x$ into $p(x) \in \text{im}(f)$ and $x - p(x) \in \text{ker}(f)$ is unique because if $x = a + b$ with $b \in \text{ker}(p)$, then $p(x) = p(a) = a$. We conclude by the definition of orthogonal projection.

5. For any $f \in F$, it holds that

   \begin{align*}
   \|x - f\|^2 &= \|x - P_F(x) + P_F(x) - f\|^2 \\
   &= \|x - P_F(x)\|^2 + \|P_F(x) - f\|^2 \\
   &\ge \|x - P_F(x)\|^2.
   \end{align*}

   Therefore $\|x - P_F(x)\| = \min_{f \in F} \|x - f\|$.

* Proposition 2.19:  Coordinates of the orthogonal projection

Let $(E, \omega)$ with $\dim E = n$ be a finite dimensional inner product space with inner product $\omega$. Let $F \subseteq E$ be a subspace of $E$ spanned by a basis $\mathcal{F} = \{f_1, \ldots, f_p\}$. Then the coordinates of the orthogonal projection $P_F : E \rightarrow F$ in $\mathcal{F}$ are given by

$$[P_F(u)]^{\mathcal{F}} = [\omega]_{\mathcal{F}\mathcal{F}}^{-1}\, q, \quad \text{with} \quad q = (\omega(u, f_i))_{i=1}^{p}.$$

*Proof.*

Let $u \in E$. The orthogonal projection of $u$ onto $F$ can be written as

$$P_F(u) = \sum_{i=1}^{p} [P_F(u)]_i^{\mathcal{F}} f_i.$$

For shorthand notation, in this proof we write $\lambda = [P_F(u)]^{\mathcal{F}}$. Since $u - P_F(u) \perp F$, it follows that

$$\omega(u - P_F(u), f_i) = 0, \quad 1 \le i \le p.$$

Inserting Eq. (2.21) into Eq. (2.22), and rearranging, we are lead to the system of equations

$$[\omega]_{\mathcal{F}\mathcal{F}}\, \lambda = q.$$

Since the $f_i$ are linearly independent, then $[\omega]_{\mathcal{F}\mathcal{F}}$ is invertible, and this leads to Eq. (2.20).

* Definition  2.20:  The supervised learning problem

Given an unknown function $f : X \rightarrow Y$ between spaces $X$ and $Y$, find a good approximation of $f$ using only a dataset of $N$ samples:

$$\mathcal{D} = \left\{ (x_i, y_i) \right\}_{i=1}^N \quad \text{with} \quad y_i = f(x_i) \quad \text{for all } i = 1 \ldots N.$$

The space $X$ is also called the /feature space/ and its elements are referred to as feature vectors. The space $Y$ is also called the /label space/ and its elements are referred to as labels. We denote the dimensions of these spaces by $d = \dim X$ and $q = \dim Y$.

The general approach to solving this problem consists of three main steps.

1. Choose a model function $F : X \times W \rightarrow Y$ parametrized by a parameter space $W$ ($W$ stands for weights, since that is how parameters are often referred to). The goal is to find an appropriate value $w^* \in W$ for the parameters such that $F(x; w^*)$ is as close as possible to $f(x)$ for every $x \in X$.

2. We need to choose a measure of quality for the model's output, so we need to choose a /loss function/ $\ell : Y \times Y \rightarrow \mathbb{R}$, where $\ell(y_1, y_2)$ indicates 'how different' $y_1$ and $y_2$ are. With this choice, $\ell(F(x; w^*), f(x))$ will indicate how close $F(x; w^*)$ and $f(x)$ are. Of course, since we only have the samples $\mathcal{D}$, we can only evaluate the loss for the $x$ in the dataset $\mathcal{D}$.

3. Based on the dataset and the loss function $\ell$, choose $w \in W$ so that $F(\,\cdot\,; w)$ is the 'best' possible approximation of the target function $f$. One of the most common strategies is to minimize the loss on the dataset, i.e. to search for

   $$w^* = \arg\min_{w \in W} \sum_{i=1}^N \ell(F(x_i; w), y_i). \qquad (2.23)$$

* Theorem     2.21:  Riesz Theorem

Let $(E, \langle \cdot, \cdot \rangle_E)$ be a Hilbert space in $\mathbb{K} = \mathbb{R}$ or $\mathbb{C}$. For every $\ell \in E'$, there exists exactly one vector $u$ such that

$$\ell(x) = \langle x, u \rangle_E, \quad \forall x \in E,$$

and

$$\|\ell\|_{op} = \|u\|_E.$$

We say that $u$ is the /Riesz representer/ of $\ell$ in $(E, \langle \cdot, \cdot \rangle_E)$.

Importantly, for complex inner-product spaces, $u$ is always located in the antilinear coordinate of the inner-product.

*Proof.*

If $\ell = 0$, then $u = 0$ works and is unique, and $\|\ell\|_{op} = 0 = \|u\|_E$. Assume henceforth that $\ell \ne 0$.

Let $K := \ker \ell = \{x \in E : \ell(x) = 0\}$. Then $K$ is a subspace of $E$ and, since $\ell \ne 0$, we have $K \ne E$. In a finite-dimensional inner-product space,

$$E = K \oplus K^{\perp}.$$

Pick $v \in K^{\perp}$ with $v \ne 0$ (possible because $K^{\perp} \ne \{0\}$). Since $v \notin K$, we have $\ell(v) \ne 0$.

*Existence:* For our fixed $v \in K^{\perp}$, define

$$u := \frac{\overline{\ell(v)}}{\|v\|_E^2} v \quad (\text{overline denotes complex conjugation; in } \mathbb{R} \text{ it is the identity}).$$

We claim that $\ell(x) = \langle x, u \rangle_E$ for all $x \in E$. Indeed, for any $x \in E$ write uniquely $x = y + \alpha v$ with $y \in K$ and $\alpha \in \mathbb{K}$. Then $\ell(y) = 0$ and hence

$$\ell(x) = \ell(y) + \alpha \ell(v) = \alpha \ell(v).$$

On the other hand, since $y \perp v$, and using that the inner product is conjugate-linear in the second argument,

$$\langle x, u \rangle_E = \left\langle y + \alpha v, \frac{\overline{\ell(v)}}{\|v\|_E^2} v \right\rangle_E = \alpha \, \overline{\left(\frac{\overline{\ell(v)}}{\|v\|_E^2}\right)} \langle v, v \rangle_E = \alpha \, \frac{\ell(v)}{\|v\|_E^2} \|v\|_E^2 = \alpha \ell(v),$$

so indeed $\ell(x) = \langle x, u \rangle_E$ for all $x \in E$.

*Uniqueness:* Suppose $u_1, u_2 \in E$ satisfy $\ell(x) = \langle x, u_1 \rangle_E = \langle x, u_2 \rangle_E$ for all $x$. Then $\langle x, u_1 - u_2 \rangle_E = 0$ for all $x \in E$. Taking $x = u_1 - u_2$ gives $\|u_1 - u_2\|_E^2 = 0$, hence $u_1 = u_2$.

*Norm identity:* For any $x \in E$, by Cauchy–Schwarz,

$$|\ell(x)| = |\langle x, u \rangle_E| \le \|x\|_E \|u\|_E.$$

Taking the supremum over $x \ne 0$ yields $\|\ell\|_{op} \le \|u\|_E$. Conversely, choose $x = u$. Then

$$\|\ell\|_{op} \ge \frac{|\ell(u)|}{\|u\|_E} = \frac{|\langle u, u \rangle_E|}{\|u\|_E} = \|u\|_E.$$

Therefore $\|\ell\|_{op} = \|u\|_E$, and concludes the proof.

* Theorem     2.22:  Adjoint Operator

Let $(E, \langle \cdot, \cdot \rangle_E)$ and $(F, \langle \cdot, \cdot \rangle_F)$ be inner-product spaces over $\mathbb{K} = \mathbb{R}$ or $\mathbb{C}$, and let $T \in \mathcal{B}(E, F)$ be a /bounded/ linear map. There exists a unique bounded linear map $T^* : F \rightarrow E$, called the /adjoint operator/ of $T$, which is such that

$$\langle T(x), y \rangle_F = \langle x, T^*(y) \rangle_E \qquad \text{for all } x \in E, y \in F. \qquad (2.27)$$

Furthermore, it holds that $\|T\|_{op} = \|T^*\|_{op}$.

*Proof.*

Fix $y \in F$, and define the linear functional $f_y(x) := \langle T(x), y \rangle_F$ for all $x \in E$. Since $T$ is a bounded linear operator, by the Cauchy-Schwarz inequality we have

$$|f_y(x)| = |\langle T(x), y \rangle_F| \le \|T(x)\|_F \|y\|_F \le \underbrace{\|T\|_{op} \|y\|_F}_{=C<+\infty} \|x\|_E,$$

which shows that $f_y : E \rightarrow \mathbb{K}$ is bounded. Therefore, $f_y \in E'$ (the continuous dual of $E$, see Eq. (1.13)). By the Riesz representation theorem, there exists a unique $z \in E$ such that $f_y(x) = \langle x, z \rangle_E$. Therefore, for each $y \in F$, there exists a unique $z \in E$ such that $\langle x, z \rangle_E = \langle T(x), y \rangle_F$. Now, define $T^* : F \rightarrow E$ the mapping $T^*(y) = z$ for all $y \in F$. Thus,

$$\langle x, T^*(y) \rangle_E = \langle T(x), y \rangle_F, \quad \forall x \in E, y \in F.$$

The uniqueness of $T^*$ follows again from the /Riesz representation theorem/. Suppose that there exists $T_1^*, T_2^* : F \rightarrow E$ with the adjoint property (2.27). This implies that $\langle (T_1^* - T_2^*)(x), y \rangle_F = 0$ for all $x, y$ which, in turn, implies that $T_1^* - T_2^* = 0$.

* Lemma       2.23:  Matrix representation

Let $(E, \langle \cdot, \cdot \rangle_E)$ and $(F, \langle \cdot, \cdot \rangle_F)$ be two inner-product spaces of finite dimension $p$ and $n \in \mathbb{N}$ respectively. Let $\mathcal{E}$ and $\mathcal{F}$ be bases of $E$ and $F$, and let $T \in \mathcal{L}(E, F)$ be a linear map. Then,

$$[T^*]_{\mathcal{F}}^{\mathcal{E}} = G_E^{-1} ([T]_{\mathcal{E}}^{\mathcal{F}})^H G_F \in \mathbb{K}^{p \times n},$$

where

$$G_E := (\langle e_i, e_j \rangle_E)_{1 \le i, j \le p} \in \mathbb{K}^{p \times p}, \qquad G_F := (\langle f_i, f_j \rangle_F)_{1 \le i, j \le n} \in \mathbb{K}^{n \times n},$$

are the so-called Gram-matrices of the vectors of $\mathcal{E}$ and $\mathcal{F}$ respectively. In particular, when $\mathcal{E}$ and $\mathcal{F}$ are orthonormal bases, then

$$[T^*]_{\mathcal{F}}^{\mathcal{E}} = ([T]_{\mathcal{E}}^{\mathcal{F}})^H \in \mathbb{K}^{p \times n}.$$

*Proof.*

We will prove the claim only for the cases when $\mathcal{E}$ and $\mathcal{F}$ are orthonormal bases. In this case, by /Proposition 2.12/, we have that

$$T(e_i) = \sum_{j=1}^n \langle T(e_i), f_j \rangle f_j, \quad 1 \le i \le p$$

$$T^*(f_j) = \sum_{i=1}^p \langle T^*(f_j), e_i \rangle\, e_i, \quad 1 \le j \le n.$$

Therefore

$$[T]_{\mathcal{E}}^{\mathcal{F}} = \left([T(e_1)]^{\mathcal{F}} \mid \ldots \mid [T(e_p)]^{\mathcal{F}}\right) = (\langle T(e_i), f_j \rangle_F)_{\substack{1 \le i \le p \\ 1 \le j \le n}},$$

and

\begin{align*}
[T^*]_{\mathcal{F}}^{\mathcal{E}} &= \left([T^*(f_1)]^{\mathcal{E}} \mid \ldots \mid [T^*(f_n)]^{\mathcal{E}}\right) \\
&= (\langle T^*(f_i), e_j \rangle_E)_{\substack{1 \le i \le n \\ 1 \le j \le p}} \\
&= \left(\overline{\langle e_j, T^*(f_i) \rangle_E}\right)_{\substack{1 \le i \le n \\ 1 \le j \le p}} \quad \text{(by conjugate symmetry)} \\
&= \left(\overline{\langle T(e_j), f_i \rangle_F}\right)_{\substack{1 \le i \le n \\ 1 \le j \le p}} \quad \text{(by Eq. (2.27))} \\
&= ([T]_{\mathcal{E}}^{\mathcal{F}})^H.
\end{align*}

* Theorem     2.24:  Unitary operators

Let $T \in \mathcal{B}(E, E)$. Then the following properties are equivalent:

1. $TT^* = T^*T = \mathrm{Id}_E$,

2. $T$ is bijective and $T^{-1} = T^*$.

3. $T$ is surjective and it preserves inner products:

   $$\langle T(x), T(y) \rangle_E = \langle x, y \rangle_E, \quad \forall x, y \in E.$$

4. $T$ is surjective and it preserves the norm:

   $$\|T(x)\|_E = \|x\|_E, \quad \forall x \in E.$$

5. $[T]_{\mathcal{E}}^{\mathcal{E}}$ is unitary ($\mathbb{K} = \mathbb{C}$) or orthogonal ($\mathbb{K} = \mathbb{R}$) if $E$ is finite dimensional and $\mathcal{E} = \{e_i\}_{i=1}^n$ is an orthonormal basis.

If one of these properties hold, we say that $T$ is a /unitary operator/ ($\mathbb{K} = \mathbb{C}$) or /orthogonal operator/ ($\mathbb{K} = \mathbb{R}$).

*Proof.*

- ($1 \Rightarrow 2$) Suppose $x \ne 0 \in \ker(T)$. Then $T^*T(x) = 0_E$ which implies that $x = 0_E$. This is a contradiction which implies that $\ker(T) = \{0_E\}$. Therefore $T$ is injective.

  We now show that $T$ is surjective. Let $y \in E$, and choose $x = T^*(y)$. We then have $T(x) = (TT^*)(y) = y$ which shows that $T$ is surjective.

  It follows that $T$ is bijective, thus invertible, and from the identity $TT^* = T^*T = \mathrm{Id}_E$ we deduce that $T^{-1} = T^*$.

- ($2 \Rightarrow 1$) Trivial.

- ($1 \Rightarrow 3$) Let $x, y \in E$. By property (2.27) of the adjoint,

  $$\langle T(x), T(y) \rangle_E = \langle x, (T^*T)(y) \rangle_E = \langle x, y \rangle_E.$$

  In addition, we already proved earlier that having $TT^* = \mathrm{Id}_E$ implies that $T$ is surjective.

- ($3 \Rightarrow 1$) It holds that $\langle x, (T^*T - \mathrm{Id})(y) \rangle_E = 0$ for all $x \in E$. Therefore $(T^*T - \mathrm{Id})(y) = 0$ for all $y \in E$, which implies that $T^*T = \mathrm{Id}_E$. This also implies that $T$ is injective as shown earlier. In addition, we are assuming that $T$ is also surjective. Therefore $T$ is bijective, thus invertible. From the fact that $T^*T = \mathrm{Id}$ we deduce that $T^{-1} = T^*$ and therefore $TT^* = \mathrm{Id}_E$, which concludes the proof.

- ($3 \Rightarrow 4$) Trivial.

- ($4 \Rightarrow 3$) Let $x, y \in E$ and suppose that $E$ is a real vector space. By the polarization identity (2.5),

  $$\langle T(x), T(y) \rangle = \frac{1}{4}\left(\|T(x) + T(y)\|_E^2 - \|T(x) - T(y)\|_E^2\right) = \frac{1}{4}\left(\|x + y\|_E^2 - \|x - y\|_E^2\right) = \langle x, y \rangle_E.$$

- ($1 \Leftrightarrow 5$) To prove this equivalence, we essentially need to use that $[T^*]_{\mathcal{E}}^{\mathcal{E}} = ([T]_{\mathcal{E}}^{\mathcal{E}})^H$.
