#+title: Ch 01 Vector Spaces
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-03-05>
#+lastmod: <2026-03-22 14:31>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t
#+startup: overview latexpreview inlineimages

* Definition  1.1:  Binary operation $+$ on a set $E$

A binary operation on set $E$ is a mapping

\begin{align*}
+ : E \times E &\rightarrow E \\
(x, y) &\mapsto x + y \\
\end{align*}

which produces an element $E$ out of two elements from $E$.

* Definition  1.3:  Commutative Group

We say that $(E, +)$ is a group when $E$ is a set, and $+$ is a binary operation on $E$ satisfying:

1. Associativity: $(x + y) + z = x + (y + z), \quad \forall x, y, z \in E$
2. Identity element: $\exists 0_{E} : x + 0_{E} = x$
3. Inverse element: $\forall x \in E, \exists \tilde{x} \in E : x + \tilde{x} = 0_{E}$
4. Commutativity: $x + y = y + x$

* Definition  1.5:  Scalar multiplication

Scalar multiplication on $E$ over the field $\mathbb{K}$ is a map

\begin{align*}
\times : \mathbb{K} \times E &\rightarrow E \\
(\lambda, x) &\mapsto \lambda \times x \\
\end{align*}

which produces an element in $E$ out of scalar $\lambda$ and an input element $x \in E$.

* Definition  1.6:  Compatibility between $\cdot$ and $+$

We say that $\cdot$ is compatible with $+$ if and only if for all $x, y \in E$ and all $\lambda, \mu \in \mathbb{K}$:

1. identity element of the scalar multiplication: $1_{\mathbb{K}} \cdot x = x$ ($1_{\mathbb{K}}$ being the multiplicative identity of $\mathbb{K}$)

2. compatibility of scalar multiplication with field multiplication:

   $$(\lambda \mu) \cdot x = \lambda \cdot (\mu \cdot x)$$

3. distributivity of scalar multiplication w.r.t. vector addition:

   $$\lambda \cdot (x + y) = \lambda \cdot x + \lambda \cdot y$$

4. distributivity of scalar multiplication w.r.t. field addition:

   $$(\lambda + \mu) \cdot x = \lambda \cdot x + \mu \cdot y$$

* Definition  1.7:  Vector space

*Definition (Vector Space)* A vector space $V$ over a field $\mathbb{F}$ is equipped with two operations:

- Vector addition $+ : V + V \rightarrow V$
- Vector multiplication $\times : \mathbb{F} \times V \rightarrow V$

Such that the following axioms hold for all $u, v, w \in V$ and all scalars $a,b \in \mathbb{F}$:

1. Associativity of addition

   $(u + v) + w = u + (v + w)$

2. Commutativity of addition

   $u + v = v + u$

3. Additive identity

   $\exists 0 \in V : \forall u \in V,  u + 0 = u$

4. Additive inverse

   $\forall u \in V, \exists -u \in V : u + (-u) = 0$

5. Distributivity over scalar additon

   $(a + b) \times u = (a \times u) + (b \times u)$

6. Distributivity over vector addition

   $a \times (u + v) = (a \times u) + (a \times v)$

7. Compatability of scalar multiplication

   $a \times (b \times u) = (a \times b) \times u$

8. Scalar multiplicative identity

   $1 \times u = u$

   Where $1$ is a multiplicative identity of $\mathbb{F}$.

* Definition  1.10: $\mathbb{K}[X]$ and degree of a polynomial

The set of polynomials over $\mathbb{K}$ is defined as

$$\mathbb{K}[X] := \left\{ \sum_{k=0}^{\infty} a_k X^k \;:\; a_k \in \mathbb{K} \;\text{and}\; \exists\, n \in \mathbb{N}_0 \;\text{s.t.}\; a_k = 0_{\mathbb{K}} \;\text{for}\; k > n \right\}.$$

The degree of a polynomial $p \in \mathbb{K}[X]$ is

$$\deg(p) := \max\{ n \in \mathbb{N}_0 \;:\; a_n \neq 0_{\mathbb{K}} \}.$$

* Definition  1.13: Linear combination

Let $E$ be a $\mathbb{K}$ vector space. Given vectors $x_1, \ldots, x_n \in E$, a /linear combination/ of these vectors is any vector of the form

$$v = \lambda_1 x_1 + \lambda_2 x_2 + \cdots + \lambda_n x_n, \qquad \text{with } \lambda_1, \ldots, \lambda_n \in \mathbb{K}, \text{ and } n \in \mathbb{N}.$$

* Definition  1.14: Generating set (Spanning set)

Let $\mathcal{X} = \{x_1, \ldots x_n\}$ be a finite subset of vectors of $E$ with $n \in \mathbb{N}$. We say that $\mathcal{X}$ a /generating set/ (or /spanning set/) of $E$ if any element of $E$ can be expressed as a linear combination of the elements of $\mathcal{X}$:

$$\forall\, x \in E, \; \exists\, \lambda_1, \ldots \lambda_n \in \mathbb{K} \;\text{s.t.}\; x = \sum_{i=1}^{n} \lambda_i x_i.$$

Equivalently,

$$E = \text{span}\{x_i\}_{i=1}^{n}.$$

* Definition  1.15: Linearly independent set (Free family)

Let $\mathcal{X} = \{x_1, \ldots x_n\}$ be a finite subset of vectors of $E$ with $n \in \mathbb{N}$. We say that $X$ is a linearly independent set (or a free family) if the only linear combination that gives the zero vector is the trivial one:

$$\lambda_1 x_1 + \cdots + \lambda_n x_n = 0 \;\text{for some}\; \lambda_1, \ldots, \lambda_n \in \mathbb{K} \quad \Rightarrow \quad \lambda_1 = \cdots = \lambda_n = 0.$$

* Definition  1.16: Basis

A set of vectors $\mathcal{B} = \{x_1, \ldots x_n\} \subset E$ is a /basis/ of $E$ if it is both generating and linearly independent.

* Proposition 1.17: Coordinate of a vector on a given basis

Let $\mathcal{B} = \{x_1, \ldots x_n\} \subset E$ be a basis of $E$. Then for any vector $x \in E$ there exist unique scalars $\lambda_1, \ldots, \lambda_n \in \mathbb{K}$ such that

$$x = \sum_{i=1}^{n} \lambda_i x_i.$$

The tuple of scalars

$$[x]^{\mathcal{B}} := (\lambda_1, \ldots, \lambda_n)^{\top} \in \mathbb{K}^n$$

is called the coordinate vector of $x$ with respect to the basis $\mathcal{B}$, and the linear mapping

\begin{align*}
\text{Vec} : E &\rightarrow \mathbb{K}^n \\
x &\mapsto [x]^{\mathcal{B}}
\end{align*}

is a isomorphism.

** Q&A

- Q_01

  What is the last point?

- A_01

  The point is that isomorphism means the two spaces are "structurally identical" as a vector spaces. So once you fix a basis $\mathcal{B}$, your abstract vectors space $E$ becomes indistinguishable from $\mathbb{K}^n$ in terms of linear algebra.

* Definition  1.52: Norm and normed vector space

Let $(E, +, \cdot)$ be a $\mathbb{K}$ vector space. A norm is a mapping $\|\cdot\|_E : E \rightarrow \mathbb{R}$ satisfying:

1. positivity: for all $x \in E$, it holds that $\|x\|_E \ge 0$,

2. non-degeneracy: for all $x \in E$, if $\|x\|_E = 0$, then $x = 0_E$,

3. homogeneity: for all $\lambda \in \mathbb{R}$ and all $x \in E$, $\|\lambda x\|_E = |\lambda| \|x\|_E$,

4. triangle inequality: for all $(x, y) \in E$, it holds that $\|x + y\|_E \le \|x\|_E + \|y\|_E$.

$(E, \|\cdot\|_E)$ is called a normed vector space.

