#+title: Ps 02
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-03-14>
#+lastmod: <2026-03-15 18:01>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t
#+startup: overview latexpreview inlineimages

* Problem 1 :DONE:
** Task
#+begin_quote
Let $X$ be a metric space and $f : [0, 1] \to X$ continuous. Show that $f([0, 1]) \subseteq X$ is path-connected.
#+end_quote

** Solution

#+begin_quote
*Lemma 11.1.12:* Path-connectedness is preserved under continuous maps

Let $X$ and $Y$ be metric spaces. If $X$ is path-connected and $f : X \rightarrow Y$ is continuous, then $f(X)$ is path connected.

*Proof.*

Let $a_1, a_2 \in f(X)$ be arbitrary. Then there are $x_1, x_2 \in X$ such that $f(x_1) = a_1$ and $f(x_2) = a_2$. Since $X$ is connected, there is a continuous function $\gamma : \left[ 0,1 \right] \rightarrow X$ such that $\gamma(0) = x_1$ and $\gamma(1) = x_2$. The function $f \circ \gamma : \left[ 0,1 \right] \rightarrow f(X)$ is also continuous, because $f$ is assumed to be continuous. It satisfies $f \circ \gamma(0) = f(x_1) = a_1$ and $f \circ \gamma(1) = f(x_2) = a_2$.
#+end_quote

The interval $\left[ 0,1 \right]$ is path-connected, since for any $s, t \in \left[ 0,1 \right]$ the map $\gamma(u) = s + u(t - s)$ is a continuous path from $s$ to $t$. Since $f$ is continuous, $f(\left[ 0,1 \right])$ is path-connected by /Lemma 11.1.12/.

* Problem 2 :DONE:
** Task
#+begin_quote
Let $f : [0, 1] \to \mathbb{R}^2$ and $f_1, f_2 : [0, 1] \to \mathbb{R}$, so that
\[
f(t) = \begin{pmatrix} f_1(t) \\ f_2(t) \end{pmatrix}.
\]
We equip $\mathbb{R}^2$ with the standard metric


$$d(x, y) = \sqrt{(x_1 - y_1)^2 + (x_2 - y_2)^2}$$


(a) Prove that the coordinate map $\chi_i : \mathbb{R}^2 \to \mathbb{R}$ defined by $\chi_i(x_1, x_2) = x_i$ is continuous, for $i = 1, 2$.

(b) Prove that $f$ is continuous if and only if both $f_1$ and $f_2$ are continuous.
#+end_quote

** Solution

*** (a)

Let $\epsilon > 0$. Choose $\delta = \epsilon$. Then if $d(x,y) < \delta$,

$$|\chi_i(x) - \chi_i(y)| = |x_i - y_i| \le \sqrt{(x_1 - y_1)^2 + (x_2 - y_2)^2} = d(x,y) < \delta = \epsilon$$

Hence, $\chi_i : \mathbb{R}^2 \rightarrow \mathbb{R}$ is continuous.

*** (b)

- ($\Rightarrow$) If $f$ is continuous, then $f_i = \chi_i \circ f$ is continuous as a composition of continuous maps.

- ($\Leftarrow$) Let $\epsilon > 0$. $f_1$ is continuous, so $\forall \epsilon > 0 \exists \delta_1 : |s - t| < \delta_1 \implies |f_1(s) - f_1(t)| < \frac{\epsilon}{\sqrt{2}}$. Similarly, for $f_2$, $\forall \epsilon > 0 \exists \delta_2 : |s - t| < \delta_2 \implies |f_2(s) - f_2(t)| < \frac{\epsilon}{\sqrt{2}}$.

  Define $\delta = \min(\delta_1, \delta_2)$. Thus,

  $$d(f(s), f(t)) = \sqrt{\left( f_1(s) - f_1(t) \right)^2 + \left( f_2(s) - f_2(t) \right)^2} < \sqrt{\frac{\epsilon^2}{2} + \frac{\epsilon^2}{2}} = \epsilon$$

* Problem 3
** Task
#+begin_quote
Let $S = \mathbb{R}^2 \setminus \{(0, 0)\}$ and $x = (1, 0)$ and $y = (-1, 0)$.

(a) Define a continuous path from $x$ to $y$.

(b) Plot this path in Julia.

(c) Visualize the sets
\[
A = \{(x, y) \in \mathbb{R}^2 : x^2 + y^2 < 1\}, \quad B = \{(-1, y) : -1 \leq y \leq 1\} \cup \{(1, y) : -1 \leq y \leq 1\}
\]
in Julia by sample/grid points. Determine which of the two sets is path-connected.
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_03_02.jl
#+end_src

#+begin_src julia :results value :exports both :tangle julia/p_03_03.jl
#+end_src

* Problem 4
** Task
#+begin_quote
Let $f : [0, 1] \to \mathbb{R}$ be given by
\[
f(x) = \frac{1}{4}(x^2 + 1).
\]

(a) Show that $f$ maps $[0, 1]$ into itself and is a contraction on $[0, 1]$.

(b) Deduce that $f$ has a unique fixed point and implement the fixed point iteration in Julia.
#+end_quote

** Notes

** Solution
#+begin_src julia :results value :exports both :tangle julia/p_04_02.jl
#+end_src
