#+title: Problem Set 9
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-01>
#+lastmod: <2025-11-04 11:33>
#+options: num:t
#+startup: overview

* Problem 1 [DONE] [CHECKED]
** Task
Consider the function g : (-1,1) -> ℝ defined by g(x) = x/(1-x^2). Prove that g is a bijection. Find g^-1.

** Notes
- I don't really understand the point of writing "(-1,1) -> ℝ". Do we pass the (-1,1) and get the ℝ as the output?

  Function g takes an input x, from the range of -1 to 1 excluded, and returns a real number as output.

- Find g^-1
  g(x) = x/(1-x^2)
  Thus, to find g':

  y = g(x)
  Thus,
  x = y/(1-y^2)
  x(1-y^2) = y
  x = xy^2 + y

  xy^2 + y - x = 0

  x = (b - (b^2 - 4*a*c)^(1/2))/(2a)

  g^-1 = (1 ± (1 + 4x^2)^(1/2))/(2x)

Only one element of domain is related to one element of codomain.
#+begin_quote Injective
*Proposition.* g : (-1,1) -> ℝ, g(x) = x/(1-x^2) is injective.

*Proof.*
g(x) = x/(1-x^2)
g'(x) = (1+x^2)/(1-x^2)^2

Since,
- Numerator: 1+x^2
  For all x ∈ ℝ, x^2 >= 0.
  So 1+x^2 >= 1 > 0, for x ∈ ℝ.

- Denominator: (1-x^2)^2
  For all x ∈ ℝ, x^2 >= 0.
  (1-x^2)^2 > 0. (can not be equal to 0)

Thus, g' is always positive in the range of (-1,1)

Since, the derivative of the function is always > 0, g is striclty monotone increasing function. Thus, g is injective.
#+end_quote

Every element of codomain has at least one relation with element of domain.
#+begin_quote Surjection
*Proposition.* g : (-1,1) -> ℝ, g(x) = x/(1-x^2) is surjective.

*Proof.* Let y ∈ ℝ be arbitrary. We need to find x ∈ (-1,1), such that g(x) = y.

From y = x/(1-x^2), we get:

           y = x / (1 - x^2)
  y(1 - x^2) = x
   -yx^2 + y = x
yx^2 + x - y = 0

Using the quadratic formula:

x = (-1 ± (1 + 4y^2)^(1/2))/(2y)

Key issues to adress:
- Which sign (+ or -) do we choose?
- Is this x actually in (-1,1)?
- What if y = 0?

*Case 1: y = 0*
        Then g(x) = 0 gives x/(1-x^2) = 0, so x = 0. Since 0 ∈ (-1,1), this works.

*Case 2: y != 0*
        We have: x = (-1 ± (1 + 4y^2)^(1/2))/(2y)
        Notice that (1 + 4y^2)^(1/2) > 1. (for y != 0)

        - If y > 0: x > 0, so we take the positive sign.
          x = (-1 + (1 + 4y^2)^(1/2))/(2y) = positive / positive  : yes
          x = (-1 - (1 + 4y^2)^(1/2))/(2y) = negative / positive  : no

        - If y < 0: x < 0, so we take the negative sign.
          x = (-1 + (1 + 4y^2)^(1/2))/(2y) = positive / negative  : yes
          x = (-1 - (1 + 4y^2)^(1/2))/(2y) = negative / negative  : no

        Thus, we select a positive sign.
                x = (-1 + (1 + 4y^2)^(1/2))/(2y)

        Now, we must verify |x|<1. This requires showing that for any y ∈ ℝ, x ∈ (-1,1).

        Thus,
        .|(-1 + (1 + 4y^2)^(1/2))/(2y)| < 1
        -1 + (1 + 4y^2)^(1/2)) < 2|y|
        (1 + 4y^2)^(1/2)) < 1 + 2|y|    (squaring both sides)
        1 + 4y^2 < 1 + 4|y| + 4y^2
        0 < 4|y| (for y != 0)

*Conclusion.* Therefore, g is surjective.
#+end_quote

** Solution
Only one element of domain is related to one element of codomain.
#+begin_quote Injective
*Proposition.* g : (-1,1) -> ℝ, g(x) = x/(1-x^2) is injective.

*Proof.*
g(x) = x/(1-x^2)
g'(x) = (1+x^2)/(1-x^2)^2

Since,
- Numerator: 1+x^2
  For all x ∈ ℝ, x^2 >= 0.
  So 1+x^2 >= 1 > 0, for x ∈ ℝ.

- Denominator: (1-x^2)^2
  For all x ∈ ℝ, x^2 >= 0.
  (1-x^2)^2 > 0. (can not be equal to 0)

Thus, g' is always positive in the range of (-1,1)

Since, the derivative of the function is always > 0, g is striclty monotone increasing function. Thus, g is injective.
#+end_quote

Every element of codomain has at least one relation with element of domain.
#+begin_quote Surjection
*Proposition.* g : (-1,1) -> ℝ, g(x) = x/(1-x^2) is surjective.

*Proof.* Let y ∈ ℝ be arbitrary. We need to find x ∈ (-1,1), such that g(x) = y.

From y = x/(1-x^2), we get:

           y = x / (1 - x^2)
  y(1 - x^2) = x
   -yx^2 + y = x
yx^2 + x - y = 0

Using the quadratic formula:

x = (-1 ± (1 + 4y^2)^(1/2))/(2y)

Key issues to adress:
- Which sign (+ or -) do we choose?
- Is this x actually in (-1,1)?
- What if y = 0?

*Case 1: y = 0*
        Then g(x) = 0 gives x/(1-x^2) = 0, so x = 0. Since 0 ∈ (-1,1), this works.

*Case 2: y != 0*
        We have: x = (-1 ± (1 + 4y^2)^(1/2))/(2y)
        Notice that (1 + 4y^2)^(1/2) > 1. (for y != 0)

        - If y > 0: x > 0, so we take the positive sign.
          x = (-1 + (1 + 4y^2)^(1/2))/(2y) = positive / positive  : yes
          x = (-1 - (1 + 4y^2)^(1/2))/(2y) = negative / positive  : no

        - If y < 0: x < 0, so we take the negative sign.
          x = (-1 + (1 + 4y^2)^(1/2))/(2y) = positive / negative  : yes
          x = (-1 - (1 + 4y^2)^(1/2))/(2y) = negative / negative  : no

        Thus, we select a positive sign.
                x = (-1 + (1 + 4y^2)^(1/2))/(2y)

        Now, we must verify |x|<1. This requires showing that for any y ∈ ℝ, x ∈ (-1,1).

        Thus,
        .|(-1 + (1 + 4y^2)^(1/2))/(2y)| < 1
        -1 + (1 + 4y^2)^(1/2)) < 2|y|
        (1 + 4y^2)^(1/2)) < 1 + 2|y|    (squaring both sides)
        1 + 4y^2 < 1 + 4|y| + 4y^2
        0 < 4|y| (for y != 0)

*Conclusion.* Therefore, g is surjective.
#+end_quote

#+begin_quote Bijection
*Proposition.* g : (-1,1) -> ℝ, g(x) = x/(1-x^2) is bijective.

*Proof.* Since g is injective and surjective, g is also bijective.
#+end_quote

* Problem 2 [DONE] [CHECKED]
** Task
Define the symmetric difference A△B of sets A and B as

        A△B := (A\B)∪(B\A).

Prove that if A and B are finite sets and |A|=|B|, then |A△B| is even.

** Notes
- What is a symmetric difference of sets?

  It is when an element its either in set A or set B, but not in both of them.

A△B := (A\B)∪(B\A)

A△B := (A∪B)\(A∩B)

#+begin_quote
*Proposition.* If A and B are finite sets and |A|=|B|, then |A△B| is even.

If |A|=|B|, then,

(4 cases)
- |A| = |B| = 2n
  - (A∩B) = 2k
    Thus, both
    .|A\(A∩B)| = B\(A∩B) = 2j

    Since
    A△B := (A\B)∪(B\A)
        := (A∪B)\(A∩B)
        := A\(A∩B) ∪ B\(A∩B)

    .|A△B| = 2*2j

  - (A∩B) = 2k+1
    Thus, both
    .|A\(A∩B)| = B\(A∩B) = 2j+1

    Since
    A△B := (A\B)∪(B\A)
        := (A∪B)\(A∩B)
        := A\(A∩B) ∪ B\(A∩B)

    .|A△B| = 2*(2j+1)

- |A| = |B| = 2n+1
  - (A∩B) = 2k
    Thus, both
    .|A\(A∩B)| = B\(A∩B) = 2j+1

    Since
    A△B := (A\B)∪(B\A)
        := (A∪B)\(A∩B)
        := A\(A∩B) ∪ B\(A∩B)

    .|A△B| = 2*(2j+1)

  - (A∩B) = 2k+1
    Thus, both
    .|A\(A∩B)| = B\(A∩B) = 2j

    Since
    A△B := (A\B)∪(B\A)
        := (A∪B)\(A∩B)
        := A\(A∩B) ∪ B\(A∩B)

    .|A△B| = 2*2j


#+end_quote

** Solution
#+begin_quote
*Proposition.* If A and B are finite sets and |A|=|B|, then |A△B| is even.

A△B := (A\B)∪(B\A)
    := (A∪B)\(A∩B)

.|A△B| := |A∪B|-|A∩B|

But
.|A∪B| = |A| + |B| - |A∩B|

Thus,
.|A△B| := |A| + |B| - 2|A∩B|

If |A| = |B|,

.|A△B| := 2|A| - 2|A∩B|
       := 2(|A| - |A∩B|)

Thus, |A△B| is even.
#+end_quote

* Problem 3 [DONE] [CHECKED]
** Task
Find an example of a function f : X -> Y and sets A,B ⊂ X, such that

        f(A△B) != f(A)△f(B).

** Notes
It means:
Find a function and two sets, such that a function on element of A xor B, gives output that is element of both f(A) and f(B).

Ok. let,
A = {1,2,3}
B = {-1,-2,-3}
X = {-3,-2,-1,0,1,2,3}

f = x^2
Thus,
f(A) = {1,4,9}
f(B) = {1,4,9}

Check:
f(A)△f(B) = {1,4,9}△{1,4,9} = ∅
f(A△B) = {1,4,9} != ∅ = {1,4,9}△{1,4,9} = f(A)△f(B)

** Solution
Let,
A = {1,2,3}
B = {-1,-2,-3}
X = {-3,-2,-1,0,1,2,3}
f = x^2

Thus,
f(A) = {1,4,9}
f(B) = {1,4,9}

Check:
f(A)△f(B) = {1,4,9}△{1,4,9} = ∅
f(A△B) = {1,4,9} != ∅ = {1,4,9}△{1,4,9} = f(A)△f(B)

* Problem 4 [DONE] [CHECKED]
** Task
Determine whether the following function f is odd, even, or neither. In each case, the domain of f is the the largest subset of ℝ, where f is defined.

1. f(x) = 5x-x^5
2. f(x) = 3/(x-5) - 4/(x-6) - 3/(x+5) + 4/(x+6)
3. f(x) = (1+x^3)^(1/3)
4. f(x) = (1+x+x^2)^(1/2) - (1-x+x^2)^(1/2)
5. f(x) = log2((1-x)/(1+x))

** Notes
- What is an even function?

  Even function is a real function, such that
        f(-x) = f(x)

- What is an odd function?

  Even function is a real function, such that
        f(-x) = -f(x)

** Solution
1. f(x) = 5x-x^5
   *Domain:* ℝ
   *Parity:* odd.
   *Reason:* f(-x) = -5x+x^5 = -(5x-x^5) = -f(x).

2. f(x) = 3/(x-5) - 4/(x-6) - 3/(x+5) + 4/(x+6)
   *Domain:* ℝ \ {±5,±6}
   *Parity:* even.
   *Reason:* f(-x) = 3/(-x-5) - 4/(-x-6) - 3/(-x+5) + 4/(-x+6)
                   = - 3/(x+5) + 4/(x+6) + 3/(x-5) - 4/(x-6)
                   = f(x).

3. f(x) = (1+x^3)^(1/3)
   *Domain:* ℝ
   *Parity:* neither.
   *Reason:* counterexample:
             f(1) = (1+1)^(1/3) = 2^(1/3)
             f(-1) = (1-1)^(1/3) = 0
             0 != 2^(1/3)

4. f(x) = (1+x+x^2)^(1/2) - (1-x+x^2)^(1/2)
   *Domain:* ℝ
   *Parity:* odd.
   *Reason:* f(-x) = (1-x+x^2)^(1/2) - (1+x+x^2)^(1/2)
                   = -((1+x+x^2)^(1/2) - (1-x+x^2)^(1/2))
                   = -f(x)

5. f(x) = log2((1-x)/(1+x))
   *Domain:* (-1,1)
             (1-x)/(1+x) = (1-x)^2 / (1-x^2)
             Thus,
             x^2 < 1
             .|x| < 1
   *Parity:* odd.
   *Reason:* f(-x) = log2((1+x)/(1-x))
                   = log2((1-x)/(1+x))^-1
                   = -log2((1-x)/(1+x))
                   = -f(x)

* Problem 5 [DONE] [REDO]
** Task
Determine on which intervals the function f : ℝ -> ℝ is monotone (increasing/decreasing), if

1. f(x) = x^3 + 3x + 5
2. f(x) = ax^2 + bx + c, where a,b,c ∈ ℝ and a != 0
3. f(x) = x - 1/x
4. f(x) = x^4 + 6x^2 + 1

** Notes
** Solution
1. f(x) = x^3 + 3x + 5

   f'(x) = 3x^2 + 3 = 3(x^2 + 1) > 0

   *Conclusion.* f is strictly increasing on (-∞,∞).

2. f(x) = ax^2 + bx + c, where a,b,c ∈ ℝ and a != 0

   f'(x) = 2ax + b

   Thus, f'(x) = 0 --> x = -b/2a

   If a > 0: f'(x) < 0 for x < -b/2a and f'(x) > 0 for x > -b/2a.

   *Conclusion.* f is stirctly decreasing on (-∞,-b/2a), and stricly increasing on (-b/2a,∞).

3. f(x) = x - 1/x

   f'(x) = 1 + 1/x^2
   Thus,
   f'(x) > 0 for every x != 0

   *Conclusion.* f is stirctly increasing on (-∞,0), and stricly increasing on (0,∞). (no value at x=0)

4. f(x) = x^4 + 6x^2 + 1

   f'(x) = 4x^3 + 12x
         = 4x(x^2 + 3)

   Since (x^2 + 3) > 0 for for all x ∈ ℝ, the sign of f'(x) is the sign of x.

   f'(x) < 0 for x < 0 and f'(x) > 0 for x > 0; f(0) = 0.

   *Conclusion.* f is stirctly decreasing on (-∞,0), and stricly increasing on (0,∞). (no value at x=0). (At x = 0, there is a local minimum.)

* Problem 6 [DONE] [CHECKED]
** Task
Let f1 : [a,b] -> ℝ and f2 : [a,b] -> ℝ. What can we say about the monotonicity of F : [a,b] -> ℝ defined as F = f1 + f2.

- If f1,f2 are increasing.
- If f1,f2 are non-decreasing.
- If f1 is increasing and f2 is decreasing.

** Notes
- If f1,f2 are increasing.

  If f1 and f2 are both increasing on [a,b], then F is also (non-decreasing) monotone increasing.

  *Proof.* Let a <= x < y <= b.

  Then, f1(x) < f1(y) and f2(x) < f2(y).

  So, F(x) = f1(x) + f2(x) < f1(y) + f2(y) = F(y)

- If f1,f2 are non-decreasing.

  If f1 and f2 are both non-decreasing on [a,b], then F is also non-decreasing.

  *Proof.* Let a <= x <= y <= b.

  Then, f1(x) <= f1(y) and f2(x) <= f2(y).

  So, F(x) = f1(x) + f2(x) <= f1(y) + f2(y) = F(y)

- If f1 is increasing and f2 is decreasing.

  Since two functions have different monotonicities, and we have no information about both of them, nothing can be concluded definetely about F. It might be increasing, decreasing, constant or not monotone at all.

** Solution
1. If f1,f2 are strictly increasing on [a,b]:

   Let a <= x < y <= b. Then f1(x) < f1(y) and f2(x) < f2(y).

   Thus, F(x) = f1(x) + f2(x) < f1(y) + f2(y) = F(y).

   F is strictly increasing.

2. If f1,f2 are non-decreasing on [a,b]:

   Let a <= x < y <= b. Then f1(x) <= f1(y) and f2(x) <= f2(y).

   Thus, F(x) = f1(x) + f2(x) <= f1(y) + f2(y) = F(y).

   F is non-decreasing.

3. If f1 is increasing and f2 is decreasing.
   Since two functions have different monotonicities, and we have no information about both of them, nothing can be concluded definetely about F. It might be increasing, decreasing, constant or not monotone at all.

   Examples:
   - *Constant:* f1(x) = x, f2(x) = 1 - x on [0,1]. Thus, F(x) = 1 is *constant*.
   - *Strictly decreasing:* f1(x) = x, f2(x) = -3x. Thus, F(x) = -2x is *strictly decreasing*.
   - *Striclty increasing:* f1(x) = 2x, f2(x) = -x. Thus, F(x) = x is *strictly increasing*.

* Problem 7 [DONE] [CHECKED]
** Task
Let A and B be countable sets. Prove that A x B is also countable.

** Notes
*Proposition.* If A and B be countable sets, A x B is also countable.

*Proof.*

- Define countable sets
  Since A and B are countable, their elements can be listed.
  A is countable infinite and can be listed as A = {a1,a2,a3,...}.
  Same with B. B = {b1,b2,b3,...}.

- Define Cartesian product
  A Cartesian product AxB is a set of all pairs (a,b), such that a∈A and b∈B.

- Define a collection of sets
  For each element of ai ∈ A, form a set by taking the Cartesian product of ai and B.
  {ai} x B = {(ai,b1),(ai,b2),(ai,b3),...}

- Establish countability on each set
  Since B is countable, each set {ai} x B can be put into a one-to-one correspondence with the natural numbers. Therefore, each {ai} x B is countable set.

-

** Solution
Let A and B be countable sets.

1. List elements
   Since A and B are countable, we can list their elements as

   A = {a1,a2,a3,...}
   B = {b1,b2,b3,...}

2. Describe the product
   The Cartesian product consists of pairs (ai,bj) where ai ∈ A, bj ∈ B.

3. Visualise the pairs
   Arrange the pairs the following way:

   (a1,b1) (a1,b2) (a1,b3) ...

   (a2,b1) (a2,b2) (a2,b3)

   (a3,b1) (a3,b2) (a3,b3)

   ...

4. Enumerate the pairs diagonally
   (a1,b1),(a1,b2),(a2,b1),(a1,b3),(a2,b2),(a3,b1),...

   In this way, every pair (ai,bj) will appear after a finite number of steps.

5. Conclusion
   Since we can list all elements of AxB one by one without missing any, AxB is countable.

* Problem 8 [DONE] [REDO]
** Task
Prove or disprove the following:

1. There exists a bijective function f : ℚ -> ℝ.
2. If A,B,C are sets such that A ⊂ B ⊂ C and A and C are countable, then B is countable.
3. The set S = {root(5)/2n : n ∈ ℕ} is countable.
4. There exists a countable subset of the set of irrational numbers.

** Notes
No notes(

** Solution
1. There exists a bijective function f : ℚ -> ℝ.
   *Rational number* is any real number that can be written in the form of a/b in which a,b ∈ ℤ, and b != 0.

   *Proposition.* There exists a bijective function f : ℚ -> ℝ.

   *Proof.* Lets assume f : ℚ -> ℝ.

   e ∈ ℝ

   e is irrational and can not be written in the form of a/b.

   Thus, there is no preimage of e in domain of f. Thus f is not surjective.

   Since bijection implies surjectivity, f is not bijective.

2. If A,B,C are sets such that A ⊂ B ⊂ C and A and C are countable, then B is countable.

   *Definition.* A set is *countable* if it has the same cardinality as some subset of the natural numbers.

   In other words, if there exists a bijective function between the set and a subset of the natural numbers.

   Given: A ⊂ B ⊂ C are countable.

   Since C is countable, there exists a bijective function f from C to a subset of natural numbers.

   And since B is a subset of C, for every element b in B, there existgs a natural number n such that f(b) = n. This creates a function g from B to a subset of natural numbers.

   Thus, B is countable.

3. The set S = {root(5)/2n : n ∈ ℕ} is countable.

   Yes, S = {root(5)/2n : n ∈ ℕ} is countable.

   *Proof.*

   A set is countable when there exists a bijective function from the set of natural numbers to the set in the question.

   In our case the function is f : ℕ -> S defined by f(n) = root(5)/2n, for all n in ℕ is a bijection.

   a. Injective
      Assume f(n) = f(m) for some natural number of n and m.

      Then by definition of f, root(5)/2n = root(5)/2m.

      After cleaning equation we get:

      2n = 2m

      And hence m = n, and f is injective.

   b. Surjective
      For every element a in S, there exists n in N, such that f(n) = a by definition of the set S.

      Thus f is surjective.

   Hence, by definition, the set S is countable.

4. There exists a countable subset of the set of irrational numbers.

   Lets take e (Euler number).

   S = {ne : n ∈ ℕ} = {1e,2e,3e,...}

   S is countable, since it is basically set of natural numbers, with each element being multiplied by irrational number e, forming a subset of the set of irrational numbers. Since e * n : n ∈ ℕ (multiplying irrational number by rational) gives irrational number.
