#+title: Problem Set 9
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-01>
#+lastmod: <2025-11-02 12:21>
#+options: num:t
#+startup: overview

* Problem 1 [IN PROGRESS]
** Task
Consider the function g : (-1,1) -> ℝ defined by g(x) = x/(1-x^2). Prove that g is a bijection. Find g^-1.

** Notes
- I don't really understand the point of writing "(-1,1) -> ℝ". Do we pass the (-1,1) and get the ℝ as the output?

  Function g takes an input x, from the range of -1 to 1 excluded, and returns an integer as output.

- Find g^-1
  g(x) = x/(1-x^2)
  Thus, to find g':

  y = g(x)
  Thus,
  x = y/(1-y^2)
  x(1-y^2) = y
  x = xy^2 + y

  xy^2 + y - x = 0

  x = (b - (b^2 - 4*a*c)^(1/2))/(2a)

  g^-1 = (1 ± (1 + 4x^2)^(1/2))/(2x)

Only one element of domain is related to one element of codomain.
#+begin_quote Injective
*Proposition.* g : (-1,1) -> ℝ, g(x) = x/(1-x^2) is injective.

*Proof.*
g(x) = x/(1-x^2)
g'(x) = (1+x^2)/(1-x^2)^2

Since,
- Numerator: 1+x^2
  For all x ∈ ℝ, x^2 >= 0.
  So 1+x^2 >= 1 > 0, for x ∈ ℝ.

- Denominator: (1-x^2)^2
  For all x ∈ ℝ, x^2 >= 0.
  (1-x^2)^2 > 0. (can not be equal to 0)

Thus, g' is always positive in the range of (-1,1)

Since, the derivative of the function is always > 0, g is striclty monotone increasing function. Thus, g is injective.
#+end_quote

Every element of codomain has at least one relation with element of domain.
#+begin_quote Surjection
*Proposition.* g : (-1,1) -> ℝ, g(x) = x/(1-x^2) is surjective.

*Proof.* Assume y ∈ ℝ. Then,

           y = x / (1 - x^2)
  y(1 - x^2) = x
   -yx^2 + y = x
yx^2 + x - y = 0

Thus,
x = (-1 ± (1 + 4y^2)^(1/2))/(2y)


#+end_quote

** Solution
* Problem 2
** Task
** Notes
** Solution
* Problem 3
** Task
** Notes
** Solution
* Problem 4
** Task
** Notes
** Solution
* Problem 5
** Task
** Notes
** Solution
* Problem 6
** Task
** Notes
** Solution
* Problem 7
** Task
** Notes
** Solution
* Problem 8
** Task
** Notes
** Solution
