#+title: Problem Set 10
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-04>
#+lastmod: <2025-11-04 15:20>
#+options: num:t
#+startup: overview
* NB?
Below, asnwering "finite" or "infinite" to "How many?" is not enough. We care whether it is ℵ0 or c, or somethinsg else.

- ℵ is an aleph number, that represents the cardinality of infinite sets.
- ℵ0 in our case stands for the cardinality of natural numbers set, which is the smallest along all aleph numbers sequence.

* Problem 1
** Task
Prove that the set of finite bit strings is countable. (A bit string is a sequence of 0 and 1. like 0001101.)

** Notes
So I understand the set of finite of bit strings as:

{"0000", "0001", "0010", "0011", ...}

With each next element being a natural binary number (including 0).

Though, we should notice that problem states "sequence of 0 and 1", meaning that set lacks "0000" and "1111".


How to prove?

We can link each element of the bit strings set to a natural number, in our case it would look like:

We imagine each of the bits being the 2^n, where n is the index of the bit (it doesn't really matter if we count it from right or from left).

Thus, it would look like this:

|---+-----+-----+-----+-----|
|   | 2^3 | 2^2 | 2^1 | 2^0 |
|---+-----+-----+-----+-----|
| 1 |   0 |   0 |   0 |   1 |
|---+-----+-----+-----+-----|
| 2 |   0 |   0 |   1 |   0 |
|---+-----+-----+-----+-----|
| 3 |   0 |   0 |   1 |   1 |
|---+-----+-----+-----+-----|
0001 <-> 1
0010 <-> 2
0011 <-> 3
0100 <-> 4
...

And since a *countable set* is the set all of whose elements can be put into one-to-one relation with the natural numbers, means its elements can be listed in a sequence.

And since all binary strigns are repesentation of natural numbers in binary number system, meaning that each element of binary strings set is into one-to-one relation with a natural numbers.

** Solution
* Problem 2
** Task
** Notes
** Solution
* Problem 3
** Task
** Notes
** Solution
* Problem 4
** Task
** Notes
** Solution
* Problem 5
** Task
** Notes
** Solution
* Problem 6
** Task
** Notes
** Solution
* Problem 7
** Task
** Notes
** Solution
