#+title: Problem Set 10
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-04>
#+lastmod: <2025-11-04 11:53>
#+options: num:t
#+startup: overview
* NB?
Below, asnwering "finite" or "infinite" to "How many?" is not enough. We care whether it is ℵ0 or c, or somethinsg else.

- ℵ is an aleph number, that represents the cardinality of infinite sets.
- ℵ0 in our case stands for the cardinality of natural numbers set, which is the smallest along all aleph numbers sequence.

* Problem 1
** Task
Prove that the set of finite bit strings is countable. (A bit string is a sequence of 0 and 1. like 0001101.)

** Notes
So I understand the set of finite of bit strings as:

{"0000", "0001", "0010", "0011", ...}

With each next element being a  natural binary number (including 0).

Though, we should notice that problem states "sequence of 0 and 1", meaning that set lacks "0000" and "1111".



** Solution
* Problem 2
** Task
** Notes
** Solution
* Problem 3
** Task
** Notes
** Solution
* Problem 4
** Task
** Notes
** Solution
* Problem 5
** Task
** Notes
** Solution
* Problem 6
** Task
** Notes
** Solution
* Problem 7
** Task
** Notes
** Solution
