#+title: Ps 01
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-01-26>
#+lastmod: <2026-01-30 12:53>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t
#+startup: overview latexpreview inlineimages

* Problem 1 :DONE:
** Task
#+begin_quote
Let $\Omega$ be any nonempty set. Define the function $d_{\Omega}:\Omega\times\Omega\rightarrow\mathbb{R}$ by
$$d_{\Omega}(x,y)=\begin{cases}0,& \text{if } x=y,\\ 1,& \text{if } x\ne y.\end{cases}$$
(1) Show that $d_{\Omega}$ is a metric on $\Omega$.
(2) Let $(x_{n})_{n\in\mathbb{N}}$ be a sequence in $\Omega$. Show that $(x_{n})_{n\in\mathbb{N}}$ converges in $(\Omega,d_{\Omega})$ if and only if it is eventually constant.
(... properly define what we mean by "eventually constant"...)
#+end_quote

** Solution

#+begin_quote
Definition (metric space). Given a set $\Omega \neq \emptyset$, we say that a mapping $d_{\Omega} : \Omega \times \Omega \rightarrow \mathbb{R}$ is a metric if the following three properties are satisfied:

- (M1) Symmetry: $\forall \, x, y \in \Omega$,

  $$d_{\Omega}(x,y) = d_{\Omega}(y,x)$$

- (M2) Triangle Inequality: $\forall \, x, y, z \in \Omega$,

  $$d_{\Omega}(x,z) \leq d_{\Omega}(x,y) + d_{\Omega}(y,z)$$

- (M3) Definiteness: $\forall \, x, y \in \Omega$,

  $$d_{\Omega}(x,y) = 0 \iff x = y$$

If $d_{\Omega}$ is a metric on $\Omega$, then $(\Omega, d_{\Omega})$ is called a metric space.
#+end_quote

- Part (1)

  For $d_{\Omega}$ to be a metric on set $\Omega$, it must satisfy three requirements of metric space.

  By the outlined definition of a metric space, I validate $(\Omega, d_{\Omega})$ to be a metric space.

  - (M1) Symmetry: $\forall \, x, y \in \Omega$

    Let $x, y \in \Omega$. Hence,

    - Case $x=y$

      $$d_{\Omega}(x, y) = 0 \, \wedge \, d_{\Omega}(y, x) = 0 \implies d_{\Omega}(x, y) = d_{\Omega}(y, x)$$

      Case holds.

    - Case $x \neq y$

      $$d_{\Omega}(x, y) = 1 \, \wedge \, d_{\Omega}(y, x) = 1 \implies d_{\Omega}(x, y) = d_{\Omega}(y, x)$$

      Case holds.

    Hence. requirement holds.

  - (M2) Triangle Inequality: $\forall \, x, y, z \in \Omega$

    Let $x, y, z \in \Omega$. Hence,

    - Case $x = z$

      $$d_{\Omega}(x,z) \leq d_{\Omega}(x,y) + d_{\Omega}(y,z)$$

      LHS: $x = z \implies d_{\Omega}(x,z) = 0$ by definition.

      RHS: Since metric is non-negative ($d_{\Omega}$ is either $0$ or $1$), $\text{RHS} \ge 0$.

      $$0 \leq d_{\Omega}(x,y) + d_{\Omega}(y,z)$$

    - Case $x \neq z$

      $$d_{\Omega}(x,z) \leq d_{\Omega}(x,y) + d_{\Omega}(y,z)$$

      LHS: $x \neq z \implies d_{\Omega}(x,z) = 1$ by definition.

      RHS: Since $x \neq z$ this leads to 2 cases:

      - $y$ equal to either $x$ or $z$:

        RHS: $d_{\Omega}(x,y) + d_{\Omega}(y,z) = 1$

        Hence,

        \begin{align*}
        d_{\Omega}(x,z) &\leq d_{\Omega}(x,y) + d_{\Omega}(y,z) \\
        1 &\leq 1
        \end{align*}

      - $y$ equal to neither $x$ and $z$:

        RHS: $d_{\Omega}(x,y) + d_{\Omega}(y,z) = 2$

        Hence,

        \begin{align*}
        d_{\Omega}(x,z) &\leq d_{\Omega}(x,y) + d_{\Omega}(y,z) \\
        1 &\leq 1 + 1 \\
        1 &\leq 2 \\
        \end{align*}

    Hence. requirement holds.

  - (M3) Definiteness: $\forall \, x, y \in \Omega$

    - $d_{\Omega}(x,y) = 0 \implies x = y$ by definition of a function $d_{\Omega}$.

    - $x = y \implies d_{\Omega}(x,y) = 0$ by definition of a function $d_{\Omega}$.

    Hence. requirement holds.

  Since the mapping $d_{\Omega} : \Omega \times \Omega \rightarrow \mathbb{R}$ satisfies all three constraints, $d_{\Omega}$ is a metric of set $\Omega$.

- Part (2)

  - $\Rightarrow$ Convergence implies eventually constant

    - *Assumption*: Assume $(x_{n})_{n\in\mathbb{N}}$ converges to $x$.

      - This means, $\forall \epsilon > 0, \exists N \in \mathbb{N} \, : \, \forall n > N, d(x_{n}, x) < \epsilon$.

    - *Goal*: Show that this implies $x_{n} = x$.

    - *Proof*:

      - Let $\epsilon = 0.5$.

      - Convergence implies $d_{\Omega}(x_{n}, x) < \epsilon$.

      - Since discrete distance $d_{\Omega}$ is binary (either 0 or 1), $d_{\Omega}(x_{n}, x) = 0$.

      - As $d_{\Omega}(x,y) = 0 \Leftarrow x = y$, hence $x_{n} = x \, \forall n > N$.

    - *Conclusion*: By definition, $(x_{n})_{n\in\mathbb{N}}$ becomes eventually constant.

  - $\Leftarrow$ Eventually constant implies convergence

    - *Assumption*: Assume a sequence $(x_{n})_{n\in\mathbb{N}}$ becomes eventually constant at some value $x$.

      - This means, $\exists N \in \mathbb{N} \, : \, \forall n > N, d_{\Omega}(x_{n}, x) = 0$

    - *Goal*: Show that this satisfies the definition of convergence $\forall \epsilon > 0$.

    - *Proof*:

      - Let $\epsilon > 0$.

      - $\forall n > N$ we know $x_n = x$.

      - Hence, $d_{\Omega}(x_{n}, x) = 0$.

      - Thus $d_{\Omega}(x_{n}, x) < \epsilon \, \forall n > N$.

    - *Conclusion*: By definition, $(x_{n})$ converges in $x$.

* Problem 2 :DONE:
** Task
#+begin_quote
Consider $\mathbb{R}^{2}$ with the metric
$$d(x,y)=|x_{1}-y_{1}|+|x_{2}-y_{2}|, \quad x=(x_{1},x_{2})^{T}, y=(y_{1},y_{2})^{T}\in\mathbb{R}^{2}.$$
Consider the sequences $(a_{n})_{n\in\mathbb{N}},(b_{n})_{n\in\mathbb{N}}\subseteq\mathbb{R}^{2}$

$$a_{n}=\begin{pmatrix}\frac{1}{n+1}\\ 2+\frac{n}{n^{2}+1}\end{pmatrix} \qquad b_{n}=\begin{pmatrix}\sqrt{4+n}-\sqrt{n}\\ (-1)^{n}\end{pmatrix}$$

and determine their behavior in regards to convergence in $(\mathbb{R}^{2},d)?$ In addition, investigate/illustrate also in Julia.
#+end_quote

** Solution

- Part $(a_{n})_{n\in\mathbb{N}$

  \begin{align*}
        \text{As } \lim_{n\rightarrow\infty} a_n^{(1)} &= \lim_{n\rightarrow\infty} \frac{1}{n+1} = 0 \\
        \text{As } \lim_{n\rightarrow\infty} a_n^{(2)} &= \lim_{n\rightarrow\infty} 2 + \frac{n}{n^2+1} = \lim_{n\rightarrow\infty} 2 + \frac{1}{n+\frac{1}{n}} = 2 \\
  \end{align*}

  Hence a candidate limit for a sequence $(a_{n})_{n\in\mathbb{N}}$ is $x_l = (0, 2)^{T}$.

  Goal: Demonstrate that $\lim_{n\rightarrow\infty} d(x_{n}, x_{l}) = 0$.

  Thus,

  \begin{align*}
        \lim_{n\rightarrow\infty} d(x_{n}, x_{l}) &= \lim_{n\rightarrow\infty} \Big|\frac{1}{n+1} - 0\Big| + \Big|2 + \frac{n}{n^2 + 1} - 2\Big| \\
        &= \lim_{n\rightarrow\infty} \Big|\frac{1}{n+1}\Big| + \Big|\frac{n}{n^2 + 1}\Big| \\
        &= \lim_{n\rightarrow\infty} \Big|\frac{1}{n+1}\Big| + \lim_{n\rightarrow\infty} \Big|\frac{n}{n^2 + 1}\Big| \\
        &= 0 + \lim_{n\rightarrow\infty} \Big|\frac{n}{n^2 + 1}\Big| \\
        &= 0 + \lim_{n\rightarrow\infty} \Big|\frac{1}{n + \frac{1}{n}}\Big| \\
        &= 0 + 0 \\
        &= 0 \\
  \end{align*}

  Hence, $x_l = (0, 2)^{T}$ is indeed a limit of a sequence $(a_n)_{n\in\mathbb{N}}$.

- Part $(b_{n})_{n\in\mathbb{N}$

  \begin{align*}
        \text{As } \lim_{n\rightarrow\infty} b_n^{(1)} &= \lim_{n\rightarrow\infty} \sqrt{4+n}-\sqrt{n} \\
        &= \lim_{n\rightarrow\infty} \frac{(\sqrt{4+n}-\sqrt{n})(\sqrt{4+n}+\sqrt{n})}{(\sqrt{4+n}+\sqrt{n})} \\
        &= \lim_{n\rightarrow\infty} \frac{(4+n)-(n)}{\sqrt{4+n}+\sqrt{n}} \\
        &= \lim_{n\rightarrow\infty} \frac{4}{\sqrt{4+n}+\sqrt{n}} \\
        &= 0 \\
        \text{As } \lim_{n\rightarrow\infty} b_n^{(2)} &= (-1)^n \\
  \end{align*}

  $b_{n}^{(2)}$ would alternate between the values of $-1$ and $1$, since $n\in\mathbb{N}$ is either even or odd.

  Since the second component diverges, the sequence $(b_{n})_{n\in\mathbb{N}}$ can not converge in $(\mathbb{R}^{2}, d)$.

- Code
  #+begin_src julia :results value :exports both :tangle julia/p_2.jl
  using Plots

  a_n1(n) = 1 / (n + 1)
  a_n2(n) = 2 + (n / (n^2 + 1))
  b_n1(n) = sqrt(4+n) - sqrt(n)
  b_n2(n) = (-1)^n

  d(x,y) = abs(x[1] - y[1]) + abs(x[2] - y[2])

  n = 1:100

  a_x = a_n1.(n)
  a_y = a_n2.(n)

  b_x = b_n1.(n)
  b_y = b_n2.(n)

  p1 = scatter(a_x, a_y,
               title="sequence a_n",
               label="a_n points",
               xlabel="x1", ylabel="x2",
               legend=:bottomright)

  p2 = scatter(b_x, b_y,
               title="sequence b_n",
               label="b_n points",
               xlabel="x1", ylabel="x2",
               legend=:bottomright)

  plot(p1, p2, layout=(2,1), size=(1200, 1200))

  savefig("./figs/p_02.png")
  #+end_src

* Problem 3 :DONE:
** Task
#+begin_quote
Consider the series
$$\sum_{n=1}^{\infty}\frac{(-1)^{n+1}}{n}.$$
(1) Show that it converges towards a limit $a\in\mathbb{R}$ Does it converge absolutely?
(2) Use Julia to guess the limit of $\sum_{k=0}^{\infty}\frac{a^{k}}{k!}$
#+end_quote

** Solution

- Part (1)

  Observe the product $(-1)^{n+1} \cdot \frac{1}{n}$. As $n\rightarrow\infty$, $(-1)^{n+1}$ would alternate between the values of $-1$ and $1$. Hence the series is alternating.

  First, I will evaluate whether the alternating series converge by using the Alternating Series Test.

  - First condition of AST is a series' sequence being equal to $0$ at $n\rightarrow\infty$.

    $$\lim_{n\rightarrow\infty} \frac{1}{n} = 0$$

    Condition met.

  - Second condition of AST is series' sequence next term being less than preceding one $a_{n+1} < a_n$.

    $$\frac{1}{n+1} < \frac{1}{n}$$

    Condition met.

  Since both conditions are met, by the Alternating Series Test, the series converges to some limit $a \in \mathbb{R}$.

  Secondly, I have to validate whether the series converges absolutely.

  \begin{align*}
  \sum_{n=1}^{\infty} \Big| \frac{(-1)^{n+1}}{n} \Big| &= \sum_{n=1}^{\infty} \frac{|(-1)^{n+1}|}{|n|} \\
  &= \sum_{n=1}^{\infty} \frac{|(-1)^{n+1}|}{n} \quad \text{(since } n \in \mathbb{N}) \\
  &= \sum_{n=1}^{\infty} \frac{1}{n} \\
  &=  \frac{1}{1} + \frac{1}{2} +\frac{1}{3} + \frac{1}{4} + ... \\
  \end{align*}

  This is a harmonic series that is known to be divergent. Hence, series do not converge absolutely.

- Part (2)

  #+begin_src julia :results output :exports both :tangle julia/p_3.jl

  s_conv() = sum((-1)^(n+1)/n for n in 1:100_000)
  a = s_conv()

  n_conv() = sum((a^k)/factorial(k) for k in 0:20)

  println("Value of a: ", a)
  println("Value of Sum: ", n_conv())

  #+end_src

  #+RESULTS:
  : s_conv (generic function with 1 method)
  : 0.6931421805849816
  : n_conv (generic function with 1 method)
  : Value of a: 0.6931421805849816
  : Value of Sum: 1.999990000075072

* Problem 4
** Task
#+begin_quote
We want to show that the sequence $(a_{n})_{n\in\mathbb{N}}=((1+\frac{1}{n+1})^{n+1})_{n\in\mathbb{N}}$ contains a convergent subsequence by verifying the following steps:

(1) Show that $(a_{n})_{n\in\mathbb{N}}$ is bounded. Hint for the upper bound: use the binomial theorem to verify

$$(1+\frac{1}{n})^{n}\le\sum_{k=0}^{n}\frac{1}{k!}, \quad n=1,2,....$$

(2) Argue now that $(a_{n})_{n\in\mathbb{N}}$ has a convergent subsequence. Make additionally numerical checks in Julia to collect some evidence that $(a_{n})_{n\in\mathbb{N}}$ is monoton and hence convergent.
#+end_quote

** Solution

- Part (1)

  $$(a + b)^{n} = \sum_{k = 0}^{n} \frac{n!}{k!(n-k)!} \cdot a^{n-k} b^{k}$$


- Part (2)



#+begin_src julia :results value :exports both :tangle julia/p_4.jl
#+end_src
