#+title: Ch 03 Characterizing Running Times
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-03-18>
#+lastmod: <2026-03-18 19:02>
#+latex: \newpage
#+latex_header: \setlength{\parindent}{0pt}
#+latex_header: \setlength{\parskip}{1em}
#+latex_header: \usepackage{amsmath}
#+latex_header: \usepackage{amssymb}
#+latex_header: \usepackage{amsthm}
#+latex_header: \usepackage[margin=1in]{geometry}
#+options: num:t
#+startup: overview latexpreview inlineimages

* 3.1 $O$ notation, $\Omega$ notation, and $\Theta$ notation

** $O$ notation

$O$ notation characterises an upper bound on the asymptotic behaviour of a function. In other words, it says that a function grows no faster than a certain rate based on the highest order term.

** $\Omega$ notation

$\Omega$ notation characterises a lower bound on the asymptotic behaviour of a function. In other words, it says that a function grows at least as fast as a certain rate, based on the highest order term.

** $\Theta$ notation

$\Theta$ notation characterises a tight bound on the asymptotic behaviour of a function. It says that a function grows precisely at a certain rate, based on the highest order term.

If you can show that a function is both $O(f(n))$ and $\Omega(f(n))$ for some function $f(n)$, then you have shown that the function is $\Theta(f(n))$.

* 3.2 Asymptotic notation: formal definitions

** $O$ notation

$O$ notation provides an asymptotic upper bound. We use $O$ notation to give an upper bound on a function, to within a constant factor.

*Definition:* For a given function $g(n)$, we denote by $O(g(n))$ the set of functions

$$O(g(n)) = \left\{ f(n) : \exists c, n_0 > 0 : 0 \le f(n) \le c \cdot g(n) \forall n \ge n_0 \right\}$$

** $\Omega$ notation

$\Omega$ notation provides an asymptotic lower bound.

*Definition:* For a given function $g(n)$, we denote by $\Omega(g(n))$ the set of functions

$$\Omega(g(n)) = \left\{ f(n) : \exists c, n_0 > 0 : 0 \le c \cdot g(n) \le f(n), \forall n \ge n_0 \right\}$$

** $\Theta$ notation

$\Theta$ notation provides an asymptotic tight bound.

*Definition:* For a given function $g(n)$, we denote by $\Theta(g(n))$ the set of functions

$$\Theta(g(n)) = \left\{ f(n) : \exists c_1, c_2, n_0 > 0 : 0 \le c_1 \cdot g(n) \le f(n) \le c_2 \cdot g(n), \forall n \ge n_0 \right\}$$

** Theorem 3.1

For any two functions $f(n)$ and $g(n)$, we have $f(n) = \Theta(g(n))$ iff $f(n) = O(g(n))$ and $f(n) = \Omega(g(n))$.

** $o$ notation

The asymptotic upper bound provided by $O$ notation may or may not be asymptotically tight. The bound $2n^2 = O(n^2)$ is asymptotically tight, but the bound $2n = O(n^2)$ is not. Hence, we denote $o(n)$ as an upper bound that is not asymptotically tight.

*Definition:* We formally define $o(g(n))$ as the set

$$o(g(n)) = \left\{ f(n) : \forall c > 0, \exists n_0 > 0 : 0 \le f(n) < c \cdot g(n), \forall n \ge n_0 \right\}$$

Intuitively, in $o$ notation, the function $f(n)$ becomes insignificant relative to $g(n)$ as $n$ gets large:

$$\lim_{n\rightarrow\infty} \frac{f(n)}{g(n)} = 0$$

** $\omega$ notation

We use $\omega$ notation to denote a lower bound that is not asymptotically tight. One way to define it is by:

$$f(n) \in \omega(g(n)) \iff g(n) \in o(f(n))$$

Formally however, we define it as:

*Definition:* $\omega(g(n))$ is the set

$$\omega(g(n)) = \left\{ f(n) : \forall c > 0, \exists n_0 > 0 : 0 \le c \cdot g(n) < f(n), \forall n \ge n_0 \right\}$$

The relation $f(n) = \omega(g(n))$ implies that

$$\lim_{n\rightarrow\infty} \frac{f(n)}{g(n)} = \infty$$
