#+title: Ps 04
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2026-01-04>
#+lastmod: <2026-01-04 14:30>
#+options: num:t
#+startup: overview

* Problem 1
** Task
Verify the following trigonometric identities and check them in Julia.
$\cos(-x)=\cos(x)$
$\sin(-x)=-\sin(x)$
$\cos(x)=\sin(x+\frac{\pi}{2})$
$\sin(x)=\cos(x-\frac{\pi}{2})$
$\sin(x+\pi)=-\sin(x)$
$\cos(x+\pi)=-\cos(x)$,

** Notes

** Solution
#+begin_src julia :results value :export both :tangle julia/p_1.jl
#+end_src

* Problem 2
** Task
Determine the derivative of arccos and check in Julia.

** Notes

** Solution
#+begin_src julia :results value :export both :tangle julia/p_2.jl
#+end_src

* Problem 3
** Task
Suppose that $f,g:U\rightarrow\mathbb{R}$ are continuous in $x_{0}\in U$ Prove that if $f$ is also differentiable in $x_{0}$ and $f(x_{0})=0,$ then the product $f g$ is differentiable in $x_{0}$.
Illustrate this claim in Julia for the functions $f(x)=x$ and $g(x)=|x|$.

** Notes

** Solution
#+begin_src julia :results value :export both :tangle julia/p_3.jl
#+end_src

* Problem 4
** Task
The aim is to prove $(1+\frac{1}{n})^{n}\rightarrow e$
(a) Determine the values of $\log(1)$ $\log^{\prime}(1)$ and verify the identity
$\log^{\prime}(1)=\lim_{n\rightarrow\infty}n~\log(1+\frac{1}{n}).$
(b) Use the definition of the general exponential to prove $(1+\frac{1}{n})^{n}\rightarrow \exp(1)$.
(This determines the limit of the sequence in Problem 4 of Problem Set 1)

** Notes

** Solution

* Problem 5
** Task
Prove by induction (and using the product rule) that, for $1\le n\in\mathbb{N}$ the derivative of $f:\mathbb{R}\rightarrow\mathbb{R}$, $f(x)=x^{n}$ is given by $f^{\prime}(x)=nx^{n-1}$.

** Notes

** Solution

* Problem 6
** Task
Compute the derivative of the following functions:
1. $f(x)=\sin(x^{2})$
2. $g(x)=e^{3x+1}$
3. $f(x)=\ln(5x^{2}-x+4)$
4. $g(x)=(2x^{3}-x)^{5}$
5. $f(x)=\sqrt{1+e^{2x}}$
6. $g(x)=\cos(\ln~x)$, $x>0$
Visualize all functions and their derivatives in Julia.

** Notes

** Solution
#+begin_src julia :results value :export both :tangle julia/p_6.jl
#+end_src

* Problem 7
** Task
Prove the inequality of arithmetic and geometric means,
$\frac{1}{2}(x+y)\ge\sqrt{xy},$
$\forall x,y\in[0,\infty)$.
(Can be useful for the next exercise!)

** Notes

** Solution

* Problem 8
** Task
Let $(x_{n})_{n\ge0}$ be defined by $x_{0}=1$, $x_{n+1}=\frac{1}{2}(x_{n}+\frac{2}{x_{n}})$ $n\in\mathbb{N}$
1. Determine $x_{1}$, $x_{2}$, and $x_{3}$.
2. Compute $x_{n}$ for large $n$ in Julia, guess the limit, and visualize the convergence.
3. Prove that $x_{n}\ge\sqrt{2}$ for all $n\ge1.$
4. Prove that $(x_{n})_{n\ge1}$ is decreasing.
5. Conclude that $(x_{n})_{n\in\mathbb{N}}$ converges and determine its limit.

** Notes

** Solution
#+begin_src julia :results value :export both :tangle julia/p_8.jl
#+end_src

* Problem 9
** Task
Consider $f:\mathbb{R}\rightarrow\mathbb{R}$ $f(x)=\cos(x)$ and the sequence
$x_{0}=2$, $x_{n+1}=x_{n}-\frac{f(x_{n})}{f^{\prime}(x_{n})}$
$n\in\mathbb{N}.$
Implement the sequence in Julia and compare with the bisection method in the interval [0, 2].

** Notes

** Solution
#+begin_src julia :results value :export both :tangle julia/p_9.jl
#+end_src
