#+title: Problem Set 12
#+author: Erik An
#+email: obluda2173@gmail.com
#+date: <2025-11-11>
#+lastmod: <2025-11-11 20:04>
#+options: num:t
#+startup: overview

* Problem 1
** Task
Prove that the set of all polynomials with real coefficients is a commutative ring with identity. Is it an integral domain? Is it a field?

** Notes
- *Questions*
  - What is a ring?
    A ring is a set with binary operations of + and *, which satisfies the following requirements:
    - *Commutative:* inclusion of additive identity 0, and additive inverse for every element.
    - *Associative multiplication:* for all a,b,c ∈ R, (a*b)c = a(b*c) for all a,b,c ∈ R.
    - *Multiplication distribution over addition:* a(b+c) = ab + ac and (a+b)c = ac + bc.

  - What is a commutative ring?
    A set that satisfies requirements for being a ring, in addition to extra requirement of:
    - ab = ba, for all a,b ∈ R.

  - What is identity? (commutative ring with identity)
    A ring that has a multiplicative identity 1 != 0 such that 1*a = a for all a ∈ R.

  - What is an integral domain?
  - What is field?

Some polynomial:
P(x) = a[n]x^n + a[n-1]x^n-1 + ... + a[1]x + a[0]

Set of polynomial:
{a[n]x^n, a[n-1]x^n-1, ..., a[1]x, a[0]}

#+begin_quote
M5: ∀ x ∈ S ∃! element (-x) ∈ S:
    x + (-x) = 0

*Proposition.* A field is an integral domain.

*Proof.* Let F be a field

Let x,y ∈ F : x*y = 0

Suppose x != 0. Then by M5, ∃ x^-1

        x^-1 * x * y = x^-1 * 0

(note for the future: check lecture 32)
#+end_quote

** Solution
* Problem 2
** Task
** Notes
** Solution
* Problem 3
** Task
** Notes
** Solution
* Problem 4
** Task
** Notes
** Solution
* Problem 5
** Task
** Notes
** Solution
* Problem 6
** Task
** Notes
** Solution
* Problem 7
** Task
** Notes
** Solution
* Problem 8
** Task
** Notes
** Solution
* Problem 9
** Task
* Problem 10
** Task
